Repository Icinga/icinga2, pull requests merged in 2018-04, with the labels that each got.

#6192 Elasticsearch: Fix crash with invalid performance data metrics
  lib/perfdata/elasticsearchwriter.cpp
Labels: Crash, Elasticsearch, bug

#6194 Elasticsearch/GELF: Add metric unit to performance data fields
  lib/perfdata/elasticsearchwriter.cpp
  lib/perfdata/gelfwriter.cpp
Labels: Elasticsearch, Graylog, enhancement

#6163 Fix reload handling by updating the PID file before process overtake
  lib/base/application.cpp
  lib/cli/daemoncommand.cpp
Labels: build-fix

#6170 Add option to windows installer to add global zones
  agent/windows-setup-agent/GlobalZonesInputBox.Designer.cs
  agent/windows-setup-agent/GlobalZonesInputBox.cs
  agent/windows-setup-agent/GlobalZonesInputBox.resx
  agent/windows-setup-agent/Icinga2SetupAgent.csproj
  agent/windows-setup-agent/SetupWizard.Designer.cs
  agent/windows-setup-agent/SetupWizard.cs
  doc/06-distributed-monitoring.md
  doc/images/distributed-monitoring/icinga2_windows_setup_wizard_01.png
  doc/images/distributed-monitoring/icinga2_windows_setup_wizard_02.png
  doc/images/distributed-monitoring/icinga2_windows_setup_wizard_02_global_zone.png
  doc/images/distributed-monitoring/icinga2_windows_setup_wizard_03.png
Labels: Configuration, Windows, enhancement

#6196 Fix InfluxDB backslash escaping
  lib/perfdata/influxdbwriter.cpp
Labels: InfluxDB, Metrics, bug

#6198 Deprecate Statusdatawriter
  doc/14-features.md
  lib/compat/statusdatawriter.cpp
Labels: Compat

#6195 Fix crash in remote api console
  lib/remote/consolehandler.cpp
Labels: API, Crash, bug

#6203 Add docs for script debugger and API filters
  doc/20-script-debugger.md
Labels: Documentation

#6201 Handle exceptions from X509Certificate2
  agent/windows-setup-agent/SetupWizard.cs
Labels: Windows

#6204 API: Check if objects exists and return proper error message
  lib/remote/configobjectutility.cpp
Labels: API, bug

#6206 Add ApplicationVersion built-in constant
  doc/17-language-reference.md
  lib/icinga/icingaapplication.cpp
Labels: Configuration, enhancement

#6207 Fix multiple parameter problems for check_nscp_api
  lib/remote/url.cpp
  lib/remote/url.hpp
  plugins/check_nscp_api.cpp
  test/remote-url.cpp
Labels: Plugins, Windows, bug

#6209 Unify zone name settings in node setup/wizard; add connection-less mode for node setup
  doc/06-distributed-monitoring.md
  doc/16-upgrading-icinga-2.md
  lib/cli/nodesetupcommand.cpp
  lib/cli/nodeutility.cpp
  lib/cli/nodeutility.hpp
  lib/cli/nodewizardcommand.cpp
Labels: CLI, enhancement

#6218 attempt to fix issue #5277
  lib/icinga/downtime.cpp
Labels: bug

#6226 Fix broken SELinux anchor in the documentation
  doc/14-features.md
Labels: Documentation, bug

#6224 Update volatile docs
  doc/08-advanced-topics.md
  doc/09-object-types.md
Labels: Documentation

#6227 Fix missing anchors in CLI commands chapter
  doc/11-cli-commands.md
Labels: Documentation, bug

#6230 Unbreak build against Boost 1.67
  lib/base/timer.cpp
  lib/checker/checkercomponent.cpp
  lib/remote/eventqueue.cpp
Labels: build-fix

#6229 Don't use shell variables in sysconfig
  etc/initsystem/icinga2.sysconfig.cmake
Labels: Packages

#6205 API: Unify verbose error messages
  doc/12-icinga2-api.md
  doc/15-troubleshooting.md
  lib/icinga/comment.cpp
  lib/icinga/downtime.cpp
  lib/remote/actionshandler.cpp
  lib/remote/apilistener-configsync.cpp
  lib/remote/configfileshandler.cpp
  lib/remote/configobjectutility.cpp
  lib/remote/configobjectutility.hpp
  lib/remote/configpackageshandler.cpp
  lib/remote/configstageshandler.cpp
  lib/remote/createobjecthandler.cpp
  lib/remote/deleteobjecthandler.cpp
  lib/remote/httputility.cpp
  lib/remote/modifyobjecthandler.cpp
  lib/remote/objectqueryhandler.cpp
  lib/remote/statushandler.cpp
  lib/remote/templatequeryhandler.cpp
  lib/remote/typequeryhandler.cpp
  lib/remote/variablequeryhandler.cpp
Labels: API, enhancement

#6217 Fix check behavior on restart
  lib/icinga/checkable-check.cpp
  lib/icinga/checkable.cpp
  test/icinga-checkable-flapping.cpp
  test/icinga-checkresult.cpp
Labels: Check Execution, bug

#6241 Fix Sysconfig file detection for Icinga 2 settings
  CMakeLists.txt
  etc/initsystem/CMakeLists.txt
  icinga-app/icinga.cpp
  lib/base/application.cpp
  lib/base/utility.cpp
Labels: Packages, bug

#6250 Fix typo
  lib/base/application.cpp
Labels: build-fix

#6251 Add my gpg fingerprint to release docs
  RELEASE.md
Labels: Documentation

#6253 Doc: Add note for not fully supported Plugin collections
  doc/10-icinga-template-library.md
Labels: Documentation

#6254 Enhance release documentation
  RELEASE.md
Labels: Documentation

#6236 Add TLS support for DB IDO PostgreSQL feature
  doc/09-object-types.md
  lib/db_ido_pgsql/idopgsqlconnection.cpp
  lib/db_ido_pgsql/idopgsqlconnection.ti
  lib/pgsql_shim/pgsqlinterface.cpp
  lib/pgsql_shim/pgsqlinterface.hpp
Labels: DB IDO, enhancement

#6243 Update PostgreSQL documentation
  doc/02-getting-started.md
Labels: Documentation

#6260 Revert "fixup set rlimit stack failed condition"
  lib/base/application.cpp
Labels: Check Execution

#6264 Enhance "Getting Started" chapter
  doc/02-getting-started.md
  doc/15-troubleshooting.md
Labels: Documentation

#6267 Update docs to reflect required user* attributes for notification objects
  doc/09-object-types.md
Labels: Documentation

#6271 Enhance advanced topics with (scheduled) downtimes
  doc/04-configuring-icinga-2.md
  doc/06-distributed-monitoring.md
  doc/08-advanced-topics.md
  doc/images/advanced-topics/icingaweb2_downtime_handled.png
Labels: Documentation
