Repository Icinga/icinga2, pull requests merged in 2018-02, with the labels that each got.

#6085 Fix crash with anonymous clients on certificate signing request and storing sent bytes
  lib/remote/jsonrpcconnection.cpp
Labels: Cluster, Crash, build-fix

#6067 Improve Windows builds and testing
  .gitignore
  BUILD_WINDOWS.md
  appveyor.yml
  test/CMakeLists.txt
  test/test-runner.cpp
  tools/win32/build.ps1
  tools/win32/configure.ps1
  tools/win32/download-openssl.ps1
  tools/win32/test.ps1
Labels: Documentation, Windows, enhancement

#6089 Docs: Fix bracket in notification example
  doc/03-monitoring-basics.md
Labels: Documentation

#6090 Fixed URL encoding for HOSTNAME and SERVICENAME in mail notification
  etc/icinga2/scripts/mail-host-notification.sh
  etc/icinga2/scripts/mail-service-notification.sh
Labels: Notifications, enhancement

#5981 SELinux: Add InfluxDB as example for services requiring `icinga2_can_connect_all`.
  doc/14-features.md
  doc/22-selinux.md
Labels: Documentation

#6102 Fix typo in Apply for Rules documentation
  doc/03-monitoring-basics.md
Labels: Documentation

#6101 Add word in operator documentation
  doc/17-language-reference.md
Labels: Documentation

#6109 Add 'used' feature to check_memory
  plugins/check_memory.cpp
  plugins/check_memory.h
Labels: Plugins

#6113 appveyor: Disable artifacts until we use them
  appveyor.yml
Labels: Tests

#6111 Add Upgrading to Icinga 2.8.2 chapter
  doc/16-upgrading-icinga-2.md
  doc/17-language-reference.md
Labels: Documentation

#6114 Fix typo in prepare-dirs
  etc/initsystem/prepare-dirs
Labels: build-fix

#6115 Fix incorrect size of request limits
  lib/remote/httpserverconnection.cpp
Labels: build-fix

#6107 Allow MYSQL_LIB to be specified by ENV variable
  third-party/cmake/FindMySQL.cmake
Labels: code-quality

#6051 Set FOLDER cmake property for the icingaloader target
  icinga-app/CMakeLists.txt
Labels: code-quality

#6050 Replace boost::algorithm::split calls with String::Split
  lib/base/scriptglobal.cpp
Labels: code-quality

#6125 Fix description of the NotificationComponent in notification.conf
  etc/icinga2/features-available/notification.conf
Labels: ITL

#6126 Require systemd headers
  INSTALL.md
  lib/base/CMakeLists.txt
Labels: build-fix

#6128 Adding documentation for configurable global zones during setup
  doc/06-distributed-monitoring.md
Labels: Documentation

#6132 Fix HTTP parser crash/hang
  lib/remote/httprequest.cpp
  lib/remote/httpresponse.cpp
  lib/remote/httpresponse.hpp
  lib/remote/httpserverconnection.cpp
Labels: bug, high-priority

#6116 Fix Windows reload
  lib/base/application.cpp
  lib/cli/daemoncommand.cpp
Labels: Windows

#6133 Limit the number of HTTP/JSON-RPC requests we read in parallel
  lib/base/stream.cpp
  lib/base/stream.hpp
  lib/base/tlsstream.cpp
  lib/base/tlsstream.hpp
  lib/remote/httpserverconnection.cpp
  lib/remote/jsonrpcconnection.cpp
Labels: bug, high-priority
