Repository Icinga/icinga2, pull requests merged in 2018-10, with the labels that each got.

#6647 node setup: always respect --accept-config and --accept-commands
  lib/cli/nodesetupcommand.cpp
Labels: CLI, bug

#6652 Fix check_memory thresholds in 'used' mode
  plugins/check_memory.cpp
Labels: Plugins, bug

#6503 Reduce the log level for missing env macros to debug
  lib/icinga/pluginutility.cpp
Labels: Log, bug

#6646 Update ITL and Docs for memory-windows - show used
  doc/10-icinga-template-library.md
  itl/command-plugins-windows.conf
Labels: ITL, enhancement

#6651 Add 'used' feature to check_swap
  doc/10-icinga-template-library.md
  itl/command-plugins-windows.conf
  plugins/check_swap.cpp
Labels: Plugins, enhancement

#6655 Improve logging for disconnected HTTP clients
  lib/remote/httpserverconnection.cpp
Labels: API, Log, enhancement

#6657 Enable the HTTP request body debug log entry for release builds
  lib/remote/httputility.cpp
Labels: API, Log, enhancement

#6658 Ensure that HTTP/1.0 or 'Connection: close' headers are properly disconnecting the client
  lib/remote/httpresponse.cpp
  lib/remote/httpserverconnection.cpp
Labels: API, bug

#6661 Cache the peer address in the HTTP server
  lib/remote/httpserverconnection.cpp
  lib/remote/httpserverconnection.hpp
Labels: API, Log, code-quality

#6663 Silence config compiler logging for runtime created objects
  lib/config/applyrule.cpp
  lib/config/applyrule.hpp
  lib/config/configitem.cpp
  lib/remote/configobjectutility.cpp
Labels: API, Log, enhancement

#6664 Revert "Initialize Socket Event Engine on application startup"
  lib/base/socketevents.cpp
  lib/base/socketevents.hpp
Labels: build-fix

#6665 Make the two modes of check_http more obvious.
  doc/10-icinga-template-library.md
Labels: Documentation

#6668 Enhance vim syntax highlighting for 2.10
  tools/syntax/vim/syntax/icinga2.vim
Labels: Installation, enhancement

#6670 Add technical concepts for the config compiler and daemon CLI command
  doc/19-technical-concepts.md
Labels: Documentation, enhancement

#6669 Don't throw an error when namespace indexers don't find a valid key
  lib/base/namespace.cpp
Labels: build-fix

#6672 Extend upgrade docs
  doc/09-object-types.md
  doc/16-upgrading-icinga-2.md
Labels: Documentation

#6674 Add a note to the docs on >2 endpoints in a zone
  doc/06-distributed-monitoring.md
Labels: Documentation

#6681 Fix spelling errors.
  icinga-app/icinga.cpp
Labels: code-quality

#6679 Initialize Configuration::InitRunDir for Windows and writing the PID file
  icinga-app/icinga.cpp
Labels: Windows, bug

#6685 Fix regression with API permission filters and namespaces in v2.10
  lib/remote/filterutility.cpp
Labels: API, bug

#6692 Update release docs for Chocolatey
  RELEASE.md
Labels: Documentation

#6690 Extend 09-object-types.md with argument array
  doc/09-object-types.md
Labels: Documentation

#6691 Add missing shutdown/program state dumps for SIGUSR2 reload handler
  lib/base/application.cpp
Labels: bug

#6696 Remove default environment, regression from e678fa1aa5
  icinga-app/icinga.cpp
Labels: bug

#6700 Enhance the addon chapter in the docs
  doc/13-addons.md
  doc/images/addons/dashing_icinga2.png
  doc/images/addons/icingaweb2_businessprocess.png
  doc/images/addons/icingaweb2_grafana.png
  doc/images/addons/icingaweb2_graphite.png
  doc/images/addons/icingaweb2_maps.png
Labels: Documentation

#6701 Add GitHub release tag to README
  README.md
Labels: Documentation

#6704 Put newly configured already running ScheduledDowntime immediately in effect
  lib/icinga/legacytimeperiod.cpp
  lib/icinga/legacytimeperiod.hpp
  lib/icinga/scheduleddowntime.cpp
  lib/icinga/scheduleddowntime.hpp
Labels: Notifications, bug

#6708 Docs: Alpine needs 'edge/main' repository too
  doc/02-getting-started.md
Labels: Documentation

#6707 Fix regression for wrong objects.cache path overwriting icinga2.debug file
  lib/compat/statusdatawriter.cpp
Labels: Compat, bug

#6714 Docs: Add package related changes to the upgrading docs
  doc/13-addons.md
  doc/16-upgrading-icinga-2.md
Labels: Documentation

#6713 Fix typo
  lib/icinga/apiactions.cpp
Labels: code-quality

#6667 Increase dependency recursion limit to 256
  lib/icinga/checkable-dependency.cpp
Labels: Check Execution, enhancement

#6662 Keep the HTTP server connection open until the stream is EOF
  lib/remote/httpserverconnection.cpp
Labels: API, bug

#6718 Call SSL_shutdown() at least twice
  lib/base/tlsstream.cpp
Labels: API, Cluster, bug

#6719 Do not send 'finished reconnecting...' if failed
  lib/remote/apilistener.cpp
Labels: Cluster, Log, bug

#6717 Improve error handling for invalid child_options for API downtime actions
  lib/icinga/apiactions.cpp
Labels: API, bug

#6725 Enable HA for features: Elasticsearch, Gelf, Graphite, InfluxDB, OpenTSDB, Perfdata
  doc/06-distributed-monitoring.md
  doc/09-object-types.md
  doc/16-upgrading-icinga-2.md
  doc/19-technical-concepts.md
  lib/perfdata/elasticsearchwriter.cpp
  lib/perfdata/elasticsearchwriter.hpp
  lib/perfdata/elasticsearchwriter.ti
  lib/perfdata/gelfwriter.cpp
  lib/perfdata/gelfwriter.hpp
  lib/perfdata/gelfwriter.ti
  lib/perfdata/graphitewriter.cpp
  lib/perfdata/graphitewriter.hpp
  lib/perfdata/graphitewriter.ti
  lib/perfdata/influxdbwriter.cpp
  lib/perfdata/influxdbwriter.hpp
  lib/perfdata/influxdbwriter.ti
  lib/perfdata/opentsdbwriter.cpp
  lib/perfdata/opentsdbwriter.hpp
  lib/perfdata/opentsdbwriter.ti
  lib/perfdata/perfdatawriter.cpp
  lib/perfdata/perfdatawriter.hpp
  lib/perfdata/perfdatawriter.ti
Labels: Cluster, enhancement

#6726 Silence the debug log a bit for IDO events
  lib/db_ido/dbevents.cpp
Labels: DB IDO, Log

#6732 Update Windows Agent with new design
  agent/windows-setup-agent/icinga-banner.png
  doc/images/distributed-monitoring/icinga2_windows_setup_installer_01.png
  doc/images/distributed-monitoring/icinga2_windows_setup_installer_02.png
  doc/images/distributed-monitoring/icinga2_windows_setup_installer_03.png
  doc/images/distributed-monitoring/icinga2_windows_setup_installer_04.png
  doc/images/distributed-monitoring/icinga2_windows_setup_installer_05.png
  doc/images/distributed-monitoring/icinga2_windows_setup_wizard_01.png
  doc/images/distributed-monitoring/icinga2_windows_setup_wizard_02.png
  doc/images/distributed-monitoring/icinga2_windows_setup_wizard_02_global_zone.png
  doc/images/distributed-monitoring/icinga2_windows_setup_wizard_03.png
  doc/images/distributed-monitoring/icinga2_windows_setup_wizard_04.png
  doc/images/distributed-monitoring/icinga2_windows_setup_wizard_05_nsclient_01.png
  doc/images/distributed-monitoring/icinga2_windows_setup_wizard_06_finish_no_ticket.png
  doc/images/distributed-monitoring/icinga2_windows_setup_wizard_06_finish_with_ticket.png
  doc/images/distributed-monitoring/icinga2_windows_setup_wizard_examine_config.png
  icinga-installer/bannrbmp.bmp
  icinga-installer/dlgbmp.bmp
Labels: Windows, enhancement

#6709 Fix the Icinga2 version check for versions with more than 5 characters
  lib/methods/icingachecktask.cpp
Labels: bug

#6740 DB IDO: Don't enqueue queries when the feature is paused (HA)
  lib/db_ido_mysql/idomysqlconnection.cpp
  lib/db_ido_pgsql/idopgsqlconnection.cpp
Labels: DB IDO, bug

#6733 Doc: warn about not setting Comment#entry_time
  doc/09-object-types.md
Labels: Documentation, enhancement

#6731 Fix typo
  doc/09-object-types.md
Labels: Documentation, bug
