Repository Icinga/icinga2, pull requests merged in 2018-08, with the labels that each got.

#6505 Fix clusterzonecheck if not connected
  lib/methods/clusterzonechecktask.cpp
Labels: Cluster, bug

#6508 Implement the Dictionary#clear script function
  doc/18-library-reference.md
  lib/base/dictionary-script.cpp
Labels: Configuration, enhancement

#6504 squashfs ignored
  doc/10-icinga-template-library.md
  itl/command-plugins.conf
Labels: ITL, enhancement

#6427 Improve error message for serializing objects with recursive references
  lib/base/serializer.cpp
  lib/base/serializer.hpp
  lib/config/configitem.cpp
Labels: Configuration, Crash, bug

#6526 icinga::PackObject(): shorten conversion to string
  lib/base/object-packer.cpp
Labels: code-quality

#6521 Implement references
  doc/17-language-reference.md
  lib/base/CMakeLists.txt
  lib/base/reference-script.cpp
  lib/base/reference.cpp
  lib/base/reference.hpp
  lib/config/config_parser.yy
  lib/config/expression.cpp
  lib/config/expression.hpp
Labels: Configuration, enhancement

#6528 Document default of User#enable_notifications
  doc/09-object-types.md
Labels: Documentation

#6511 ApiListener: Add support for dynamic port handling
  doc/16-upgrading-icinga-2.md
  doc/17-language-reference.md
  lib/base/socket.cpp
  lib/base/socket.hpp
  lib/remote/apilistener.cpp
  lib/remote/apilistener.hpp
  lib/remote/apilistener.ti
Labels: Cluster, enhancement

#6531 Expose Zone#all_parents via API
  lib/remote/apilistener.cpp
  lib/remote/zone.cpp
  lib/remote/zone.hpp
  lib/remote/zone.ti
Labels: API, enhancement

#6539 Build fix for CentOS 7 and non-unity builds
  lib/remote/pkiutility.hpp
Labels: build-fix

#6544 Remove #include for deprecated header file
  test/base-object-packer.cpp
Labels: code-quality

#6563 [Feature] Cloudera service health CheckCommand
  doc/10-icinga-template-library.md
  itl/plugins-contrib.d/CMakeLists.txt
  itl/plugins-contrib.d/big-data.conf
Labels: ITL, enhancement

#6469 Fix Windows Agent resize behavior
  agent/windows-setup-agent/SetupWizard.Designer.cs
  agent/windows-setup-agent/SetupWizard.cs
Labels: Installation, Windows, bug

#6561 [Feature] Ceph health CheckCommand
  doc/10-icinga-template-library.md
  itl/plugins-contrib.d/storage.conf
Labels: ITL, enhancement

#6556 windows: Allow suppression of extra actions in the MSI package
  icinga-installer/icinga2.wixpatch.cmake
Labels: Installation, Windows, enhancement

#6567 ApiListener: Dump the state file port detail as number
  lib/remote/apilistener.cpp
Labels: build-fix

#6570 Increase limit for simultaneously connected anonymous TLS clients
  lib/remote/apilistener.cpp
Labels: Cluster

#6510 Update windows build scripts
  .gitignore
  appveyor.yml
  tools/win32/build.ps1
  tools/win32/configure.ps1
  tools/win32/download-openssl.ps1
  tools/win32/test.ps1
Labels: Tests, Windows

#6532 Add child_options to ScheduledDowntime
  doc/09-object-types.md
  doc/12-icinga2-api.md
  doc/16-upgrading-icinga-2.md
  lib/icinga/apiactions.cpp
  lib/icinga/downtime.cpp
  lib/icinga/downtime.hpp
  lib/icinga/scheduleddowntime.cpp
  lib/icinga/scheduleddowntime.hpp
  lib/icinga/scheduleddowntime.ti
Labels: Configuration, enhancement
