Repository Icinga/icinga2, pull requests merged in 2018-03, with the labels that each got.

#6136 Add counter for current concurrent checks to Icinga check
  lib/methods/icingachecktask.cpp
Labels: Check Execution, enhancement

#6139 itl/disk: Ignore overlay and netfs filesystems
  doc/10-icinga-template-library.md
  itl/command-plugins.conf
Labels: ITL, enhancement

#6145 Fix incorrect parameter name in the API documentation
  doc/12-icinga2-api.md
Labels: Documentation

#6135 Limit JSON RPC message size
  lib/base/netstring.cpp
  lib/base/netstring.hpp
  lib/remote/apilistener.cpp
  lib/remote/apilistener.hpp
  lib/remote/jsonrpc.cpp
  lib/remote/jsonrpc.hpp
  lib/remote/jsonrpcconnection.cpp
Labels: API, Cluster

#6147 Fix incorrect argument type for JsonRpc::SendMessage
  lib/base/win32.hpp
  lib/remote/jsonrpc.cpp
  lib/remote/jsonrpc.hpp
Labels: bug, build-fix

#6146 Ensure that SetCorked() works properly
  lib/base/socketevents-poll.cpp
  lib/base/tlsstream.cpp
  lib/remote/httpserverconnection.cpp
  lib/remote/jsonrpcconnection.cpp
Labels: bug

#6148 Fix ApiUser unit test
  test/remote-user.cpp
Labels: build-fix

#6160 Replace std::vector:push_back calls with initializer list
  lib/cli/nodesetupcommand.cpp
  lib/cli/nodewizardcommand.cpp
Labels: code-quality

#6166 Fix broken link in README
  README.md
Labels: Documentation, bug

#6169 appveyor: Clean cache when updating appveyor.yml
  appveyor.yml
Labels: build-fix

#6016 Check notification state filters for problems only, not for Custom, etc.
  lib/icinga/notification.cpp
Labels: Notifications, bug

#6058 Clean up the Icinga plugins a bit
  plugins/CMakeLists.txt
  plugins/check_disk.cpp
  plugins/check_disk.h
  plugins/check_load.cpp
  plugins/check_load.h
  plugins/check_memory.cpp
  plugins/check_memory.h
  plugins/check_network.cpp
  plugins/check_nscp_api.cpp
  plugins/check_perfmon.cpp
  plugins/check_perfmon.h
  plugins/check_ping.cpp
  plugins/check_ping.h
  plugins/check_procs.cpp
  plugins/check_procs.h
  plugins/check_service.cpp
  plugins/check_service.h
  plugins/check_swap.cpp
  plugins/check_swap.h
  plugins/check_update.cpp
  plugins/check_update.h
  plugins/check_uptime.cpp
  plugins/check_uptime.h
  plugins/check_users.cpp
  plugins/check_users.h
  plugins/thresholds.cpp
  plugins/thresholds.h
  plugins/thresholds.hpp
Labels: code-quality

#6098 Clean up CORS implementation
  doc/09-object-types.md
  doc/16-upgrading-icinga-2.md
  lib/remote/apilistener.ti
  lib/remote/httpserverconnection.cpp
Labels: API, code-quality, enhancement

#6171 Update copyright of the Windows Agent to 2018
  agent/windows-setup-agent/Properties/AssemblyInfo.cs
Labels: code-quality

#6119 fixup set rlimit stack failed condition
  lib/base/application.cpp
Labels: needs-feedback

#6172 Docs: Add a note to only query the NSClient++ API from the local Icinga 2 client
  doc/06-distributed-monitoring.md
  doc/10-icinga-template-library.md
Labels: Documentation

#6174 Fix crash without CORS setting
  lib/remote/httpserverconnection.cpp
Labels: API, build-fix

#6179 Fix crash in api user command
  lib/cli/apiusercommand.cpp
Labels: CLI, Crash, bug, high-priority

#6176 hashed_password -> password_hash. Fixes #6175
  doc/09-object-types.md
Labels: Documentation, bug

#6177 Doc: Fix typo in API user creation example
  doc/12-icinga2-api.md
Labels: Documentation, bug

#6187 Remove Icinga Studio Screenshots
  doc/images/icinga2-api/icinga2_api_icinga_studio_connect.png
  doc/images/icinga2-api/icinga2_api_icinga_studio_overview.png
Labels: code-quality
