Repository Icinga/icinga2, pull requests merged in 2018-11, with the labels that each got.

#6751 Doc fix: documentation link for apt
  doc/10-icinga-template-library.md
Labels: Documentation

#6743 Doc fix: error in example path.
  doc/05-service-monitoring.md
Labels: Documentation

#6745 Add support for -q argument to Manubulon snmp-storage commmand
  doc/10-icinga-template-library.md
  itl/command-plugins-manubulon.conf
Labels: ITL, enhancement

#6760 armhf: Apply workaround for timer tests with std::bind callbacks
  test/base-timer.cpp
Labels: Packages, Tests, bug

#6759 Fix possible double free in StreamLogger::BindStream()
  lib/base/streamlogger.cpp
Labels: Log, bug

#6762 fixes #6758
  etc/initsystem/icinga2.service.cmake
Labels: Installation, Packages

#6756 ITL: Add repeat_key for check_nwc_health
  itl/plugins-contrib.d/network-components.conf
Labels: ITL

#6479 SocketEvents: inherit from Stream
  lib/base/socketevents-epoll.cpp
  lib/base/socketevents-poll.cpp
  lib/base/socketevents.cpp
  lib/base/socketevents.hpp
  lib/base/tlsstream.cpp
  lib/base/tlsstream.hpp
Labels: code-quality

#6770 Fix deadlock in GraphiteWriter
  lib/perfdata/graphitewriter.cpp
  lib/perfdata/graphitewriter.hpp
Labels: bug

#6771 Implement unit tests for Dictionary initializers
  test/CMakeLists.txt
  test/base-dictionary.cpp
Labels: Tests

#6773 Initialize ICINGA2_ERROR_LOG inside the systemd environment
  etc/initsystem/icinga2.service.cmake
Labels: Installation, Packages

#6480 Modify windows check_update command to allow specifying thresholds.
  doc/10-icinga-template-library.md
  itl/command-plugins-windows.conf
  plugins/check_update.cpp
Labels: Plugins, Windows, enhancement

#6775 Add technical docs for the check scheduler (general, initial check, offsets)
  doc/19-technical-concepts.md
Labels: Documentation

#6791 Docs: Add a section for DB IDO Cleanup
  doc/14-features.md
Labels: Documentation

#6800 Fix check_perfmon to support non-localized names
  plugins/check_perfmon.cpp
Labels: Plugins, Windows, bug

#6808 Remove redundand check for object existence on creation via API
  lib/remote/configobjectutility.cpp
Labels: API, bug
