Repository Icinga/icinga2, pull requests merged in 2018-12, with the labels that each got.

#6811 Fix state conditions in check_memory and check_swap
  plugins/check_memory.cpp
  plugins/check_swap.cpp
  plugins/thresholds.cpp
  plugins/thresholds.hpp
Labels: Plugins, Windows, bug

#6814 Restore 'Connection: close' behaviour in HTTP responses
  lib/remote/httpresponse.cpp
  lib/remote/httpserverconnection.cpp
Labels: API, bug

#6819 Enhance and unify development docs for debug, develop, package
  BUILD_WINDOWS.md
  INSTALL.md
  README.md
  doc/21-development.md
Labels: Documentation, enhancement

#6786 DSL: Implement getenv()
  doc/18-library-reference.md
  icinga-app/icinga.cpp
  lib/base/application.cpp
  lib/base/scriptutils.cpp
  lib/base/scriptutils.hpp
  lib/base/utility.cpp
  lib/base/utility.hpp
  lib/cli/consolecommand.cpp
Labels: Configuration, enhancement

#6801 Add varnish CheckCommand definition
  doc/10-icinga-template-library.md
  itl/plugins-contrib.d/web.conf
Labels: ITL, enhancement

#6750 #6749 Wrong operator on stride variable causing incorrect behaviour
  lib/icinga/legacytimeperiod.cpp
Labels: Configuration, bug

#6757 Fix that no_more_notifications gets reset when Recovery notifications are filtered away
  lib/icinga/notification.cpp
Labels: Notifications, bug

#6815 ThreadPool#Stop(): discard non-processed queue items
  lib/base/threadpool.cpp
Labels: bug

#6823 ITL: Support --list argument to check_apt
  doc/10-icinga-template-library.md
  itl/command-plugins.conf
Labels: ITL, enhancement

#6820 Only create downtimes from non-paused ScheduledDowntime objects in HA enabled cluster zones
  lib/icinga/scheduleddowntime.cpp
Labels: Cluster, bug

#6817 HttpServerConnection#DataAvailableHandler(): be aware of being called multiple times concurrently
  lib/remote/httpserverconnection.cpp
Labels: API, bug

#6829 API Event Streams: Add 'command' for Notification events
  doc/12-icinga2-api.md
  lib/icinga/apievents.cpp
Labels: API, enhancement

#6843 Improve AppVeyor builds
  appveyor.yml
  tools/win32/configure.ps1
Labels: Tests, Windows

#6826 Downtime#HasValidConfigOwner(): wait for ScheduledDowntimes
  lib/icinga/downtime.cpp
  lib/icinga/scheduleddowntime.cpp
  lib/icinga/scheduleddowntime.hpp
Labels: Configuration, bug

#6821 Don't delete downtimes in satellite zones
  lib/icinga/downtime.cpp
  lib/icinga/downtime.ti
Labels: Configuration, bug

#6850 Fix ITL CheckCommand disk
  doc/10-icinga-template-library.md
  itl/command-plugins.conf
Labels: ITL

#6852 Add haproxy CheckCommand definition
  doc/10-icinga-template-library.md
  itl/plugins-contrib.d/web.conf
Labels: ITL

#6864 Add phpfpm-status CheckCommand definition
  doc/10-icinga-template-library.md
  itl/plugins-contrib.d/web.conf
Labels: ITL, enhancement

#6863 Add hddtemp CheckCommand definition
  doc/10-icinga-template-library.md
  itl/plugins-contrib.d/hardware.conf
Labels: ITL, enhancement

#6862 Add proxysql CheckCommand definition
  doc/10-icinga-template-library.md
  itl/plugins-contrib.d/databases.conf
Labels: ITL, enhancement
