Repository Icinga/icinga2, pull requests merged in 2018-07, with the labels that each got.

#6423 Fix missing next check update causing the scheduler to execute checks too often
  lib/checker/checkercomponent.cpp
  lib/icinga/checkable-check.cpp
Labels: build-fix

#6429 Make HttpServerConnection#m_DataHandlerMutex a boost::recursive_mutex
  lib/remote/httpserverconnection.cpp
  lib/remote/httpserverconnection.hpp
Labels: bug, build-fix

#6433 Docs: Fix typos in 03-monitoring-basics.md
  doc/03-monitoring-basics.md
Labels: Documentation, bug

#6436 Update tested Elasticsearch version
  doc/14-features.md
Labels: Documentation

#6439 Revert "Fix obsolete parameter in Systemd script"
  etc/initsystem/icinga2.service.cmake
Labels: build-fix

#6451 Fix initscripts
  etc/initsystem/icinga2.init.d.cmake
  etc/initsystem/prepare-dirs.cmake
  etc/initsystem/safe-reload.cmake
Labels: Packages, bug

#6467 Start and stop the timer thread lazily
  lib/base/timer.cpp
  lib/base/timer.hpp
Labels: Tests, bug, build-fix

#6470 Fix spelling errors.
  lib/base/socket.cpp
  lib/checker/checkercomponent.cpp
  lib/cli/nodesetupcommand.cpp
  lib/icinga/checkable-check.cpp
  lib/icinga/checkable-notification.cpp
  lib/icinga/clusterevents-check.cpp
  lib/icinga/notification.cpp
  lib/notification/notificationcomponent.cpp
  third-party/yajl/src/api/yajl_parse.h
Labels: code-quality

#6487 Fix "Discard" message being warning
  lib/remote/apilistener-configsync.cpp
Labels: Log, bug

#6458 Fix debug build log entry for ConfigItem activation priority
  lib/config/configitem.cpp
Labels: code-quality

#6456 Keep notes for immediately log flushing
  lib/base/logger.cpp
Labels: code-quality

#6440 Fix typo
  lib/cli/apisetuputility.cpp
Labels: code-quality

#6455 Log something when the Filelogger has been started
  lib/base/filelogger.cpp
Labels: Log, enhancement

#6379 Throw config error when using global zones as parent
  lib/remote/zone.cpp
Labels: Configuration, enhancement

#6408 ObjectLock#Unlock(): don't reset m_Object->m_LockOwner too early
  lib/base/object.hpp
  lib/base/objectlock.cpp
Labels: bug

#6386 Fix that TimePeriod segments are not cleared on restart
  lib/icinga/timeperiod.cpp
Labels: Configuration, bug

#6475 lib->compat->statusdatawriter: fix notifications_enabled
  lib/compat/statusdatawriter.cpp
Labels: Compat

#6110 Implement support for optionally specifying the 'var' keyword in 'for' loops
  doc/17-language-reference.md
  lib/config/config_parser.yy
Labels: Configuration, enhancement

#6414 Implement support for the --env command-line argument
  doc/06-distributed-monitoring.md
  icinga-app/icinga.cpp
  icinga-installer/icinga2.wixpatch.cmake
  lib/cli/apisetupcommand.cpp
  lib/cli/apisetupcommand.hpp
  lib/cli/apisetuputility.cpp
  lib/cli/apisetuputility.hpp
  lib/cli/featureutility.cpp
  lib/cli/featureutility.hpp
  lib/remote/apilistener.cpp
  lib/remote/apilistener.hpp
Labels: Configuration, enhancement

#6491 Feature/itl vmware health
  doc/10-icinga-template-library.md
  itl/plugins-contrib.d/vmware.conf
Labels: ITL, enhancement

#6488 Fix typo with the CheckCommand cert
  doc/10-icinga-template-library.md
Labels: Documentation, ITL

#6489 Implement object packer for consistent hashing
  lib/base/CMakeLists.txt
  lib/base/object-packer.cpp
  lib/base/object-packer.hpp
Labels: code-quality, enhancement

#6494 Test PackObject
  test/CMakeLists.txt
  test/base-object-packer.cpp
Labels: Tests

#6410 Remove unused code
  lib/remote/apiclient.cpp
  lib/remote/apiclient.hpp
Labels: code-quality
