Repository Icinga/icinga2, pull requests merged in 2018-06, with the labels that each got.

#6347 SELinux: Allow notification plugins to read local users …
  tools/selinux/icinga2.te
Labels: Packages

#6350 clarify the permision system of the api in the docs
  doc/12-icinga2-api.md
Labels: Documentation, enhancement

#6357 Increase header size to 8KB for HTTP requests
  doc/12-icinga2-api.md
  lib/remote/httprequest.cpp
Labels: API

#6343 Fix that checks with command_endpoint don't return any check results
  lib/icinga/checkable-check.cpp
Labels: Check Execution, Cluster, bug

#6367 Revert "Fix Windows reload"
  lib/base/application.cpp
  lib/cli/daemoncommand.cpp
Labels: Windows

#6372 Remove the import of 'legacy-timeperiod' in the docs
  doc/08-advanced-topics.md
  doc/09-object-types.md
Labels: Documentation

#6373 Drop command template imports for versions < 2.6 in the docs
  doc/09-object-types.md
Labels: Documentation

#6374 Docs: Add an additional note for VMWare timeouts on Ubuntu 16.04 LTS
  doc/05-service-monitoring.md
Labels: Documentation

#6375 some minor fixes in the flapping documentation
  doc/08-advanced-topics.md
Labels: Documentation

#6377 Fix missing name for workqueue while creating runtime objects via API
  lib/remote/configobjectutility.cpp
Labels: code-quality

#6371 ApiListener#NewClientHandlerInternal(): Explicitly close the TLS stream on any failure
  lib/remote/apilistener.cpp
Labels: API, Cluster, bug

#6368 Fix program option parsing
  lib/cli/clicommand.cpp
Labels: CLI, bug

#6383 HttpRequest#ParseBody(): indicate success on complete body
  lib/remote/httprequest.cpp
Labels: API, CLI, bug

#6384 Remove leftover for sysconfig file parsing
  icinga-app/icinga.cpp
  lib/base/application.cpp
  lib/base/application.hpp
Labels: build-fix

#6391 Docs: Fix icinga.com link
  doc/01-about.md
Labels: Documentation

#6390 Docs: Update Windows wizard images
  doc/06-distributed-monitoring.md
  doc/images/distributed-monitoring/icinga2_windows_setup_wizard_01.png
  doc/images/distributed-monitoring/icinga2_windows_setup_wizard_02.png
  doc/images/distributed-monitoring/icinga2_windows_setup_wizard_02_global_zone.png
  doc/images/distributed-monitoring/icinga2_windows_setup_wizard_03.png
Labels: Documentation, Windows

#6397 TlsStream#IsEof(): fix false positive EOF indicator
  lib/base/tlsstream.cpp
Labels: Plugins, Windows, bug

#6393 Stream#ReadLine(): fix false positive buffer underflow indicator
  lib/base/stream.cpp
Labels: API, Elasticsearch, bug

#6400 Enhance debug logging for check_nscp_api
  plugins/check_nscp_api.cpp
Labels: Plugins, Windows, enhancement

#6381 Fix sysconfig not being handled correctly by sysvinit
  etc/initsystem/icinga2.init.d.cmake
  etc/initsystem/prepare-dirs.cmake
  etc/initsystem/safe-reload.cmake
Labels: Packages, build-fix

#6401 Fix connection error handling in Elasticsearch and InfluxDB features
  lib/perfdata/elasticsearchwriter.cpp
  lib/perfdata/influxdbwriter.cpp
Labels: Elasticsearch, InfluxDB, bug

#6402 Use SSL_pending() for remaining TLS stream data
  lib/base/tlsstream.cpp
Labels: Cluster, code-quality

#6403 Conform to RFC for CRLF in HTTP requests
  lib/remote/httprequest.cpp
Labels: API, bug

#6413 Fix table in Livestatus Filters
  doc/14-features.md
Labels: Documentation

#6411 Windows: Conform to the Plugin API spec for performance label quoting
  plugins/check_disk.cpp
  plugins/check_load.cpp
  plugins/check_memory.cpp
  plugins/check_network.cpp
  plugins/check_perfmon.cpp
  plugins/check_service.cpp
  plugins/check_swap.cpp
  plugins/check_update.cpp
  plugins/check_uptime.cpp
  plugins/check_users.cpp
Labels: Plugins, Windows, bug

#6412 Fix output formatting in windows plugins
  plugins/check_memory.cpp
  plugins/check_ping.cpp
  plugins/thresholds.cpp
  plugins/thresholds.hpp
Labels: Plugins, Windows

#6407 Fix wrong UOM in check_uptime windows plugin
  plugins/check_uptime.cpp
  plugins/thresholds.cpp
  plugins/thresholds.hpp
Labels: Windows, bug

#6308 Update lsi-raid ITL command
  doc/10-icinga-template-library.md
  itl/plugins-contrib.d/raid-controller.conf
Labels: ITL, enhancement

#6389 New ITL command nscp-local-tasksched
  doc/10-icinga-template-library.md
  itl/command-nscp-local.conf
Labels: ITL, enhancement

#6348 Fix for catalogued locally databases. Fixes #6338
  doc/10-icinga-template-library.md
  itl/plugins-contrib.d/databases.conf
Labels: ITL, enhancement
