Repository Icinga/icinga2, pull requests merged in 2019-04, with the labels that each got.

#7062 Improve DB IDO HA failover behaviour
  doc/09-object-types.md
  doc/16-upgrading-icinga-2.md
  lib/base/workqueue.hpp
  lib/db_ido/dbconnection.cpp
  lib/db_ido/dbconnection.ti
  lib/db_ido/idochecktask.cpp
  lib/db_ido_mysql/idomysqlconnection.cpp
  lib/db_ido_pgsql/idopgsqlconnection.cpp
  lib/remote/CMakeLists.txt
  lib/remote/apilistener-authority.cpp
  lib/remote/apilistener.cpp
Labels: Cluster, DB IDO, enhancement

#7071 Technical Concepts: Add config compiler references
  doc/19-technical-concepts.md
Labels: Documentation

#7059 Document check_command may be a string
  doc/12-icinga2-api.md
Labels: Documentation

#7064 Add command `icingacli-elasticsearch` to ITL
  doc/10-icinga-template-library.md
  itl/plugins-contrib.d/icingacli.conf
Labels: ITL, enhancement

#7008 Use C++11 atomics for our intrusive pointers
  lib/base/object.cpp
  lib/base/object.hpp
Labels: code-quality

#7000 Don't abuse goto for building simple loops
  lib/base/application.cpp
  lib/base/process.cpp
Labels: code-quality

#7074 Impersonate as Icinga user, not root
  doc/16-upgrading-icinga-2.md
  lib/cli/apisetupcommand.cpp
  lib/cli/featuredisablecommand.cpp
  lib/cli/featureenablecommand.cpp
  lib/cli/nodesetupcommand.cpp
  lib/cli/nodewizardcommand.cpp
Labels: CLI, enhancement

#6918 Add technical concept docs for our internal JSON-RPC API messages
  doc/19-technical-concepts.md
Labels: Documentation

#7077 Always update object authority & don't skip notifications in non-API setups
  lib/notification/notificationcomponent.cpp
  lib/remote/apilistener-authority.cpp
Labels: Cluster, bug, build-fix

#7078 Deprecate ExternalCommandListener feature ('command') and adjust log warnings to the roadmap
  doc/09-object-types.md
  doc/14-features.md
  lib/compat/checkresultreader.cpp
  lib/compat/compatlogger.cpp
  lib/compat/externalcommandlistener.cpp
  lib/compat/statusdatawriter.cpp
Labels: Documentation

#7080 Docs: Improve config object types chapter
  doc/09-object-types.md
Labels: Documentation

#7082 Troubleshooting docs: Add Windows agents without NodeName constant
  doc/15-troubleshooting.md
Labels: Documentation

#7085 Remove not needed inline code tag
  doc/16-upgrading-icinga-2.md
Labels: Documentation, build-fix

#7076 /v1/events: terminate on disconnect
  lib/remote/actionshandler.cpp
  lib/remote/actionshandler.hpp
  lib/remote/configfileshandler.cpp
  lib/remote/configfileshandler.hpp
  lib/remote/configpackageshandler.cpp
  lib/remote/configpackageshandler.hpp
  lib/remote/configstageshandler.cpp
  lib/remote/configstageshandler.hpp
  lib/remote/consolehandler.cpp
  lib/remote/consolehandler.hpp
  lib/remote/createobjecthandler.cpp
  lib/remote/createobjecthandler.hpp
  lib/remote/deleteobjecthandler.cpp
  lib/remote/deleteobjecthandler.hpp
  lib/remote/eventqueue.cpp
  lib/remote/eventqueue.hpp
  lib/remote/eventshandler.cpp
  lib/remote/eventshandler.hpp
  lib/remote/httphandler.cpp
  lib/remote/httphandler.hpp
  lib/remote/httpserverconnection.cpp
  lib/remote/httpserverconnection.hpp
  lib/remote/infohandler.cpp
  lib/remote/infohandler.hpp
  lib/remote/modifyobjecthandler.cpp
  lib/remote/modifyobjecthandler.hpp
  lib/remote/objectqueryhandler.cpp
  lib/remote/objectqueryhandler.hpp
  lib/remote/statushandler.cpp
  lib/remote/statushandler.hpp
  lib/remote/templatequeryhandler.cpp
  lib/remote/templatequeryhandler.hpp
  lib/remote/typequeryhandler.cpp
  lib/remote/typequeryhandler.hpp
  lib/remote/variablequeryhandler.cpp
  lib/remote/variablequeryhandler.hpp
Labels: API, bug, build-fix

#7087 HttpServerConnection: Log the user agent field for new requests too
  lib/remote/httpserverconnection.cpp
Labels: API, Log, enhancement

#7079 Build Windows with Visual Studio 2017
  CMakeLists.txt
  agent/CMakeLists.txt
  agent/windows-setup-agent/Icinga2SetupAgent.csproj
  appveyor.yml
  choco/CMakeLists.txt
  choco/chocolateyInstall.ps1.cmake
  choco/icinga2.nuspec.cmake
  plugins/check_swap.cpp
  tools/win32/build.ps1
  tools/win32/configure.ps1
  tools/win32/download-openssl.ps1
  tools/win32/load-vsenv.ps1
  tools/win32/test.ps1
Labels: Windows, enhancement

#7093 Docs: Update version specific changes for 2.11
  doc/03-monitoring-basics.md
  doc/06-distributed-monitoring.md
  doc/08-advanced-topics.md
  doc/11-cli-commands.md
  doc/16-upgrading-icinga-2.md
  doc/17-language-reference.md
  doc/18-library-reference.md
Labels: Documentation

#7073 Improve docs for 2.11: Development, test snapshot packages & installation repos
  doc/01-about.md
  doc/02-getting-started.md
  doc/15-troubleshooting.md
  doc/16-upgrading-icinga-2.md
  doc/19-technical-concepts.md
  doc/21-development.md
  doc/images/development/windows_boost_build_dev_cmd.png
Labels: Documentation

#7109 Improve code docs for cluster message routing conditions
  lib/remote/apilistener.cpp
  lib/remote/apilistener.hpp
Labels: code-quality

#7115 Improve REST API docs
  doc/11-cli-commands.md
  doc/12-icinga2-api.md
  doc/19-technical-concepts.md
Labels: Documentation

#7116 Drop Checkable#reachable in favor of #last_reachable
  lib/icinga/checkable.cpp
  lib/icinga/checkable.hpp
  lib/icinga/checkable.ti
Labels: build-fix

#7120 Ignore synced config zones where no config item exists
  lib/cli/daemonutility.cpp
Labels: Cluster, Configuration, bug

#7113 use dedicated permissions namespace for scriptframe in filterutility
  lib/remote/eventqueue.cpp
  lib/remote/filterutility.cpp
Labels: API, bug

#7122 FilterUtility::EvaluateFilter(): ensure not to modify the global namespace
  lib/remote/filterutility.cpp
Labels: bug

#7121 Fix that MaxConcurrentChecks constant is overridden from 'checker' feature
  doc/09-object-types.md
  doc/12-icinga2-api.md
  doc/16-upgrading-icinga-2.md
  icinga-app/icinga.cpp
  lib/base/application.cpp
  lib/base/application.hpp
  lib/base/configuration.cpp
  lib/base/configuration.hpp
  lib/base/configuration.ti
  lib/checker/checkercomponent.cpp
  lib/checker/checkercomponent.ti
  lib/icinga/clusterevents-check.cpp
  lib/icinga/icingaapplication.cpp
  lib/icinga/icingaapplication.hpp
  lib/remote/configpackageutility.cpp
Labels: Check Execution, bug

#7112 Include host state in Service#handled and Service#severity
  lib/icinga/checkable.hpp
  lib/icinga/service.cpp
  lib/icinga/service.hpp
Labels: code-quality

#7050 Implement previous_state_change
  lib/icinga/checkable-check.cpp
  lib/icinga/checkable.ti
Labels: Check Execution, enhancement

#7128 Re-write ObjectLock's implementation details
  lib/base/object.cpp
  lib/base/object.hpp
  lib/base/objectlock.cpp
  lib/base/objectlock.hpp
Labels: code-quality

#7126 ApiListener#ApiTimerHandler(): delete all replayed logs
  lib/remote/apilistener.cpp
Labels: Cluster, bug

#7127 ApiListener#RotateLogFile(): don't overwrite previous log
  lib/remote/apilistener.cpp
Labels: Cluster, bug

#7133 Use new I/O engine in PkiUtility::FetchCert() and PkiUtility::RequestCertificate()
  lib/base/netstring.cpp
  lib/base/netstring.hpp
  lib/base/tcpsocket.hpp
  lib/base/tlsstream.cpp
  lib/base/tlsstream.hpp
  lib/remote/apilistener.cpp
  lib/remote/jsonrpc.cpp
  lib/remote/jsonrpc.hpp
  lib/remote/jsonrpcconnection-pki.cpp
  lib/remote/pkiutility.cpp
Labels: API, CLI

#7137 JsonRpcConnection: reduce log spam on disconnect
  lib/remote/jsonrpcconnection.cpp
Labels: Cluster, build-fix

#7135 Use new I/O engine in ElasticsearchWriter
  lib/perfdata/elasticsearchwriter.cpp
  lib/perfdata/elasticsearchwriter.hpp
Labels: Elasticsearch

#7129 avoid incrementing Ptr which could be already be in destruction-phase
  lib/base/timer.cpp
  lib/base/timer.hpp
  test/base-timer.cpp
Labels: bug

#7130 StreamLogger#BindStream(): set #m_FlushLogTimer only if needed
  lib/base/streamlogger.cpp
Labels: bug

#7004 Timer::TimerThreadProc(): use C++11 lambda instead of bind()
  lib/base/timer.cpp
Labels: code-quality

#7140 Add log message for log rotate; update docs
  doc/14-features.md
  lib/base/application.cpp
Labels: Documentation, Log

#6988 ThreadPool: use the Boost ASIO thread pool under the hood
  lib/base/exception.cpp
  lib/base/exception.hpp
  lib/base/scriptglobal.cpp
  lib/base/socketevents-epoll.cpp
  lib/base/socketevents-poll.cpp
  lib/base/socketevents.cpp
  lib/base/threadpool.cpp
  lib/base/threadpool.hpp
  lib/cli/apisetuputility.cpp
  lib/config/configcompilercontext.cpp
  lib/config/configitem.cpp
  lib/remote/apilistener-filesync.cpp
  lib/remote/configfileshandler.cpp
  lib/remote/configobjectutility.cpp
  lib/remote/consolehandler.cpp
  lib/remote/filterutility.cpp
  plugins/check_nscp_api.cpp
Labels: code-quality, enhancement

#7102 Replace self-written filesystem ops with boost.filesystem
  CMakeLists.txt
  lib/base/configobject.cpp
  lib/base/scriptglobal.cpp
  lib/base/utility.cpp
  lib/base/utility.hpp
  lib/cli/apisetuputility.cpp
  lib/cli/nodesetupcommand.cpp
  lib/cli/nodeutility.cpp
  lib/cli/nodewizardcommand.cpp
  lib/compat/checkresultreader.cpp
  lib/compat/externalcommandlistener.cpp
  lib/compat/statusdatawriter.cpp
  lib/config/configcompilercontext.cpp
  lib/icinga/icingaapplication.cpp
  lib/perfdata/perfdatawriter.cpp
  lib/remote/apilistener.cpp
  lib/remote/configobjectutility.cpp
  lib/remote/jsonrpcconnection-pki.cpp
Labels: code-quality

#6722 Add notification result store/sync
  doc/08-advanced-topics.md
  lib/compat/compatlogger.cpp
  lib/compat/compatlogger.hpp
  lib/db_ido/dbevents.cpp
  lib/db_ido/dbevents.hpp
  lib/icinga/CMakeLists.txt
  lib/icinga/checkable-notification.cpp
  lib/icinga/checkable.hpp
  lib/icinga/clusterevents.cpp
  lib/icinga/clusterevents.hpp
  lib/icinga/notification.cpp
  lib/icinga/notification.hpp
  lib/icinga/notification.ti
  lib/icinga/notificationcommand.cpp
  lib/icinga/notificationcommand.hpp
  lib/icinga/notificationresult.cpp
  lib/icinga/notificationresult.hpp
  lib/icinga/notificationresult.ti
  lib/methods/pluginnotificationtask.cpp
  lib/methods/pluginnotificationtask.hpp
  lib/perfdata/gelfwriter.cpp
  lib/perfdata/gelfwriter.hpp
Labels: Cluster, Notifications, enhancement

#7088 Implement new event queue for ASIO consumers
  lib/icinga/apievents.cpp
  lib/remote/eventqueue.cpp
  lib/remote/eventqueue.hpp
  lib/remote/eventshandler.cpp
Labels: API, enhancement

#7124 Namespace: place ObjectLock in all methods
  lib/base/namespace.cpp
Labels: code-quality

#7146 Update release procedure
  CHANGELOG.md
  RELEASE.md
  changelog.py
  doc/12-icinga2-api.md
Labels: Documentation

#7148 Add --cn parameter to 'api setup' CLI command allowing hostname overrides
  doc/11-cli-commands.md
  lib/cli/apisetupcommand.cpp
  lib/cli/apisetupcommand.hpp
Labels: API, CLI, enhancement

#7151 Documentation: add missing argument to chkconfig command.
  doc/02-getting-started.md
Labels: Documentation

#6734 db ido: remove redundant mysql indexes
  lib/db_ido_mysql/schema/mysql.sql
  lib/db_ido_mysql/schema/upgrade/2.11.0.sql
Labels: DB IDO

#7145 Raise .NET target version to 4.6
  CMakeLists.txt
  agent/windows-setup-agent/App.config
  agent/windows-setup-agent/Icinga2SetupAgent.csproj
  agent/windows-setup-agent/Properties/Resources.Designer.cs
  agent/windows-setup-agent/Properties/Settings.Designer.cs
  doc/06-distributed-monitoring.md
  doc/16-upgrading-icinga-2.md
  doc/21-development.md
  icinga-installer/icinga2.wixpatch.cmake
Labels: Packages, Windows

#7152 account for adjusted interface of mysql8
  lib/mysql_shim/mysqlinterface.cpp
  lib/mysql_shim/mysqlinterface.hpp
Labels: DB IDO, bug

#7153 Fix compiler warnings in Windows plugins
  plugins/check_perfmon.cpp
  plugins/check_ping.cpp
  plugins/check_service.cpp
  plugins/check_update.cpp
  plugins/check_uptime.cpp
Labels: Plugins, Windows, code-quality

#7150 Ensure that runtime created API objects survive a restart
  doc/15-troubleshooting.md
  doc/16-upgrading-icinga-2.md
  lib/cli/daemoncommand.cpp
  lib/remote/apilistener-configsync.cpp
  lib/remote/apilistener.cpp
  lib/remote/apilistener.hpp
  lib/remote/configpackageutility.cpp
  lib/remote/configpackageutility.hpp
Labels: API, bug
