Repository Icinga/icinga2, pull requests merged in 2019-02, with the labels that each got.

#6853 Checkable: require zone to be set if command_endpoint is set
  lib/icinga/checkable.cpp
Labels: Cluster, Configuration, Log

#6914 ClusterEvents::AcknowledgementSet event should forward 'persistent' attribute
  lib/icinga/clusterevents.cpp
Labels: Cluster, bug

#6901 TcpSocket#Bind(): also set SO_REUSEPORT
  lib/base/tcpsocket.cpp
Labels: API, bug

#6928 Doc: Add .NET 3.5 to the windows build stack
  doc/21-development.md
Labels: Documentation

#6858 Make string builder reusable
  lib/base/CMakeLists.txt
  lib/base/object-packer.cpp
  lib/base/stringbuilder.cpp
  lib/base/stringbuilder.hpp
Labels: code-quality

#6935 Enhance notification logging
  lib/icinga/checkable-notification.cpp
  lib/icinga/notification.cpp
  lib/notification/notificationcomponent.cpp
Labels: Log, Notifications, enhancement

#6894 Fix checkresults from the future breaking checks
  lib/icinga/checkable-check.cpp
Labels: Check Execution, bug

#6940 Fix check_swap percentage calculation
  plugins/check_swap.cpp
Labels: Plugins, Windows, bug

#6944 Troubleshooting: Add notes on ephemeral port range blocking on Windows agents
  doc/15-troubleshooting.md
Labels: Documentation

#6943 Avoid duplicating non-zero count message replay messages in the debug log
  lib/remote/apilistener.cpp
Labels: Log

#6748 Fix api setup to automatically create the conf.d directory
  lib/cli/apisetuputility.cpp
Labels: CLI, bug

#6577 Include api user configuration file during api setup
  lib/cli/apisetuputility.cpp
  lib/cli/nodeutility.cpp
  lib/cli/nodeutility.hpp
Labels: CLI, Configuration

#6934 Raise required Boost version to 1.53
  CMakeLists.txt
  doc/21-development.md
Labels: Documentation, Packages

#6854 Make UnameHelper() efficient
  lib/base/utility.cpp
Labels: CLI

#6882 InfluxdbWriter#Stop(): flush buffer
  lib/perfdata/influxdbwriter.cpp
  lib/perfdata/influxdbwriter.hpp
Labels: InfluxDB, bug

#6857 Url#m_Query: preserve order
  lib/remote/apiclient.cpp
  lib/remote/httputility.cpp
  lib/remote/url.cpp
  lib/remote/url.hpp
  test/remote-url.cpp
Labels: Plugins, Windows, bug

#6949 Doc fix: update check_rbl parameter
  doc/10-icinga-template-library.md
Labels: Documentation

#6956 Escape pipe symbol in api documentation
  doc/12-icinga2-api.md
Labels: Documentation

#6958 Debug: Log calls to ConfigObject::Deactivate()
  lib/base/configobject.cpp
Labels: code-quality

#6953 Fix indent in configcompiler.cpp
  lib/config/configcompiler.cpp
Labels: code-quality

#6896 Notification#BeginExecuteNotification(): SetNextNotification() correctly
  lib/icinga/notification.cpp
Labels: Notifications

#6963 Add missing args for apache-status and fix a few typos
  doc/10-icinga-template-library.md
  itl/plugins-contrib.d/web.conf
Labels: ITL, enhancement

#6971 Activate downtimes before any checkable object
  lib/icinga/downtime.ti
Labels: Notifications, bug

#6972 Fix formatting in development docs
  doc/21-development.md
Labels: build-fix

#6975 Fix nested hostgroup example
  doc/23-migrating-from-icinga-1x.md
Labels: Documentation

#6970 Improve reload handling for features (metric & queue flush, activation priority)
  doc/17-language-reference.md
  lib/base/application.cpp
  lib/base/configobject.cpp
  lib/base/configuration.cpp
  lib/base/configuration.hpp
  lib/base/configuration.ti
  lib/checker/checkercomponent.cpp
  lib/checker/checkercomponent.hpp
  lib/checker/checkercomponent.ti
  lib/db_ido/servicedbobject.cpp
  lib/db_ido_mysql/idomysqlconnection.cpp
  lib/db_ido_pgsql/idopgsqlconnection.cpp
  lib/icinga/downtime.ti
  lib/icinga/icingaapplication.ti
  lib/notification/notificationcomponent.ti
  lib/perfdata/elasticsearchwriter.cpp
  lib/perfdata/elasticsearchwriter.ti
  lib/perfdata/gelfwriter.cpp
  lib/perfdata/gelfwriter.hpp
  lib/perfdata/gelfwriter.ti
  lib/perfdata/graphitewriter.cpp
  lib/perfdata/graphitewriter.hpp
  lib/perfdata/graphitewriter.ti
  lib/perfdata/influxdbwriter.cpp
  lib/perfdata/influxdbwriter.hpp
  lib/perfdata/influxdbwriter.ti
  lib/perfdata/opentsdbwriter.cpp
  lib/perfdata/opentsdbwriter.ti
  lib/perfdata/perfdatawriter.cpp
  lib/perfdata/perfdatawriter.hpp
  lib/perfdata/perfdatawriter.ti
  lib/remote/configpackageutility.cpp
Labels: Check Execution, DB IDO, Log, Metrics, bug
