Repository Icinga/icinga2, pull requests merged in 2019-05, with the labels that each got.

#7157 DB IDO: Do not deactivate objects during application reload/restart
  lib/base/application.cpp
  lib/base/application.hpp
  lib/db_ido/dbconnection.cpp
Labels: DB IDO, bug

#7155 use current frame scope for permission filter function calls
  lib/remote/filterutility.cpp
Labels: API, bug, build-fix

#7158 CLI: Fix updates for NodeName/ZoneName constants
  lib/cli/nodesetupcommand.cpp
  lib/cli/nodewizardcommand.cpp
Labels: CLI, bug

#7162 CLI: Return non-zero on unknown sub commands
  icinga-app/icinga.cpp
  lib/cli/clicommand.cpp
Labels: CLI, bug

#7163 DB IDO: Use cached reachable state
  lib/db_ido/hostdbobject.cpp
  lib/db_ido/servicedbobject.cpp
Labels: DB IDO, bug

#7164 Improve validation for times.{begin,end} in notification objects
  lib/icinga/notification.cpp
  lib/icinga/notification.hpp
Labels: Configuration, bug

#7166 cmake: Update MySQL autodetection to support MariaDB
  third-party/cmake/FindMySQL.cmake
Labels: code-quality, low-priority

#7168 Fix deadlock in API config packages
  lib/remote/configobjectutility.cpp
  lib/remote/configpackageshandler.cpp
  lib/remote/configpackageutility.cpp
  lib/remote/configpackageutility.hpp
  lib/remote/configstageshandler.cpp
Labels: area/api, build-fix

#7169 Docs: Improve distributed, features HA, reachability chapters
  doc/03-monitoring-basics.md
  doc/06-distributed-monitoring.md
  doc/13-addons.md
  doc/14-features.md
Labels: Documentation

#7171 Docs: Add Master-Master-Replication as option for mysql
  doc/06-distributed-monitoring.md
Labels: area/documentation

#7165 Doc: Improve the development chapter
  doc/21-development.md
Labels: area/documentation

#7175 Docs: Use jo to format JSON body for API actions, esp. unix timestamps
  doc/12-icinga2-api.md
Labels: area/documentation

#7172 Account for OpenSSL library evolution
  lib/base/tlsstream.cpp
  lib/base/tlsutility.cpp
  lib/remote/pkiutility.cpp
Labels: area/api, area/distributed, core/quality

#7154 Lock all kind of Objects during serialization
  lib/base/serializer.cpp
  lib/icinga/timeperiod.cpp
Labels: bug

#7178 API: Automatically repair broken _api package
  doc/15-troubleshooting.md
  doc/16-upgrading-icinga-2.md
  lib/cli/daemoncommand.cpp
  lib/remote/apilistener.cpp
  lib/remote/configobjectutility.cpp
  lib/remote/configobjectutility.hpp
  lib/remote/configpackageutility.cpp
Labels: area/api, bug

#7179 Add new -r parameter for esxi_hardware command
  doc/10-icinga-template-library.md
  itl/plugins-contrib.d/virtualization.conf
Labels: area/itl, enhancement

#7026 CLI: 'ca list' lists pending CSRs by default, add '--all' parameter
  doc/06-distributed-monitoring.md
  doc/11-cli-commands.md
  doc/16-upgrading-icinga-2.md
  lib/cli/calistcommand.cpp
Labels: area/cli, enhancement

#7181 Add check command for x509's host check
  doc/10-icinga-template-library.md
  itl/plugins-contrib.d/icingacli.conf
Labels: area/itl, enhancement

#7185 Fix wrong facility in GelfWriter log message
  lib/perfdata/gelfwriter.cpp
Labels: area/log, bug, core/build-fix

#7189 Use --description instead of -d for check_service.exe
  itl/command-plugins-windows.conf
Labels: area/itl, core/quality

#7190 Disable program option guessing in check_service
  plugins/check_service.cpp
Labels: area/windows, bug

#7143 Use I/O engine in debug console CLI command
  lib/cli/consolecommand.cpp
  lib/cli/consolecommand.hpp
Labels: area/cli, enhancement

#7142 check_nscp_api: Rewrite using Boost ASIO and Beast
  plugins/check_nscp_api.cpp
Labels: area/windows, enhancement

#7199 Docs: Add styleguide with development details
  CONTRIBUTING.md
  doc/12-icinga2-api.md
  doc/21-development.md
Labels: area/documentation, enhancement

#7156 Implement sleep CheckCommand
  doc/10-icinga-template-library.md
  itl/command-icinga.conf
  lib/methods/CMakeLists.txt
  lib/methods/methods-itl.conf
  lib/methods/sleepchecktask.cpp
  lib/methods/sleepchecktask.hpp
Labels: area/itl, enhancement

#6813 Implement TLS support for the GelfWriter feature
  doc/09-object-types.md
  lib/perfdata/gelfwriter.cpp
  lib/perfdata/gelfwriter.hpp
  lib/perfdata/gelfwriter.ti
Labels: area/graylog, enhancement

#7201 Unify copyright headers
  lib/base/io-engine.cpp
  lib/base/io-engine.hpp
  lib/base/lazy-init.hpp
  lib/perfdata/elasticsearchwriter.ti
Labels: core/quality

#7200 Docs: Replace 'training whitespaces' with 'trailing whitespaces'
  doc/21-development.md
Labels: area/documentation

#7205 CLI: Remove broken troubleshoot command
  doc/11-cli-commands.md
  doc/16-upgrading-icinga-2.md
  doc/icinga2.8
  lib/cli/CMakeLists.txt
  lib/cli/troubleshootcommand.cpp
  lib/cli/troubleshootcommand.hpp
Labels: area/cli, core/quality

#7196 Cleanup old code (HTTP, Cluster)
  lib/base/CMakeLists.txt
  lib/base/networkstream.hpp
  lib/base/socketevents-epoll.cpp
  lib/base/socketevents-poll.cpp
  lib/base/socketevents.cpp
  lib/base/socketevents.hpp
  lib/base/tcpsocket.hpp
  lib/base/tlsstream.cpp
  lib/base/tlsstream.hpp
  lib/base/tlsutility.cpp
  lib/base/tlsutility.hpp
  lib/base/unixsocket.hpp
  lib/cli/consolecommand.cpp
  lib/cli/daemoncommand.cpp
  lib/compat/statusdatawriter.cpp
  lib/db_ido_mysql/idomysqlconnection.cpp
  lib/db_ido_pgsql/idopgsqlconnection.cpp
  lib/livestatus/commentstable.cpp
  lib/livestatus/contactstable.cpp
  lib/livestatus/downtimestable.cpp
  lib/livestatus/endpointstable.cpp
  lib/livestatus/hoststable.cpp
  lib/livestatus/livestatuslogutility.cpp
  lib/livestatus/logtable.cpp
  lib/livestatus/servicestable.cpp
  lib/livestatus/statehisttable.cpp
  lib/livestatus/table.cpp
  lib/perfdata/elasticsearchwriter.cpp
  lib/perfdata/graphitewriter.cpp
  lib/perfdata/graphitewriter.hpp
  lib/perfdata/influxdbwriter.cpp
  lib/perfdata/opentsdbwriter.cpp
  lib/perfdata/opentsdbwriter.hpp
  lib/perfdata/opentsdbwriter.ti
  lib/remote/CMakeLists.txt
  lib/remote/apiclient.cpp
  lib/remote/apiclient.hpp
  lib/remote/httpchunkedencoding.cpp
  lib/remote/httpchunkedencoding.hpp
  lib/remote/httpclientconnection.cpp
  lib/remote/httpclientconnection.hpp
  lib/remote/httphandler.hpp
  lib/remote/httprequest.cpp
  lib/remote/httprequest.hpp
  lib/remote/httpresponse.cpp
  lib/remote/httpresponse.hpp
  lib/remote/httputility.cpp
  lib/remote/httputility.hpp
  lib/remote/jsonrpc.cpp
  lib/remote/jsonrpc.hpp
Labels: core/quality

#7210 Quality: Replace deprecated get_io_service() with get_executor().context() for Boost ASIO
  lib/base/tcpsocket.hpp
  lib/remote/apilistener.cpp
  lib/remote/httpserverconnection.cpp
  lib/remote/jsonrpcconnection-heartbeat.cpp
  lib/remote/jsonrpcconnection.cpp
Labels: core/build-fix, core/quality
