Repository Icinga/icinga2, pull requests merged in 2019-12, with the labels that each got.

#7668 Fix TLS context copies in ApiListener
  lib/remote/apilistener.cpp
Labels: area/api, core/quality

#7674 IcingaDB: Remove unused checksums
  lib/icingadb/icingadb-objects.cpp
Labels: area/icingadb

#7665 Docs: clarify CRITICAL vs. UNKNOWN
  doc/03-monitoring-basics.md
Labels: area/documentation

#7664 Docs: explicitly explain how to disable freshness checks
  doc/08-advanced-topics.md
Labels: area/documentation

#7682 Documentation: Some small typo fixes
  doc/15-troubleshooting.md
Labels: area/documentation

#7681 Improve error message for POST queries
  lib/remote/modifyobjecthandler.cpp
Labels: area/api, enhancement

#7417 DSL: Add support for Lambda Closures ()use(x)=>x and ()use(x)=>{return x}
  doc/17-language-reference.md
  lib/config/config_parser.yy
Labels: area/configuration, enhancement

#7540 Add file age check for Windows command definition
  doc/10-icinga-template-library.md
  itl/plugins-contrib.d/windows.conf
Labels: area/itl, area/windows

#7669 IcingaDB: Add notification recipients
  lib/icingadb/icingadb-objects.cpp
Labels: area/icingadb, enhancement

#7694 IcingaDB: Add timestamp to stats stream
  lib/icingadb/icingadb.cpp
Labels: area/icingadb

#7696 Metrics: Always send '0' as value for thresholds
  lib/perfdata/elasticsearchwriter.cpp
  lib/perfdata/gelfwriter.cpp
  lib/perfdata/graphitewriter.cpp
  lib/perfdata/influxdbwriter.cpp
  lib/perfdata/opentsdbwriter.cpp
Labels: area/metrics, bug

#7702 IcingaDB history: Add cancelled_by & removed_by to downtime & comment history
  lib/icingadb/icingadb-objects.cpp
Labels: area/icingadb

#7701 Fix bash line continuation in mail-host-notification.sh
  etc/icinga2/scripts/mail-host-notification.sh
Labels: area/setup, bug

#7686 Fix open connections when agent waits for CA approval
  lib/remote/jsonrpcconnection-pki.cpp
Labels: area/distributed, bug

#7706 Fix notification scripts to stay compatible with Dash
  etc/icinga2/scripts/mail-host-notification.sh
  etc/icinga2/scripts/mail-service-notification.sh
Labels: area/setup, bug

#7708 IcingaDB: update icinga:nextupdate:* on Checkable#next_check changes
  lib/icingadb/icingadb-objects.cpp
  lib/icingadb/icingadb.hpp
Labels: area/icingadb

#7712 JSON: Update to nlohmann/json 3.7.3
  third-party/nlohmann_json/json.hpp
Labels: core/quality
