Repository Icinga/icinga2, pull requests merged in 2019-10, with the labels that each got.

#7564 doc typo: path to error.log
  doc/14-features.md
Labels: area/documentation

#7544 Avoid loading the authoritative marker for syncs at all cost
  lib/remote/apilistener-filesync.cpp
Labels: bug

#7552 Avoid syncing .authorititative marker received from < 2.11 parent nodes
  lib/remote/apilistener-filesync.cpp
Labels: area/distributed, bug

#7578 Align the docs with GitHub details on Zone Inception
  doc/15-troubleshooting.md
  doc/16-upgrading-icinga-2.md
Labels: area/documentation

#7457 Config parser: save some memory allocations
  lib/config/config_parser.yy
Labels: core/quality

#7360 Replace some classic shared pointers with intrusive ones
  lib/base/CMakeLists.txt
  lib/base/netstring.cpp
  lib/base/netstring.hpp
  lib/base/shared.hpp
  lib/base/tlsstream.hpp
  lib/base/tlsutility.cpp
  lib/base/tlsutility.hpp
  lib/cli/consolecommand.cpp
  lib/cli/consolecommand.hpp
  lib/perfdata/elasticsearchwriter.cpp
  lib/perfdata/gelfwriter.cpp
  lib/perfdata/graphitewriter.cpp
  lib/perfdata/graphitewriter.hpp
  lib/perfdata/influxdbwriter.cpp
  lib/perfdata/opentsdbwriter.cpp
  lib/perfdata/opentsdbwriter.hpp
  lib/remote/apilistener.cpp
  lib/remote/apilistener.hpp
  lib/remote/httpserverconnection.cpp
  lib/remote/httpserverconnection.hpp
  lib/remote/jsonrpc.cpp
  lib/remote/jsonrpc.hpp
  lib/remote/jsonrpcconnection.cpp
  lib/remote/jsonrpcconnection.hpp
  lib/remote/pkiutility.cpp
  plugins/check_nscp_api.cpp
Labels: core/quality

#7364 Replace classic shared pointers to Expression and NamespaceValue with intrusive ones
  lib/base/CMakeLists.txt
  lib/base/function.hpp
  lib/base/json-script.cpp
  lib/base/math-script.cpp
  lib/base/namespace.cpp
  lib/base/namespace.hpp
  lib/base/scriptframe.cpp
  lib/base/scriptglobal.cpp
  lib/base/shared-object.hpp
  lib/config/applyrule.cpp
  lib/config/applyrule.hpp
  lib/config/config_parser.yy
  lib/config/configcompiler.cpp
  lib/config/configcompiler.hpp
  lib/config/configitem.cpp
  lib/config/configitem.hpp
  lib/config/configitembuilder.cpp
  lib/config/configitembuilder.hpp
  lib/config/expression.cpp
  lib/config/expression.hpp
  lib/config/vmops.hpp
  lib/icinga/icingaapplication.cpp
  lib/remote/eventqueue.cpp
  lib/remote/eventqueue.hpp
Labels: core/quality

#7583 Minor doc fix
  doc/06-distributed-monitoring.md
Labels: area/documentation

#7541 Config lexer: complain on EOF in heredocs, i.e. {{{abc<EOF>
  lib/config/config_lexer.ll
Labels: area/configuration, bug

#7584 Cluster Config Sync: Check the timestamp prior to config file checksums for changes
  lib/remote/apilistener-filesync.cpp
Labels: area/distributed, bug

#7458 Config parser: introduce optional_newlines
  lib/config/config_parser.yy
Labels: area/configuration, core/quality

#7588 Docs: Add upgrading notes for 2.11.x bugfix releases
  doc/16-upgrading-icinga-2.md
Labels: area/documentation

#7589 Clarify the installation of EPEL repository on CentOS vs RHEL
  doc/02-installation.md
Labels: area/documentation

#7591 Docs: Add the link from object type joins to URL endpoints
  doc/12-icinga2-api.md
Labels: area/documentation

#7593 I like to move it, move it
  lib/config/config_parser.yy
Labels: core/quality
