Repository Icinga/icinga2, pull requests merged in 2019-06, with the labels that each got.

#7214 Docs: Fix typo
  doc/18-library-reference.md
Labels: area/documentation

#7204 Allow setting the SNMP version for check_iftraffic.pl
  doc/10-icinga-template-library.md
  itl/plugins-contrib.d/network-components.conf
Labels: area/itl

#7216 Provide the snmpv3_context option
  doc/10-icinga-template-library.md
  itl/command-plugins.conf
Labels: area/itl

#7211 Require TLS 1.2 for Cluster & REST API
  doc/09-object-types.md
  doc/16-upgrading-icinga-2.md
  lib/base/tlsutility.cpp
  lib/remote/apilistener.cpp
  lib/remote/apilistener.ti
Labels: area/api, area/distributed

#7213 Docs: Add note about not to use director-global for own configuration
  doc/06-distributed-monitoring.md
Labels: area/documentation

#7224 Docs: Mark include_zones as internal consumed functionality
  doc/17-language-reference.md
Labels: area/documentation

#7219 API: Harden default cipher list
  doc/09-object-types.md
  doc/16-upgrading-icinga-2.md
  lib/remote/apilistener.ti
Labels: area/api, area/distributed, enhancement

#7209 Close server connections and shutdown coroutines immediately on disconnect
  lib/remote/httpserverconnection.cpp
  lib/remote/httpserverconnection.hpp
  lib/remote/jsonrpcconnection-heartbeat.cpp
  lib/remote/jsonrpcconnection.cpp
  lib/remote/jsonrpcconnection.hpp
Labels: area/api, area/distributed

#7220 Improve error handling with network connections (Boost ASIO)
  lib/remote/apilistener.cpp
  lib/remote/httpserverconnection.cpp
Labels: area/api, area/distributed

#7229 Docs: Improve the service monitoring chapter (plugin API, new plugin, integration, etc.)
  doc/05-service-monitoring.md
Labels: area/documentation, enhancement

#7184 Strip '\r' in notification messages to avoid 'Content-Type: application/octet-stream'
  etc/icinga2/scripts/mail-host-notification.sh
  etc/icinga2/scripts/mail-service-notification.sh
Labels: area/notifications, area/setup

#7231 Docs: Update technical concepts for TLS Network IO and Boost Asio, Beast and Coroutines
  doc/19-technical-concepts.md
Labels: area/distributed, area/documentation, enhancement

#7230 Avoid concurrent cluster config sync transactions
  lib/remote/apilistener-filesync.cpp
  lib/remote/apilistener.hpp
Labels: area/distributed, bug

#7232 Doc: Add missing closing code tag
  doc/05-service-monitoring.md
Labels: area/documentation, core/build-fix

#7233 Docs: Add new runtime checkable attributes and explain severity in tech concepts
  doc/09-object-types.md
  doc/19-technical-concepts.md
Labels: area/documentation

#7208 Actually wait for running checks
  lib/checker/checkercomponent.cpp
Labels: area/checks, ref/NC

#7218 API Actions: Add downtime for all host services (child objects)
  doc/12-icinga2-api.md
  doc/16-upgrading-icinga-2.md
  lib/icinga/apiactions.cpp
Labels: area/api, enhancement

#7118 Systemd: don't kill any running check plugins
  etc/initsystem/icinga2.service.cmake
Labels: area/checks, ref/NC

#7183 Fix System-V return codes according to LSB
  etc/initsystem/icinga2.init.d.cmake
Labels: area/setup

#7011 LegacyTimePeriod::ProcessTimeRangeRaw(): support ranges across midnight
  doc/08-advanced-topics.md
  lib/icinga/legacytimeperiod.cpp
  test/CMakeLists.txt
  test/icinga-legacytimeperiod.cpp
Labels: area/configuration, bug

#6500 Implemented `ca remove` cli command + documentation.
  doc/06-distributed-monitoring.md
  doc/11-cli-commands.md
  doc/16-upgrading-icinga-2.md
  lib/cli/CMakeLists.txt
  lib/cli/calistcommand.cpp
  lib/cli/caremovecommand.cpp
  lib/cli/caremovecommand.hpp
  lib/cli/carestorecommand.cpp
  lib/cli/carestorecommand.hpp
  lib/cli/casigncommand.cpp
  lib/remote/jsonrpcconnection-pki.cpp
  lib/remote/pkiutility.cpp
  lib/remote/pkiutility.hpp
Labels: area/cli, enhancement

#7238 Fix build errors with Boost v1.70
  lib/base/tcpsocket.hpp
  lib/remote/apilistener.cpp
  lib/remote/httpserverconnection.cpp
  lib/remote/httpserverconnection.hpp
  lib/remote/jsonrpcconnection.cpp
  lib/remote/jsonrpcconnection.hpp
Labels: core/build-fix

#7248 SSL Context: Explicitly load ECC ciphers on el7
  lib/base/tlsutility.cpp
Labels: bug, core/build-fix

#7192 Remove double whitespaces for notifications log message
  lib/icinga/checkable-check.cpp
  lib/icinga/notification.cpp
Labels: area/log, bug

#6727 Improve cluster config sync
  doc/16-upgrading-icinga-2.md
  doc/19-technical-concepts.md
  lib/cli/daemonutility.cpp
  lib/methods/icingachecktask.cpp
  lib/remote/CMakeLists.txt
  lib/remote/apilistener-filesync.cpp
  lib/remote/apilistener.cpp
  lib/remote/apilistener.hpp
  lib/remote/apilistener.ti
Labels: area/distributed, enhancement

#7252 Fix type in nanorc syntax file
  tools/syntax/nano/icinga2.nanorc
Labels: area/setup

#7251 Disable stack traces for WQ exceptions (used in config compiler)
  lib/base/workqueue.cpp
  lib/base/workqueue.hpp
Labels: area/configuration, area/log, bug

#7259 Fix Path to staged files
  lib/remote/apilistener-filesync.cpp
Labels: core/build-fix

#7262 Fix syntax (missing ")
  doc/16-upgrading-icinga-2.md
Labels: area/documentation, core/build-fix

#7266 Fix out-of-bounds crash with Array#remove
  lib/base/array.cpp
Labels: area/cli, area/configuration, bug

#7267 Add security issue URL to README/About in the docs
  README.md
  doc/01-about.md
Labels: area/documentation
