Repository Icinga/icinga2, pull requests merged in 2019-09, with the labels that each got.

#7467 Docs: Update Linux and Windows Dev instructions for 2.11
  doc/21-development.md
Labels: area/documentation

#7476 Always reset Boost beast buffer in HttpServerConnection#ProcessMessages
  lib/remote/httpserverconnection.cpp
Labels: area/api, core/quality

#7477 HttpServerConnection: Prefer error codes over Boost exceptions
  lib/remote/httpserverconnection.cpp
Labels: area/api, core/quality

#7479 Build: Add Powershell script for development config for building Windows debug packages
  tools/win32/configure-dev.ps1
Labels: area/setup, core/quality

#7481 Add summarized performance data to check_network
  plugins/check_network.cpp
Labels: area/windows, enhancement

#7483 JsonRpcConnection: Don't swallow exceptions in Boost.Coroutine
  lib/remote/httpserverconnection.cpp
  lib/remote/jsonrpcconnection.cpp
Labels: area/distributed, bug, core/build-fix

#7486 Rewrite error handling in HttpServerConnection#EnsureValidHeaders()
  lib/remote/httpserverconnection.cpp
Labels: area/distributed, bug, core/build-fix, core/quality

#7485 Avoid the Defer-Disconnect destructor pattern with Boost.Coroutines
  lib/remote/apilistener.cpp
  lib/remote/httpserverconnection.cpp
  lib/remote/jsonrpcconnection.cpp
Labels: area/distributed, bug, core/build-fix

#7487 API: Avoid I/O on shutdown
  lib/remote/httpserverconnection.cpp
  lib/remote/jsonrpcconnection.cpp
Labels: area/api, area/distributed, core/quality

#7490 Quality: Replace deprecated Boost IO service code
  lib/base/io-engine.cpp
  lib/base/io-engine.hpp
  lib/base/tcpsocket.hpp
  lib/base/tlsstream.hpp
  lib/cli/consolecommand.cpp
  lib/perfdata/elasticsearchwriter.cpp
  lib/perfdata/gelfwriter.cpp
  lib/perfdata/graphitewriter.cpp
  lib/perfdata/influxdbwriter.cpp
  lib/perfdata/opentsdbwriter.cpp
  lib/remote/apilistener.cpp
  lib/remote/eventqueue.cpp
  lib/remote/httpserverconnection.cpp
  lib/remote/httpserverconnection.hpp
  lib/remote/jsonrpcconnection.cpp
  lib/remote/jsonrpcconnection.hpp
  lib/remote/pkiutility.cpp
  plugins/check_nscp_api.cpp
Labels: core/quality

#7491 Introduce IoEngine::SpawnCoroutine wrapping asio::spawn and Boost exceptions
  lib/base/io-engine.hpp
  lib/remote/apilistener.cpp
  lib/remote/httpserverconnection.cpp
  lib/remote/jsonrpcconnection.cpp
Labels: area/api, area/distributed, bug, core/build-fix, core/quality

#7502 Docs: Update debugging instructions for 2.11
  doc/21-development.md
Labels: area/documentation

#7503 API: Add AES128-GCM-SHA256 compatible cipher for el6
  doc/09-object-types.md
  doc/16-upgrading-icinga-2.md
  lib/remote/apilistener.ti
Labels: area/api, core/build-fix

#7504 Docs: Update product URLs and missing bits
  README.md
  doc/01-about.md
  doc/02-installation.md
  doc/04-configuration.md
  doc/05-service-monitoring.md
  doc/06-distributed-monitoring.md
  doc/13-addons.md
  doc/14-features.md
  doc/23-migrating-from-icinga-1x.md
  doc/images/addons/icinga_certificate_monitoring.png
  doc/images/addons/icinga_reporting.png
  doc/images/configuration/icinga_web_local_server.png
  doc/images/installation/mariadb-centos7.png
  doc/images/installation/nano-syntax.png
  doc/images/installation/postgr-import-ido.png
  doc/images/installation/vim-syntax.png
  mkdocs.yml
Labels: area/documentation

#7507 CSR Auto-signing: Add debug logging for skipped signing
  lib/remote/jsonrpcconnection-pki.cpp
Labels: area/log, enhancement

#7518 Fix spelling error
  doc/15-troubleshooting.md
Labels: area/documentation

#7526 Docs: Add upgrading/troubleshooting details for repos, config sync, agents
  doc/15-troubleshooting.md
  doc/16-upgrading-icinga-2.md
Labels: area/documentation

#7527 Improve error message/docs for command endpoints requiring a zone
  etc/icinga2/zones.d/README
  lib/icinga/checkable.cpp
Labels: area/configuration, area/documentation

#7534 Introduce Checkable#next_update
  doc/09-object-types.md
  lib/icinga/checkable.cpp
  lib/icinga/checkable.hpp
  lib/icinga/checkable.ti
Labels: enhancement

#7529 WarnOnImplicitlySetGlobalVar(): warn only on sins inside actual DSL code
  lib/config/expression.cpp
Labels: area/api, area/configuration

#7538 Dependency#OnAllConfigLoaded(): don't link *this with the child if *this is going to be dropped
  lib/icinga/dependency.cpp
Labels: area/configuration
