Repository Icinga/icinga2, pull requests merged in 2019-08, with the labels that each got.

#7381 Refine the term 'TLS' instead of 'SSL'
  doc/08-advanced-topics.md
  doc/12-icinga2-api.md
  doc/14-features.md
  doc/15-troubleshooting.md
  doc/19-technical-concepts.md
  doc/21-development.md
  doc/23-migrating-from-icinga-1x.md
Labels: area/documentation

#7383 Add missing options to 'nwc_health' ITL CheckCommand
  doc/10-icinga-template-library.md
  itl/plugins-contrib.d/network-components.conf
Labels: area/itl, enhancement

#7390 Docs: Syncing binaries with the config sync are not supported
  doc/06-distributed-monitoring.md
  doc/16-upgrading-icinga-2.md
Labels: area/documentation

#7392 Docs: Enhance Troubleshooting with TLS handshake, CSR signing, checks, notifications, cluster sync
  doc/15-troubleshooting.md
Labels: area/documentation, enhancement

#7389 Fix name of 'timeperiods' livestatus table in doc
  doc/24-appendix.md
Labels: area/documentation

#7396 DB IDO: Fix upgrade script for 2.11.0 (drop index only if existing)
  doc/16-upgrading-icinga-2.md
  lib/db_ido_mysql/schema/upgrade/2.11.0.sql
Labels: area/db-ido, core/build-fix

#7391 Cluster sync: Only sync valid UTF8 content (text config, no binaries)
  doc/16-upgrading-icinga-2.md
  lib/remote/apilistener-filesync.cpp
Labels: area/distributed

#7399 Improve logging for downtime/ack events (add, remove, expire)
  lib/icinga/checkable.cpp
  lib/icinga/downtime.cpp
  lib/remote/configobjectutility.cpp
Labels: area/log, enhancement

#7400 Fix missing stats for current_concurrent_checks via REST API
  lib/icinga/cib.cpp
Labels: area/api, bug

#7397 icinga2 daemon --close-stdio: keep console log open during first config validation
  lib/cli/daemoncommand.cpp
Labels: area/log

#7403 Enhance Agent best practices throughout the documentation
  doc/03-monitoring-basics.md
  doc/07-agent-based-monitoring.md
  doc/08-advanced-topics.md
  doc/13-addons.md
Labels: area/documentation

#7406 Docs: Add a note to icinga check about failed reload detection
  doc/10-icinga-template-library.md
Labels: area/documentation

#7409 CMake: If target arch cannot be detected, don't throw an error
  CMakeLists.txt
Labels: area/setup, core/build-fix

#7418 Fix minimum version parsing in the 'icinga' check
  lib/base/utility.cpp
  lib/base/utility.hpp
  lib/methods/icingachecktask.cpp
  test/CMakeLists.txt
  test/base-utility.cpp
Labels: area/checks, bug

#7419 Fix object create/delete config object cluster loop (missing message origin)
  lib/base/configobject.cpp
  lib/base/configobject.hpp
  lib/config/configitem.cpp
  lib/config/configitem.hpp
  lib/remote/apilistener-configsync.cpp
  lib/remote/configobjectutility.cpp
  lib/remote/configobjectutility.hpp
Labels: area/distributed, bug

#7420 Docs: Add cluster message routing details
  doc/19-technical-concepts.md
Labels: area/documentation, enhancement

#7423 Fix and improve logging for runtime object sync
  lib/remote/apilistener-configsync.cpp
  lib/remote/configobjectutility.cpp
  lib/remote/jsonrpcconnection.cpp
Labels: area/distributed, area/log, bug

#7421 Expose metric current_pending_callbacks
  lib/base/threadpool.cpp
  lib/base/threadpool.hpp
  lib/icinga/cib.cpp
  lib/methods/icingachecktask.cpp
Labels: area/metrics, enhancement

#7422 Correct current_concurrent_checks to actually running checks
  lib/icinga/checkable-check.cpp
  lib/icinga/checkable.hpp
  lib/icinga/cib.cpp
  lib/methods/icingachecktask.cpp
  lib/methods/pluginchecktask.cpp
Labels: bug

#7428 ITL: Add sar-perf
  doc/08-advanced-topics.md
  doc/10-icinga-template-library.md
  itl/plugins-contrib.d/operating-system.conf
Labels: area/itl

#7437 Add check_uptime to ITL
  doc/10-icinga-template-library.md
  itl/command-plugins.conf
Labels: area/itl

#7435 CMake: Fix LTO flags for shared linking
  CMakeLists.txt
Labels: area/setup

#7434 CMake: Fix CXX flags for AIX
  CMakeLists.txt
Labels: area/setup

#7447 check_nscp_api: read HTTP response via Boost.Beast
  plugins/check_nscp_api.cpp
Labels: area/windows, core/build-fix

#7346 DaemonCommand#Run(): set code page to UTF-8
  lib/cli/daemoncommand.cpp
Labels: area/runtime

#7449 DSL: warn on x=y if x is a global variable
  itl/command-nscp-local.conf
  lib/config/expression.cpp
Labels: area/configuration

#7450 Windows binary: Also update the exe icon
  icinga-app/icinga.ico
Labels: area/windows, core/build-fix

#7445 JsonRpcConnection#Disconnect(): unregister the connection ASAP
  lib/remote/jsonrpcconnection.cpp
Labels: area/distributed, bug, core/build-fix

#7451 Update docs: Fix online URL, cipher list
  doc/16-upgrading-icinga-2.md
  lib/db_ido_mysql/idomysqlconnection.cpp
  lib/db_ido_pgsql/idopgsqlconnection.cpp
  lib/remote/infohandler.cpp
Labels: area/documentation, core/quality

#7356 InfluxdbWriter: clone less
  lib/perfdata/influxdbwriter.cpp
Labels: area/influxdb, core/quality

#7459 Metrics: Expose problem/handled counts for hosts/services
  lib/icinga/cib.cpp
  lib/icinga/cib.hpp
  lib/icinga/icingaapplication.cpp
  lib/methods/icingachecktask.cpp
Labels: area/metrics, core/build-fix, enhancement

#7463 Docs: Prefer the Powershell commands on Windows
  doc/06-distributed-monitoring.md
  doc/15-troubleshooting.md
  doc/images/distributed-monitoring/icinga2_windows_cmd_admin_net_start_stop.png
Labels: area/documentation

#7464 Docs: Update supported Windows agent versions
  doc/06-distributed-monitoring.md
Labels: area/documentation
