Repository Icinga/icinga2, pull requests merged in 2019-03, with the labels that each got.

#6995 Typo and link fix
  doc/08-advanced-topics.md
Labels: Documentation

#6991 PkiUtility::NewCa(): just warn if the CA files already exist
  lib/remote/pkiutility.cpp
Labels: CLI, bug

#6979 Doc: write systemd lower-case
  doc/02-getting-started.md
  doc/15-troubleshooting.md
  doc/16-upgrading-icinga-2.md
  doc/21-development.md
Labels: Documentation

#7001 Assignment operators doc: tell what the { } are for
  doc/17-language-reference.md
Labels: Documentation

#6977 Ignore failure of unit test base_utility/comparepasswords_issafe
  test/base-utility.cpp
Labels: Tests

#6999 Suppress or fix compiler warnings
  icinga-app/icinga.cpp
  lib/base/application.cpp
  lib/base/netstring.cpp
  lib/base/process.cpp
  lib/base/scriptframe.cpp
  lib/cli/consolecommand.cpp
  lib/cli/nodesetupcommand.cpp
  lib/icinga/legacytimeperiod.cpp
  lib/icinga/scheduleddowntime.cpp
  lib/remote/apilistener.cpp
  lib/remote/eventqueue.cpp
Labels: code-quality

#7014 Utility::ValidateUTF8(): use UTF8-CPP
  CMakeLists.txt
  cmake/FindUTF8CPP.cmake
  lib/base/utility.cpp
  test/CMakeLists.txt
  test/base-utility.cpp
  third-party/utf8cpp/.gitignore
  third-party/utf8cpp/CMakeLists.txt
  third-party/utf8cpp/LICENSE
  third-party/utf8cpp/README.md
  third-party/utf8cpp/samples/docsample.cpp
  third-party/utf8cpp/source/utf8.h
  third-party/utf8cpp/source/utf8/checked.h
  third-party/utf8cpp/source/utf8/core.h
  third-party/utf8cpp/source/utf8/unchecked.h
  third-party/utf8cpp/test_data/negative/utf8_invalid.txt
  third-party/utf8cpp/test_data/utf8samples/UTF-8-demo.txt
  third-party/utf8cpp/test_data/utf8samples/Unicode_transcriptions.html
  third-party/utf8cpp/test_data/utf8samples/quickbrown.txt
  third-party/utf8cpp/test_drivers/negative/negative.cpp
  third-party/utf8cpp/test_drivers/smoke_test/test.cpp
  third-party/utf8cpp/test_drivers/utf8reader/utf8reader.cpp
Labels: code-quality

#7025 Update .gitignore
  .gitignore
Labels: code-quality

#6978 Doc: SLES 11 requires a newer boost version, too
  doc/21-development.md
Labels: Documentation

#6990 InfluxdbWriter: don't leak sockets
  lib/base/defer.hpp
  lib/perfdata/influxdbwriter.cpp
Labels: InfluxDB, bug

#7020 ElasticsearchWriter: don't leak sockets
  lib/perfdata/elasticsearchwriter.cpp
Labels: Elasticsearch, bug

#7019 Replace YAJL with nlohmann::json
  .travis.yml
  CMakeLists.txt
  cmake/FindJSON.cmake
  cmake/FindYAJL.cmake
  doc/16-upgrading-icinga-2.md
  doc/21-development.md
  lib/base/json.cpp
  test/CMakeLists.txt
  test/base-json.cpp
  third-party/CMakeLists.txt
  third-party/nlohmann_json/LICENSE
  third-party/nlohmann_json/json.hpp
  third-party/yajl/.gitignore
  third-party/yajl/BUILDING
  third-party/yajl/BUILDING.win32
  third-party/yajl/CMakeLists.txt
  third-party/yajl/COPYING
  third-party/yajl/ChangeLog
  third-party/yajl/README
  third-party/yajl/TODO
  third-party/yajl/src/CMakeLists.txt
  third-party/yajl/src/api/yajl_common.h
  third-party/yajl/src/api/yajl_gen.h
  third-party/yajl/src/api/yajl_parse.h
  third-party/yajl/src/api/yajl_tree.h
  third-party/yajl/src/api/yajl_version.h.cmake
  third-party/yajl/src/yajl.c
  third-party/yajl/src/yajl_alloc.c
  third-party/yajl/src/yajl_alloc.h
  third-party/yajl/src/yajl_buf.c
  third-party/yajl/src/yajl_buf.h
  third-party/yajl/src/yajl_bytestack.h
  third-party/yajl/src/yajl_encode.c
  third-party/yajl/src/yajl_encode.h
  third-party/yajl/src/yajl_gen.c
  third-party/yajl/src/yajl_lex.c
  third-party/yajl/src/yajl_lex.h
  third-party/yajl/src/yajl_parser.c
  third-party/yajl/src/yajl_parser.h
  third-party/yajl/src/yajl_tree.c
  third-party/yajl/src/yajl_version.c
Labels: API, Cluster, code-quality

#7027 Elasticsearch: Improve error handling/logging
  lib/perfdata/elasticsearchwriter.cpp
Labels: Elasticsearch, Log, enhancement

#7030 SELinux: add unreserved_port_type attribute to icinga2_port_t
  tools/selinux/icinga2.te
Labels: Packages

#7028 Fix heading level in development chapter
  doc/21-development.md
Labels: Documentation

#7002 check_network -h: drop non-existent feature
  plugins/check_network.cpp
Labels: Plugins, Windows

#7032 Backport Defer class for 2.10
  lib/base/defer.hpp
Labels: code-quality

#7031 Improve logging for parsing metrics in features
  lib/perfdata/elasticsearchwriter.cpp
  lib/perfdata/elasticsearchwriter.hpp
  lib/perfdata/gelfwriter.cpp
  lib/perfdata/gelfwriter.hpp
  lib/perfdata/graphitewriter.cpp
  lib/perfdata/graphitewriter.hpp
  lib/perfdata/influxdbwriter.cpp
  lib/perfdata/influxdbwriter.hpp
  lib/perfdata/opentsdbwriter.cpp
  lib/perfdata/opentsdbwriter.hpp
Labels: Elasticsearch, Graphite, Graylog, InfluxDB, Log, Metrics, OpenTSDB, enhancement

#7033 Docs: Update supported package repos in Getting Started chapter
  doc/02-getting-started.md
Labels: Documentation

#7034 Update NSClient++ to 0.5.2.39
  CMakeLists.txt
Labels: Packages, Windows

#7035 Elasticsearch: Change Content-Type header to 'application/x-ndjson' for bulk streams
  doc/16-upgrading-icinga-2.md
  lib/perfdata/elasticsearchwriter.cpp
Labels: Elasticsearch, enhancement

#7037 Fix incorrect title in API docs
  doc/12-icinga2-api.md
Labels: Documentation

#7046 Document that `ca list` is not an inventory, add cleanup cycle
  doc/06-distributed-monitoring.md
Labels: Documentation

#7042 SELinux: add a boolean to allow execution of plugins via sudo
  doc/22-selinux.md
  tools/selinux/icinga2.te
Labels: Packages

#6998 Unify documentation code formatting
  doc/04-configuring-icinga-2.md
  doc/05-service-monitoring.md
  doc/06-distributed-monitoring.md
  doc/07-agent-based-monitoring.md
  doc/08-advanced-topics.md
  doc/09-object-types.md
  doc/10-icinga-template-library.md
  doc/12-icinga2-api.md
  doc/13-addons.md
  doc/14-features.md
  doc/15-troubleshooting.md
  doc/17-language-reference.md
  doc/18-library-reference.md
  doc/20-script-debugger.md
  doc/21-development.md
  doc/22-selinux.md
  doc/23-migrating-from-icinga-1x.md
Labels: Documentation

#7049 REST API Docs: Add Golang client code example
  doc/02-getting-started.md
  doc/12-icinga2-api.md
Labels: Documentation

#7047 Update issue templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: Documentation

#7051 InfluxDB/Elasticsearch: Flush only if there's data in the buffer
  lib/perfdata/elasticsearchwriter.cpp
  lib/perfdata/influxdbwriter.cpp
Labels: Elasticsearch, InfluxDB, bug

#7052 Disable feature HA by default (InfluxDB, Graphite, Gelf, Elasticsearch, OpenTSDB, Perfdata)
  doc/09-object-types.md
  doc/16-upgrading-icinga-2.md
  lib/perfdata/elasticsearchwriter.ti
  lib/perfdata/gelfwriter.ti
  lib/perfdata/graphitewriter.ti
  lib/perfdata/influxdbwriter.ti
  lib/perfdata/opentsdbwriter.ti
  lib/perfdata/perfdatawriter.ti
Labels: build-fix
