Repository Icinga/icinga2, pull requests merged in 2020-09, with the labels that each got.

#8224 Close connections w/o sucessful TLS handshakes during 10s
  lib/remote/apilistener.cpp
  lib/remote/apilistener.hpp
Labels: area/distributed, bug

#8220 GitHub actions: don't cancel not yet failed jobs on a failure
  .github/workflows/packages.yml
Labels: area/ci

#8225 Clear ApiListener#last_failed_zones_stage_validation on config::Update if config not changed
  lib/remote/apilistener-filesync.cpp
Labels: area/distributed

#8227 Ensure the daemon doesn't get killed by logrotate
  lib/cli/daemoncommand.cpp
Labels: area/log, bug, core/crash

#8226 Check !!downtime->GetCheckable() before downtime->GetCheckable()->GetName()
  lib/icinga/downtime.cpp
Labels: bug, core/crash, ref/NC

#8231 Buildfix
  lib/remote/apilistener-filesync.cpp
  lib/remote/apilistener.hpp
Labels: core/build-fix

#8230 Fix open connections when agent waits for CA approval
  lib/remote/jsonrpcconnection-pki.cpp
Labels: area/distributed, bug

#8228 Check !!downtime->GetCheckable() before downtime->GetCheckable()->GetName()
  lib/icinga/downtime.cpp
Labels: bug, core/crash, ref/NC

#8189 Clear ApiListener#last_failed_zones_stage_validation on config::Update if config not changed
  lib/remote/apilistener-filesync.cpp
  lib/remote/apilistener.hpp
Labels: area/distributed, bug

#8235 Fix Windows .exe version v2.12.0 -> 2.12.0
  icinga-app/icinga.rc
  icinga-version.h.cmake
Labels: area/setup, area/windows, bug

#8234 Fix Windows .exe version v2.12.0 -> 2.12.0
  icinga-app/icinga.rc
  icinga-version.h.cmake
Labels: area/setup, area/windows, bug

#8211 Application#RunEventLoop(): don't wait for the thread pool to stop on shutdown
  lib/base/application.cpp
Labels: core/crash

#8241 IDO: customvariables: fix duplicate entry error
  lib/db_ido/dbobject.cpp
Labels: area/db-ido, bug

#8174 Revert "MacroProcessor::ResolveArguments(): skip null argument values"
  lib/icinga/macroprocessor.cpp
Labels: bug

#8270 Improve IDO queue stats logging
  lib/base/workqueue.cpp
  lib/base/workqueue.hpp
  lib/db_ido/dbconnection.cpp
  lib/db_ido/dbconnection.hpp
  lib/db_ido_mysql/idomysqlconnection.cpp
  lib/db_ido_mysql/idomysqlconnection.hpp
  lib/db_ido_pgsql/idopgsqlconnection.cpp
  lib/db_ido_pgsql/idopgsqlconnection.hpp
Labels: area/db-ido, area/log, enhancement

#8276 Call Process::InitializeSpawnHelper() ASAP
  lib/cli/daemoncommand.cpp
Labels: area/checks, bug

#8271 Improve IDO queue stats logging
  lib/base/workqueue.cpp
  lib/base/workqueue.hpp
  lib/db_ido/dbconnection.cpp
  lib/db_ido/dbconnection.hpp
  lib/db_ido_mysql/idomysqlconnection.cpp
  lib/db_ido_mysql/idomysqlconnection.hpp
  lib/db_ido_pgsql/idopgsqlconnection.cpp
  lib/db_ido_pgsql/idopgsqlconnection.hpp
Labels: area/db-ido, area/log, enhancement
