Repository Icinga/icinga2, pull requests merged in 2020-06, with the labels that each got.

#7995 icinga2 pki save-cert: allow to specify --key and --cert
  lib/cli/pkisavecertcommand.cpp
Labels: area/cli, bug

#8024 GitHub actions: build Raspbian packages
  .github/workflows/packages.yml
Labels: core/quality, enhancement

#7944 Chocolatey: Prepare new build process
  CMakeLists.txt
  choco/CMakeLists.txt
  choco/chocolateyInstall.ps1.cmake
  choco/chocolateyInstall.ps1.template.cmake
  choco/icinga2.nuspec.cmake
  tools/win32/build-choco.ps1
Labels: area/setup

#8049 Chocolatey: Prepare new build process (2.11 backport)
  CMakeLists.txt
  choco/CMakeLists.txt
  choco/chocolateyInstall.ps1.cmake
  choco/chocolateyInstall.ps1.template.cmake
  choco/icinga2.nuspec.cmake
  tools/win32/build-choco.ps1
Labels: area/setup

#8046 prepare-dirs: combine mkdir and chmod
  etc/initsystem/prepare-dirs.cmake
Labels: ref/IP

#8045 prepare-dirs: combine mkdir and chmod
  etc/initsystem/prepare-dirs.cmake
Labels: ref/IP

#8015 StreamLogger#Flush(): lock self
  lib/base/streamlogger.cpp
Labels: area/log, bug

#8054 Ensure the custom function is not null in Array#{sort,map,reduce,filter,any,all}()
  lib/base/array-script.cpp
Labels: area/configuration, bug

#8048 Docs: Move Icinga DB installation down (until it's ready for production)
  doc/02-installation.md
Labels: area/documentation

#8053 Ensure the custom function is not null in Array#{sort,map,reduce,filter,any,all}()
  lib/base/array-script.cpp
Labels: area/configuration, bug

#8051 Deprecate Livestatus
  doc/09-object-types.md
  doc/14-features.md
Labels: area/documentation, area/livestatus

#8066 Docs: Add missing file prefix to link
  doc/06-distributed-monitoring.md
Labels: area/documentation, bug
