Repository Icinga/icinga2, pull requests merged in 2020-02, with the labels that each got.

#7817 ApiEvents: Fix AcknowledgementCleared code quality
  lib/icinga/apievents.cpp
Labels: core/quality

#7747 Don't send event::Heartbeat to unauthenticated peers
  lib/remote/jsonrpcconnection-heartbeat.cpp
Labels: area/distributed

#7811 Cluster config sync: Use a more friendly message when configs are equal and don't need a reload
  doc/15-troubleshooting.md
  lib/remote/apilistener-filesync.cpp
Labels: area/distributed, area/documentation, area/log

#7809 Close connections w/o sucessful TLS handshakes during 10s
  lib/remote/apilistener.cpp
  lib/remote/apilistener.hpp
Labels: area/distributed, bug

#7767 Ensure that log replay files are properly renamed on Windows
  lib/remote/apilistener.cpp
Labels: area/distributed, area/windows, bug

#7810 IoEngine#SpawnCoroutine(): don't copy parameter
  lib/base/io-engine.hpp
Labels: core/quality

#7788 Terminate windows check processes with UNKNOWN state on timeout
  lib/base/process.cpp
Labels: area/windows, bug

#7769 Make ConfigCompiler#m_LexBuffer a String
  lib/config/config_lexer.ll
  lib/config/configcompiler.hpp
Labels: core/quality

#7785 Change behaviour of multiple dependencies (all failed = unreachable)
  doc/16-upgrading-icinga-2.md
  lib/icinga/checkable-dependency.cpp
  lib/icinga/dependency.cpp
  lib/icinga/dependency.hpp
  test/CMakeLists.txt
  test/icinga-checkresult.cpp
  test/icinga-dependencies.cpp
Labels: area/distributed, area/runtime, core/quality

#7697 IcingaDB: Fix enumeral mismatch compiler warnings
  lib/icingadb/icingadb-objects.cpp
Labels: area/icingadb, core/quality

#7824 Doc: Fix wrong docker image for debian developemnt environment
  doc/21-development.md
Labels: area/documentation, bug

#7835 Improve experience with 'Node Setup for Agents/Satellite'
  doc/06-distributed-monitoring.md
  doc/16-upgrading-icinga-2.md
  lib/base/tlsutility.cpp
  lib/base/tlsutility.hpp
  lib/cli/nodesetupcommand.cpp
  lib/cli/pkisavecertcommand.cpp
Labels: area/cli, area/documentation, enhancement

#7838 Catch exception when trusted cert is not readable during node setup on agent/satellite
  lib/cli/nodesetupcommand.cpp
Labels: area/cli, bug

#7833 CLI: Add OpenSSL version to 'Build' section in --version
  lib/base/application.cpp
  lib/base/tlsutility.cpp
  lib/base/tlsutility.hpp
Labels: area/cli, enhancement

#7843 CLI: Add `pki verify` command for better TLS certificate troubleshooting
  doc/11-cli-commands.md
  doc/15-troubleshooting.md
  doc/16-upgrading-icinga-2.md
  lib/base/tlsutility.cpp
  lib/base/tlsutility.hpp
  lib/cli/CMakeLists.txt
  lib/cli/pkiverifycommand.cpp
  lib/cli/pkiverifycommand.hpp
  lib/remote/jsonrpcconnection-pki.cpp
  lib/remote/pkiutility.cpp
Labels: area/cli, enhancement

#7853 Windows setup wizard: Remove deprecated parameters for 'pki save-cert'
  agent/windows-setup-agent/SetupWizard.cs
Labels: area/windows, core/build-fix

#7860 Fix translation
  doc/22-selinux.md
Labels: area/documentation

#7867 Dev Docs: Update debugging instructions
  doc/21-development.md
Labels: area/documentation

#7858 SELinux: Let safe-reload run in icinga2_t
  .gitignore
  tools/selinux/icinga2.fc
  tools/selinux/icinga2.sh
  tools/selinux/icinga2.te
Labels: area/setup

#7866 Remove contrib/ directory
  contrib/GPLHeader
  contrib/README
  contrib/discover-api.py
  contrib/discover.py
  contrib/i2eval/Makefile
  contrib/i2eval/README
  contrib/i2eval/i2tcl.cpp
  contrib/i2eval/i2tcl.hpp
  contrib/i2eval/i2tcl.tcl
Labels: core/quality

#7859 Add new Projects to documentation
  doc/12-icinga2-api.md
Labels: area/documentation

#7861 Fix 'check_timeout' not being forwarded to agent command endpoints
  doc/19-technical-concepts.md
  lib/icinga/checkable-check.cpp
  lib/icinga/clusterevents-check.cpp
Labels: area/distributed, bug
