Repository Icinga/icinga2, pull requests merged in 2020-11, with the labels that each got.

#8109 ITL: Assignment of check_adress in check_http blocks check by hostname
  itl/command-plugins.conf
Labels: area/itl, bug

#8087 Display Logmessage if an permission error occurs
  lib/remote/httphandler.cpp
Labels: area/api, area/log, bug

#8108 API: Send Content-Type as api response header too
  lib/remote/httpserverconnection.cpp
Labels: area/api, bug

#8448 GitHub actions: build Ubuntu groovy
  .github/workflows/packages.yml
Labels: area/ci

#8445 GitHub actions: build Ubuntu groovy
  .github/workflows/packages.yml
Labels: area/ci

#8400 Docs: provide shorter and batch-ier instructions on how to setup a Windows dev env
  doc/21-development.md
  doc/win-dev.ps1
Labels: area/documentation, area/windows

#8459 API: Don't accept object updates for unknown global zone
  lib/remote/apilistener-configsync.cpp
Labels: area/api, area/distributed, bug, ref/NC

#8454 Include HTTP status codes in log
  lib/remote/httpserverconnection.cpp
Labels: area/api

#8399 ApiListener#NewClientHandlerInternal(): reject connections from already connected endpoints
  lib/remote/apilistener.cpp
Labels: area/distributed, enhancement

#8446 Add info about ongoing support for IDO
  doc/14-features.md
Labels: area/db-ido, area/documentation, enhancement

#8457 Log config object deletions to replay log
  lib/remote/apilistener-configsync.cpp
Labels: area/api, area/distributed, bug, ref/NC

#8460 Fix 'emoving' typo
  lib/remote/configobjectutility.cpp
Labels: core/quality

#8470 Log config object deletions to replay log
  lib/remote/apilistener-configsync.cpp
Labels: area/api, area/distributed, bug, ref/NC

#8455 Log config object deletions to replay log
  lib/remote/apilistener-configsync.cpp
Labels: area/api, area/distributed, bug, ref/NC

#7892 ITL: fix check_dns -q docs
  doc/10-icinga-template-library.md
Labels: area/documentation

#7915 etc/icinga2/scripts/*.sh: explicitly specify shell
  etc/icinga2/scripts/mail-host-notification.sh
  etc/icinga2/scripts/mail-service-notification.sh
Labels: bug

#7931 Livestatus: append app name to program_version
  lib/livestatus/statustable.cpp
Labels: area/livestatus, enhancement

#8195 JsonEncode(): suffix pretty JSON w/ \n
  lib/base/json.cpp
  test/base-json.cpp
Labels: area/api, enhancement

#8232 Fix Windows .exe version v2.12.0 -> 2.12.0
  icinga-app/icinga.rc
  icinga-version.h.cmake
Labels: area/setup, area/windows, bug

#8482 Close anonymous connections after 10 seconds
  lib/remote/jsonrpcconnection.cpp
Labels: area/distributed, bug

#8473 Fix cluster message routing for global zones
  lib/remote/apilistener.cpp
Labels: area/api, area/distributed, bug, ref/NC

#8475 Start ApiListener#SyncClient() in the thread pool
  lib/remote/apilistener.cpp
Labels: area/distributed, bug

#8483 Close anonymous connections after 10 seconds
  lib/remote/jsonrpcconnection.cpp
Labels: area/distributed, bug

#8486 Config sync: Only remove files, if timestamp changed
  lib/remote/apilistener-filesync.cpp
Labels: area/configuration, area/distributed, bug

#8487 Add #8486 to changelog
  CHANGELOG.md
Labels: area/documentation

#8476 Clarify difference between API actions and functions in their docstrings
  lib/remote/apiaction.hpp
  lib/remote/apifunction.hpp
Labels: core/quality

#8461 API: Don't accept object updates for unknown zone
  lib/remote/apilistener-configsync.cpp
Labels: area/api, area/distributed, bug, ref/NC

#8474 Fix cluster message routing for global zones
  lib/remote/apilistener.cpp
Labels: area/api, area/distributed, bug, ref/NC

#8467 Include HTTP status codes in log
  lib/remote/httpserverconnection.cpp
Labels: area/api

#8465 ApiListener#NewClientHandlerInternal(): reject connections from already connected endpoints
  lib/remote/apilistener.cpp
Labels: area/distributed, enhancement

#8495 Config sync: Only remove files, if timestamp changed
  lib/remote/apilistener-filesync.cpp
Labels: area/configuration, area/distributed, bug

#8496 Start ApiListener#SyncClient() in the thread pool
  lib/remote/apilistener.cpp
Labels: area/distributed, bug

#8450 API: Don't accept object updates for unknown global zone
  lib/remote/apilistener-configsync.cpp
Labels: area/api, area/distributed, bug, ref/NC

#8440 Fix cluster message routing for global zones
  lib/remote/apilistener.cpp
Labels: area/api, area/distributed, bug, ref/NC

#8466 ApiListener#NewClientHandlerInternal(): reject connections from already connected endpoints
  lib/remote/apilistener.cpp
Labels: area/distributed, enhancement

#8500 Config sync: Only remove files, if timestamp changed
  lib/remote/apilistener-filesync.cpp
Labels: area/configuration, area/distributed, bug

#8479 Close anonymous connections after 10 seconds
  lib/remote/jsonrpcconnection.cpp
Labels: area/distributed, bug

#8149 RELEASE.md: use perl, not sed
  RELEASE.md
Labels: area/documentation, bug

#8504 Start ApiListener#SyncClient() in the thread pool
  lib/remote/apilistener.cpp
Labels: area/distributed, bug

#8222 Fix typo
  doc/08-advanced-topics.md
Labels: area/documentation, bug

#8321 Allow to create API User w/ password
  lib/remote/apiuser.ti
Labels: area/api, bug

#8074 Add -S and -i parameters to the api queries
  doc/12-icinga2-api.md
Labels: area/documentation, enhancement

#8510 Improve config sync locking (support/2.11)
  lib/base/CMakeLists.txt
  lib/base/process.cpp
  lib/base/process.hpp
  lib/base/spinlock.cpp
  lib/base/spinlock.hpp
  lib/remote/apilistener-filesync.cpp
  lib/remote/apilistener.hpp
Labels: area/distributed, area/windows, bug, enhancement, ref/NC

#8511 Improve config sync locking (support/2.12)
  lib/base/CMakeLists.txt
  lib/base/process.cpp
  lib/base/process.hpp
  lib/base/spinlock.cpp
  lib/base/spinlock.hpp
  lib/remote/apilistener-filesync.cpp
  lib/remote/apilistener.hpp
Labels: area/distributed, area/windows, bug, enhancement, ref/NC

#8488 Improve config sync locking
  lib/base/CMakeLists.txt
  lib/base/process.cpp
  lib/base/process.hpp
  lib/base/spinlock.cpp
  lib/base/spinlock.hpp
  lib/remote/apilistener-filesync.cpp
  lib/remote/apilistener.hpp
Labels: area/distributed, core/quality
