Repository Icinga/icinga2, pull requests merged in 2020-12, with the labels that each got.

#8516 GitHub actions: drop SLES 12.4
  .github/workflows/packages.yml
Labels: area/ci

#8517 GitHub actions: drop SLES 15.0
  .github/workflows/packages.yml
Labels: area/ci

#8520 GitHub actions: drop CentOS 6
  .github/workflows/packages.yml
Labels: area/ci

#8518 GitHub actions: drop openSUSE 15.0
  .github/workflows/packages.yml
Labels: area/ci

#8519 GitHub actions: drop Fedora 29
  .github/workflows/packages.yml
Labels: area/ci

#8451 s/http/https/g
  CONTRIBUTING.md
  doc/03-monitoring-basics.md
  doc/05-service-monitoring.md
  doc/07-agent-based-monitoring.md
  doc/10-icinga-template-library.md
  doc/12-icinga2-api.md
  doc/14-features.md
  doc/16-upgrading-icinga-2.md
  doc/21-development.md
  doc/icinga2.8
  icinga-app/icinga.cpp
Labels: area/documentation, bug

#8040 Add API endpoint: /v1/actions/execute-command
  doc/12-icinga2-api.md
  doc/19-technical-concepts.md
  lib/base/atomic.hpp
  lib/base/configobject.ti
  lib/db_ido/idochecktask.cpp
  lib/icinga/apiactions.cpp
  lib/icinga/apiactions.hpp
  lib/icinga/checkable.cpp
  lib/icinga/checkable.hpp
  lib/icinga/checkable.ti
  lib/icinga/checkcommand.cpp
  lib/icinga/checkcommand.hpp
  lib/icinga/clusterevents-check.cpp
  lib/icinga/clusterevents.cpp
  lib/icinga/clusterevents.hpp
  lib/icinga/eventcommand.cpp
  lib/icinga/eventcommand.hpp
  lib/icinga/host.ti
  lib/icinga/hostgroup.ti
  lib/icinga/macroprocessor.cpp
  lib/icinga/macroresolver.hpp
  lib/icinga/notificationcommand.cpp
  lib/icinga/notificationcommand.hpp
  lib/icinga/service.ti
  lib/icinga/servicegroup.ti
  lib/icinga/timeperiod.ti
  lib/icinga/user.ti
  lib/icinga/usergroup.ti
  lib/methods/clusterchecktask.cpp
  lib/methods/clusterzonechecktask.cpp
  lib/methods/dummychecktask.cpp
  lib/methods/exceptionchecktask.cpp
  lib/methods/icingachecktask.cpp
  lib/methods/nullchecktask.cpp
  lib/methods/nulleventtask.cpp
  lib/methods/pluginchecktask.cpp
  lib/methods/plugineventtask.cpp
  lib/methods/pluginnotificationtask.cpp
  lib/methods/randomchecktask.cpp
  lib/methods/sleepchecktask.cpp
  lib/remote/actionshandler.cpp
  lib/remote/actionshandler.hpp
  lib/remote/apilistener.cpp
  lib/remote/apilistener.hpp
  lib/remote/endpoint.ti
  tools/mkclass/classcompiler.cpp
Labels: area/api, enhancement

#7905 mkclass: make .ti class members atomic if possible
  lib/base/atomic.hpp
  lib/base/configobject.ti
  lib/icinga/host.ti
  lib/icinga/hostgroup.ti
  lib/icinga/service.ti
  lib/icinga/servicegroup.ti
  lib/icinga/timeperiod.ti
  lib/icinga/user.ti
  lib/icinga/usergroup.ti
  tools/mkclass/classcompiler.cpp
Labels: core/quality

#8458 docs: Add section about usage of satellites
  doc/06-distributed-monitoring.md
Labels: area/documentation, enhancement

#8221 Document command for verifying the parent node's cert
  doc/06-distributed-monitoring.md
Labels: area/documentation

#8314 Add support Influxdb basic auth
  doc/09-object-types.md
  lib/perfdata/influxdbwriter.cpp
  lib/perfdata/influxdbwriter.ti
Labels: area/influxdb, enhancement

#8294 Sort doc/18-library-reference.md
  doc/18-library-reference.md
Labels: area/documentation, bug

#8035 /v1/actions/add-comment: add param expiry
  lib/icinga/apiactions.cpp
Labels: area/api, enhancement

#8534 List the actual CLI parameters in the node setup docs
  doc/06-distributed-monitoring.md
Labels: area/documentation, bug

#8535 Configuration.ApiBindHost: default to ::
  doc/17-language-reference.md
  lib/base/configuration.cpp
Labels: area/documentation, bug

#8301 Docs: enable syntax highlighting
  CONTRIBUTING.md
  RELEASE.md
  doc/02-installation.md
  doc/03-monitoring-basics.md
  doc/05-service-monitoring.md
  doc/06-distributed-monitoring.md
  doc/07-agent-based-monitoring.md
  doc/11-cli-commands.md
  doc/12-icinga2-api.md
  doc/13-addons.md
  doc/14-features.md
  doc/15-troubleshooting.md
  doc/16-upgrading-icinga-2.md
  doc/19-technical-concepts.md
  doc/20-script-debugger.md
  doc/21-development.md
  doc/22-selinux.md
Labels: area/documentation, bug

#8543 Use proper buffer size for OpenSSL error messages (support/2.11)
  lib/base/tlsutility.cpp
  lib/base/tlsutility.hpp
  lib/remote/pkiutility.cpp
Labels: bug

#8541 Use proper buffer size for OpenSSL error messages
  lib/base/tlsutility.cpp
  lib/base/tlsutility.hpp
  lib/remote/pkiutility.cpp
Labels: bug

#8521 GitHub actions: drop Fedora 30
  .github/workflows/packages.yml
Labels: area/ci

#8551 Also drop distributions on support/2.12
  .github/workflows/packages.yml
Labels: area/ci, enhancement

#8550 Fix runtime config updates not working for objects without zone
  lib/remote/apilistener-configsync.cpp
Labels: area/distributed, bug

#8436 On recovery: re-check children
  lib/icinga/checkable-check.cpp
  lib/icinga/checkable-notification.cpp
Labels: area/checks, area/notifications, bug, ref/NC

#8506 On recovery: re-check children
  lib/icinga/checkable-check.cpp
  lib/icinga/checkable-notification.cpp
Labels: area/checks, area/notifications, bug, ref/NC

#8556 Fix typos in API documentation
  doc/12-icinga2-api.md
Labels: area/documentation, bug

#8549 Fix runtime config updates not working for objects without zone
  lib/remote/apilistener-configsync.cpp
Labels: area/distributed, bug

#7871 PerfdataValue: add UoMs
  doc/05-service-monitoring.md
  lib/base/perfdatavalue.cpp
  test/icinga-perfdata.cpp
Labels: area/checks, enhancement

#8542 Use proper buffer size for OpenSSL error messages (support/2.12)
  lib/base/tlsutility.cpp
  lib/base/tlsutility.hpp
  lib/remote/pkiutility.cpp
Labels: bug

#8567 Build fix: Use correct shared pointer implementation
  lib/base/tlsutility.hpp
Labels: core/build-fix

#8560 On recovery: re-check children
  lib/icinga/checkable-check.cpp
  lib/icinga/checkable-notification.cpp
Labels: area/checks, area/notifications, bug, ref/NC

#8191 Define BOOST_ASIO_USE_TS_EXECUTOR_AS_DEFAULT
  CMakeLists.txt
Labels: bug

#8575 Support Boost 1.74 when setting HTTP headers
  lib/base/string.cpp
  lib/base/string.hpp
  lib/perfdata/elasticsearchwriter.cpp
  lib/perfdata/influxdbwriter.cpp
  lib/remote/configfileshandler.cpp
  lib/remote/httpserverconnection.cpp
  lib/remote/httputility.cpp
  lib/remote/infohandler.cpp
Labels: bug
