Repository Icinga/icinga2, pull requests merged in 2020-10, with the labels that each got.

#8299 Don't send reminder notifications before suppressed ones
  lib/notification/notificationcomponent.cpp
Labels: area/notifications, bug

#8291 IDO: Make sure to insert program status
  lib/db_ido/dbconnection.cpp
  lib/db_ido/dbconnection.hpp
  lib/db_ido_mysql/idomysqlconnection.hpp
  lib/db_ido_pgsql/idopgsqlconnection.hpp
Labels: area/db-ido, bug

#8303 Revert: Fix duplicate entry error
  lib/db_ido/dbobject.cpp
Labels: area/db-ido, bug, core/build-fix

#8308 Make ApiListener::m_ConfigSyncStageLock a SpinLock
  lib/base/CMakeLists.txt
  lib/base/spinlock.cpp
  lib/base/spinlock.hpp
  lib/remote/apilistener-filesync.cpp
  lib/remote/apilistener.hpp
Labels: area/distributed, bug, core/crash

#8325 Improve new IDO logging
  lib/db_ido/dbconnection.cpp
  lib/db_ido/dbconnection.hpp
Labels: area/db-ido, area/log, core/quality

#8305 Do not upsert customvar status on heavy config update
  lib/db_ido/dbobject.cpp
Labels: area/db-ido, core/quality

#8298 IDO MySQL: actually COMMIT after 25000 async queries
  lib/db_ido_mysql/idomysqlconnection.cpp
  lib/db_ido_mysql/idomysqlconnection.hpp
Labels: area/db-ido, bug

#8300 Don't send reminder notifications before suppressed ones
  lib/notification/notificationcomponent.cpp
Labels: area/notifications, bug

#8292 Add timeout for boost::asio::ssl::stream#async_shutdown()
  lib/base/io-engine.cpp
  lib/base/io-engine.hpp
  lib/remote/jsonrpcconnection.cpp
Labels: area/distributed, bug

#8337 Catch exceptions in the thread running HandleConfigUpdate
  lib/remote/apilistener-filesync.cpp
Labels: area/distributed, core/crash, ref/NC

#8316 *DbObject#CalculateConfigHash(): sort groups to be hashed
  lib/db_ido/hostdbobject.cpp
  lib/db_ido/servicedbobject.cpp
  lib/db_ido/userdbobject.cpp
Labels: area/db-ido, bug

#8240 RELEASE.md: remove unneccessary "Authors" section
  RELEASE.md
Labels: area/documentation

#8342 Buildfix
  lib/base/CMakeLists.txt
  lib/base/shared-object.hpp
Labels: core/build-fix

#8343 RELEASE.md: fix packaging repo URLs
  RELEASE.md
Labels: area/documentation, bug

#8346 RELEASE.md: Add instructions how to prepare releases for Windows
  RELEASE.md
Labels: area/documentation, bug

#8327 Do not upsert customvar status on heavy config update
  lib/db_ido/dbobject.cpp
Labels: area/db-ido, core/quality

#8328 Improve new IDO logging
  lib/db_ido/dbconnection.cpp
  lib/db_ido/dbconnection.hpp
Labels: area/db-ido, area/log, core/quality

#8330 IDO: Make sure to insert program status
  lib/db_ido/dbconnection.cpp
  lib/db_ido/dbconnection.hpp
  lib/db_ido_mysql/idomysqlconnection.hpp
  lib/db_ido_pgsql/idopgsqlconnection.hpp
Labels: area/db-ido, bug

#8348 Make ApiListener::m_ConfigSyncStageLock a SpinLock
  lib/base/CMakeLists.txt
  lib/base/spinlock.cpp
  lib/base/spinlock.hpp
  lib/remote/apilistener-filesync.cpp
  lib/remote/apilistener.hpp
Labels: area/distributed, bug, core/crash

#8345 Catch exceptions in the thread running HandleConfigUpdate
  lib/remote/apilistener-filesync.cpp
Labels: area/distributed, core/crash

#8320 *DbObject#CalculateConfigHash(): sort groups to be hashed
  lib/db_ido/hostdbobject.cpp
  lib/db_ido/servicedbobject.cpp
  lib/db_ido/userdbobject.cpp
Labels: area/db-ido, bug

#8353 GitHub actions: build also support/*
  .github/workflows/docker.yml
  .github/workflows/packages.yml
Labels: area/ci

#8349 IDO MySQL: actually COMMIT after 25000 async queries
  lib/db_ido_mysql/idomysqlconnection.cpp
  lib/db_ido_mysql/idomysqlconnection.hpp
Labels: area/db-ido, bug

#8358 RELEASE.md: remove Chocolatey section
  RELEASE.md
Labels: area/documentation, bug

#8293 Add timeout for boost::asio::ssl::stream#async_shutdown()
  lib/base/io-engine.cpp
  lib/base/io-engine.hpp
  lib/remote/apilistener.cpp
  lib/remote/jsonrpcconnection.cpp
Labels: area/distributed, bug

#8243 Improve IDO queue stats logging
  lib/base/workqueue.cpp
  lib/base/workqueue.hpp
  lib/db_ido/dbconnection.cpp
  lib/db_ido/dbconnection.hpp
  lib/db_ido_mysql/idomysqlconnection.cpp
  lib/db_ido_mysql/idomysqlconnection.hpp
  lib/db_ido_pgsql/idopgsqlconnection.cpp
  lib/db_ido_pgsql/idopgsqlconnection.hpp
Labels: area/db-ido, area/log, enhancement

#8318 Catch exceptions in the thread running HandleConfigUpdate
  lib/remote/apilistener-filesync.cpp
Labels: area/distributed, core/crash, ref/NC

#8326 Do not upsert customvar status on heavy config update
  lib/db_ido/dbobject.cpp
Labels: area/db-ido, core/quality

#8242 Don't send reminder notifications before suppressed ones
  lib/notification/notificationcomponent.cpp
Labels: area/notifications, bug

#8363 IDO MySQL: actually COMMIT after 25000 async queries
  lib/db_ido_mysql/idomysqlconnection.cpp
  lib/db_ido_mysql/idomysqlconnection.hpp
Labels: area/db-ido, bug

#8364 Make ApiListener::m_ConfigSyncStageLock a SpinLock
  lib/base/CMakeLists.txt
  lib/base/spinlock.cpp
  lib/base/spinlock.hpp
  lib/remote/apilistener-filesync.cpp
  lib/remote/apilistener.hpp
Labels: area/distributed, bug, core/crash

#8370 Application#RunEventLoop(): don't wait for the thread pool to stop on shutdown
  lib/base/application.cpp
Labels: core/crash

#8371 Revert "MacroProcessor::ResolveArguments(): skip null argument values"
  lib/icinga/macroprocessor.cpp
Labels: area/checks, bug

#8166 Ensure the daemon doesn't get killed by logrotate
  lib/cli/daemoncommand.cpp
Labels: area/log, bug, core/crash

#8378 IDO: Do not log, if paused
  lib/db_ido/dbconnection.cpp
  lib/db_ido_mysql/idomysqlconnection.cpp
Labels: area/db-ido, area/log, bug

#8376 icinga2 daemon: reap remaining child processes after reload
  lib/cli/daemoncommand.cpp
Labels: area/checks, bug, core/crash

#8379 IDO: Do not log, if paused
  lib/db_ido/dbconnection.cpp
  lib/db_ido_mysql/idomysqlconnection.cpp
Labels: area/db-ido, area/log, bug

#8380 IDO: Do not log stats, if paused
  lib/db_ido/dbconnection.cpp
  lib/db_ido_mysql/idomysqlconnection.cpp
Labels: area/db-ido, area/log, bug

#8374 icinga2 daemon: reap remaining child processes after reload
  lib/cli/daemoncommand.cpp
Labels: area/checks, bug, core/crash

#8229 Check !!downtime->GetCheckable() before downtime->GetCheckable()->GetName()
  lib/icinga/downtime.cpp
Labels: bug, core/crash, ref/NC

#8165 ProcessCheckResult(): Make sure hosts aren't locked during Service::GetSeverity()
  lib/icinga/checkable-check.cpp
Labels: area/checks, area/icingadb, bug

#8331 IDO: Make sure to insert program status
  lib/db_ido/dbconnection.cpp
  lib/db_ido/dbconnection.hpp
  lib/db_ido_mysql/idomysqlconnection.hpp
  lib/db_ido_pgsql/idopgsqlconnection.hpp
Labels: area/db-ido, bug

#8277 Call Process::InitializeSpawnHelper() ASAP
  lib/cli/daemoncommand.cpp
Labels: area/checks, bug

#7864 Add timeout for boost::asio::ssl::stream#async_shutdown()
  lib/base/io-engine.cpp
  lib/base/io-engine.hpp
  lib/remote/apilistener.cpp
  lib/remote/jsonrpcconnection.cpp
Labels: area/distributed, bug

#8388 Remove Utility::GetEnv from header
  lib/base/utility.hpp
Labels: core/quality

#8393 docs: remove references to Visual Studio 2017
  doc/21-development.md
Labels: area/documentation, area/windows, bug

#8394 RELEASE.md: update branch workflow for packaging repos
  RELEASE.md
Labels: area/documentation, enhancement

#7736 API-Event StateChange & CheckResult: Added acknowledgement and downtime_depth…
  doc/12-icinga2-api.md
  lib/icinga/apievents.cpp
Labels: area/api, enhancement

#8115 Docs: In some places, Timeperiod is used instead of TimePeriod
  doc/08-advanced-topics.md
  doc/10-icinga-template-library.md
Labels: area/documentation, bug

#8163 Fix a small typ with a missing apostrophe
  doc/14-features.md
Labels: area/documentation, bug

#8245 Fixes an issue with opentsdb and a double space
  lib/perfdata/opentsdbwriter.cpp
Labels: area/opentsdb, bug

#8081 Adjust Event-S-R API query syntax error
  doc/12-icinga2-api.md
Labels: area/documentation, bug

#8085 Fix LC_NUMERIC set twice and use a wrong value
  lib/base/process.cpp
Labels: area/checks, bug

#8315 Adjust documentation using wrong attributes type
  doc/09-object-types.md
Labels: area/documentation, area/influxdb, bug

#8123 ido_pgsql: do not set standard_conforming_strings to off
  lib/db_ido_pgsql/idopgsqlconnection.cpp
Labels: area/db-ido, bug

#8101 State timestamps set by the same check result differ across nodes
  lib/icinga/checkable-check.cpp
Labels: area/checks, area/distributed, bug
