Repository Icinga/icinga2, pull requests merged in 2020-03, with the labels that each got.

#7881 Document Checkable#acknowledgement_last_change
  doc/09-object-types.md
Labels: area/documentation

#7884 Fix OnHostProblemChanged signal
  lib/icinga/checkable-check.cpp
Labels: area/checks, bug

#7886 IcingaDB: make signal handlers synchronous
  lib/icingadb/icingadb-objects.cpp
Labels: area/icingadb

#7823 Fix timing point for Application::GetStartTime() (related to command endpoint grace period)
  icinga-app/icinga.cpp
  lib/base/application.cpp
  lib/base/application.hpp
  lib/icinga/checkable-check.cpp
  lib/icinga/checkable.cpp
  lib/icinga/cib.cpp
  lib/icinga/icingaapplication.cpp
  lib/methods/icingachecktask.cpp
  lib/methods/randomchecktask.cpp
  lib/remote/apilistener-authority.cpp
Labels: area/checks, area/distributed, bug, core/quality

#7900 IcingaDB: Downtime, Comment, Notification: Add host_id, if object_type is service
  lib/icingadb/icingadb-objects.cpp
Labels: area/icingadb, bug

#7902 Add missing 2.11.3 CHANGELOG entry
  CHANGELOG.md
Labels: core/quality

#7906 Icinga DB - Flapping history: Add percent_state_change_start/end
  lib/icingadb/icingadb-objects.cpp
Labels: area/icingadb

#7911 Sort AUTHORS case-insensitively
  AUTHORS
  RELEASE.md
Labels: area/documentation

#7913 Docs: Icinga DB installation
  doc/02-installation.md
  doc/14-features.md
Labels: area/documentation

#7938 Docs: Fix Icinga Web 2 docs URL
  doc/02-installation.md
Labels: area/documentation
