Repository Icinga/icinga2, pull requests merged in 2021-02, with the labels that each got.

#7092 Fix Windows command escape for \"
  lib/base/utility.cpp
  test/CMakeLists.txt
  test/base-utility.cpp
Labels: area/windows, bug

#8622 dependency.ti: fix typo
  lib/icinga/dependency.ti
Labels: area/configuration, area/runtime, bug

#8614 Improve handling of exceptions thrown by RunWorker
  lib/cli/daemoncommand.cpp
Labels: area/windows, bug

#8637 GitHub actions: drop openSUSE v15.1
  .github/workflows/packages.yml
Labels: area/ci

#8636 GitHub actions: drop SLES v15.1
  .github/workflows/packages.yml
Labels: area/ci
