Repository Icinga/icinga2, pull requests merged in 2021-07, with the labels that each got.

#8842 RELEASE.md: Re-provision Build Server
  RELEASE.md
Labels: area/documentation, area/windows

#8626 Ido*sqlConnection#InternalDeactivateObject(): mark object inactive also in memory
  lib/db_ido_mysql/idomysqlconnection.cpp
  lib/db_ido_pgsql/idopgsqlconnection.cpp
Labels: area/api, area/db-ido, bug, ref/NC

#8858 Cancel previous HEAD's jobs only for PRs
  .github/workflows/docker.yml
  .github/workflows/packages.yml
Labels: area/ci

#8861 GitHub actions: auto-cancel previous jobs for the same PR
  .github/workflows/docker.yml
  .github/workflows/packages.yml
Labels: area/ci

#8862 GitHub actions: build Windows
  .github/workflows/packages.yml
  appveyor.yml
  doc/21-development.md
  doc/win-dev.ps1
  tools/win32/configure.ps1
  tools/win32/load-vsenv.ps1
Labels: area/ci, area/documentation, area/windows

#8867 GitHub actions: auto-cancel previous jobs for the same PR
  .github/workflows/packages.yml
Labels: area/ci

#8868 GitHub actions: build Windows
  .github/workflows/packages.yml
  appveyor.yml
  doc/21-development.md
  doc/win-dev.ps1
  tools/win32/configure.ps1
  tools/win32/load-vsenv.ps1
Labels: area/ci, area/documentation, area/windows

#8875 Bump build deps
  doc/21-development.md
  doc/win-dev.ps1
  tools/win32/configure-dev.ps1
  tools/win32/configure.ps1
Labels: core/consider-backporting, core/quality

#8730 IDO: update program status on stop
  lib/db_ido/dbconnection.cpp
  lib/db_ido/dbconnection.hpp
  lib/db_ido_mysql/idomysqlconnection.cpp
  lib/db_ido_mysql/idomysqlconnection.hpp
  lib/db_ido_pgsql/idopgsqlconnection.cpp
  lib/db_ido_pgsql/idopgsqlconnection.hpp
Labels: area/db-ido, bug

#8872 Add timeout for full Icinga connection handshake
  doc/09-object-types.md
  lib/remote/apilistener.cpp
  lib/remote/apilistener.ti
Labels: area/distributed, bug, ref/IP

#8871 ScheduledDowntime::TimerProc(): Catch exceptions to make sure other downtimes are still created
  lib/icinga/scheduleddowntime.cpp
Labels: area/runtime, bug

#8866 Add timeout for full Icinga connection handshake
  doc/09-object-types.md
  lib/remote/apilistener.cpp
  lib/remote/apilistener.ti
Labels: area/distributed, bug, ref/IP

#8863 ScheduledDowntime::TimerProc(): Catch exceptions to make sure other downtimes are still created
  lib/icinga/scheduleddowntime.cpp
Labels: area/runtime, bug

#8874 Checkable::NotifyDowntimeEnd(): don't send Downtime end notification unless triggered
  lib/icinga/checkable.cpp
Labels: area/runtime, bug, core/consider-backporting

#8310 On ScheduledDowntime change: remove downtimes created before change
  lib/icinga/downtime.cpp
  lib/icinga/downtime.ti
  lib/icinga/scheduleddowntime.cpp
  lib/icinga/scheduleddowntime.hpp
Labels: area/configuration, core/consider-backporting, enhancement, ref/IP, ref/NC

#8830 Icinga DB: no active checks? Not overdue!
  lib/icingadb/icingadb-objects.cpp
Labels: area/icingadb, enhancement

#8761 Icinga DB: introduce icinga:*:state#normalized_performance_data
  doc/05-service-monitoring.md
  lib/icinga/pluginutility.cpp
  lib/icinga/pluginutility.hpp
  lib/icingadb/icingadb-objects.cpp
  test/CMakeLists.txt
  test/icinga-perfdata.cpp
Labels: area/icingadb, enhancement

#8884 Windows build scripts: allow setting BITS=32 to use 32 bit dependency paths by default
  tools/win32/configure.ps1
Labels: area/ci, core/consider-backporting

#8887 Windows build scripts: allow setting BITS=32 to use 32 bit dependency paths by default
  tools/win32/configure.ps1
Labels: core/quality

#8885 Bump OpenSSL to 1.1.1k
  doc/win-dev.ps1
  tools/win32/configure.ps1
Labels: core/quality

#8888 Bump OpenSSL to 1.1.1k
  doc/win-dev.ps1
  tools/win32/configure.ps1
Labels: core/quality

#8889 Downtime#Start(): trigger fixed downtimes immediately instead of waiting for the timer
  lib/icinga/downtime.cpp
Labels: area/runtime, bug, ref/IP

#8865 Improve crashlog
  CMakeLists.txt
  config.h.cmake
  doc/21-development.md
  lib/base/application.cpp
  lib/base/exception.cpp
  lib/base/exception.hpp
  lib/base/stacktrace.cpp
  lib/base/stacktrace.hpp
  test/base-stacktrace.cpp
Labels: area/log, enhancement

#8869 Improve crashlog
  CMakeLists.txt
  config.h.cmake
  doc/21-development.md
  lib/base/application.cpp
  lib/base/exception.cpp
  lib/base/exception.hpp
  lib/base/stacktrace.cpp
  lib/base/stacktrace.hpp
  test/base-stacktrace.cpp
Labels: area/log, enhancement

#8855 Fix IDO MySQL schema version (as in v2.11 upgrade)
  lib/db_ido/dbconnection.hpp
  lib/db_ido/idochecktask.cpp
  lib/db_ido_mysql/idomysqlconnection.cpp
  lib/db_ido_mysql/idomysqlconnection.hpp
  lib/db_ido_mysql/schema/mysql.sql
  lib/db_ido_pgsql/idopgsqlconnection.cpp
  lib/db_ido_pgsql/idopgsqlconnection.hpp
Labels: area/db-ido, bug

#8425 IDO MySQL: support larger host and service names
  lib/db_ido_mysql/idomysqlconnection.cpp
  lib/db_ido_mysql/schema/mysql.sql
  lib/db_ido_mysql/schema/upgrade/2.13.0.sql
Labels: area/db-ido, bug

#6326 Implement scheduling_endpoint attribute
  doc/08-advanced-topics.md
  lib/icinga/apiactions.cpp
  lib/icinga/checkable-check.cpp
  lib/icinga/checkresult.ti
  lib/icinga/host.cpp
  lib/icinga/service.cpp
Labels: area/api, enhancement

#8634 RedisConnection: log actual query performance
  lib/icingadb/icingadb-objects.cpp
  lib/icingadb/icingadb.cpp
  lib/icingadb/icingadb.hpp
  lib/icingadb/redisconnection.cpp
  lib/icingadb/redisconnection.hpp
Labels: area/icingadb, area/log, bug

#8721 GitHub actions: also build on Debian Bullseye
  .github/workflows/packages.yml
Labels: area/ci

#8894 RedisConnection: log info messages only once
  lib/icingadb/redisconnection.cpp
Labels: area/icingadb, bug

#8918 Icinga DB: HDEL also icinga:checksum:*, not only icinga:*
  lib/icingadb/icingadb-objects.cpp
Labels: area/icingadb, bug

#8544 Icinga DB: support TLS
  doc/09-object-types.md
  lib/base/tlsutility.cpp
  lib/base/tlsutility.hpp
  lib/icingadb/icingadb.cpp
  lib/icingadb/icingadb.hpp
  lib/icingadb/icingadb.ti
  lib/icingadb/redisconnection.cpp
  lib/icingadb/redisconnection.hpp
  lib/remote/apilistener.cpp
  lib/remote/apilistener.ti
Labels: area/icingadb, enhancement

#8934 Split GitHub actions
  .github/workflows/deb.yml
  .github/workflows/docker.yml
  .github/workflows/packages.yml
  .github/workflows/raspbian.yml
  .github/workflows/rpm.yml
  .github/workflows/windows.yml
Labels: area/ci

#8913 API Action "remove-downtime": Also remove child downtimes
  lib/icinga/apiactions.cpp
  lib/icinga/checkable-downtime.cpp
  lib/icinga/downtime.cpp
  lib/icinga/downtime.hpp
  lib/icinga/downtime.ti
  lib/icinga/externalcommandprocessor.cpp
  lib/icingadb/icingadb-objects.cpp
Labels: area/api, area/runtime, enhancement

#8921 TimePeriod/ScheduledDowntime: improve DST handling
  lib/icinga/legacytimeperiod.cpp
  lib/icinga/legacytimeperiod.hpp
  test/CMakeLists.txt
  test/icinga-legacytimeperiod.cpp
Labels: area/runtime, bug

#8930 WorkQueue#ParallelFor(): optionally don't pre-glue items together to chunks of different size
  lib/base/workqueue.hpp
  lib/icingadb/icingadb-objects.cpp
Labels: area/icingadb, bug

#8923 Icinga DB: DEL icinga:nextupdate:* along with the other keys to delete
  lib/icingadb/icingadb-objects.cpp
Labels: area/icingadb, bug

#8915 Icinga DB: priorize state > config
  lib/icingadb/icingadb-objects.cpp
  lib/icingadb/icingadb.cpp
  lib/icingadb/redisconnection.hpp
Labels: area/icingadb, enhancement

#8897 RedisConnection: AUTH and SELECT
  lib/icingadb/redisconnection.cpp
  lib/icingadb/redisconnection.hpp
Labels: area/icingadb, bug

#8933 Icinga DB: only start multiple Redis connections after the first one succeeded
  lib/icingadb/icingadb.cpp
Labels: area/icingadb

#8937 Override exit code on process timeout
  lib/base/process.cpp
Labels: area/checks

#8899 Introduce IcingaDB#connect_timeout
  doc/09-object-types.md
  lib/base/tlsutility.hpp
  lib/icingadb/icingadb.cpp
  lib/icingadb/icingadb.hpp
  lib/icingadb/icingadb.ti
  lib/icingadb/redisconnection.cpp
  lib/icingadb/redisconnection.hpp
  lib/remote/apilistener.ti
Labels: area/icingadb, enhancement

#8940 RedisConnection: copy callback before calling it
  lib/icingadb/redisconnection.cpp
Labels: area/icingadb, bug, queue/important

#8916 Icinga DB: introduce Checkable#last_comment_id
  lib/icinga/checkable-comment.cpp
  lib/icinga/checkable.hpp
  lib/icingadb/icingadb-objects.cpp
  lib/icingadb/icingadb.hpp
Labels: area/icingadb, enhancement

#8941 Icinga DB: ensure all connections are ready on first use
  lib/icingadb/icingadb.cpp
  lib/icingadb/icingadb.hpp
Labels: area/icingadb, bug

#8943 Docs: Describe parameter 'expiry' in 'add-comment' API action
  doc/12-icinga2-api.md
Labels: area/api, area/documentation, bug, enhancement
