Repository Icinga/icinga2, pull requests merged in 2021-01, with the labels that each got.

#8088 Display logmessage if two nodes run on different versions
  lib/remote/apilistener.cpp
Labels: area/distributed, area/log, enhancement

#8083 Implement new API event streams response
  doc/12-icinga2-api.md
  lib/icinga/apievents.cpp
  lib/icinga/apievents.hpp
  lib/remote/eventqueue.hpp
  lib/remote/eventshandler.cpp
Labels: area/api, enhancement

#8431 Windows agent: Default to lower case FQDN
  agent/windows-setup-agent/SetupWizard.cs
Labels: area/setup, area/windows, enhancement

#8591 Fix crash when notifications are sent while the notification object is deleted
  lib/icinga/notification.cpp
Labels: area/distributed, area/notifications, core/crash

#8442 Close FDs based on /proc/self/fd
  icinga-app/icinga.cpp
  lib/base/process.cpp
  lib/base/utility.cpp
  lib/base/utility.hpp
Labels: bug

#8157 Clean up temp files
  lib/base/configobject.cpp
  lib/icinga/icingaapplication.cpp
Labels: bug

#8025 ConfigObjectUtility::GetObjectConfigPath(): hash names of not already existing objects
  lib/remote/configobjectutility.cpp
Labels: area/configuration, bug

#8001 Doc: clarify TimePeriod/ScheduledDowntime time zone handling
  doc/08-advanced-topics.md
  doc/09-object-types.md
Labels: area/documentation

#8104 API: Display a correct status when removing a downtime
  lib/base/exception.cpp
  lib/base/exception.hpp
  lib/icinga/apiactions.cpp
  lib/icinga/downtime.cpp
  lib/icinga/externalcommandprocessor.cpp
Labels: area/api, bug

#8562 Fix no re-notification for non OK state changes with time delay
  lib/icinga/notification.cpp
Labels: area/notifications, bug

#8427 StartUnixWorker(): don't exit() on fork() failure
  lib/cli/daemoncommand.cpp
Labels: area/cli, bug

#8529 GitHub actions: drop Fedora 31
  .github/workflows/packages.yml
Labels: area/ci

#8515 API: Update the ssl context after each accepting incoming connection
  lib/base/utility.cpp
  lib/base/utility.hpp
  lib/remote/apilistener.cpp
Labels: area/distributed, enhancement

#8594 Remove upq from ConfigItem::ActivateItems
  lib/cli/daemoncommand.cpp
  lib/config/configitem.cpp
  lib/config/configitem.hpp
  lib/remote/configobjectutility.cpp
Labels: core/quality

#8599 IcingaDB: Check whether or not cr is nullptr
  lib/icingadb/icingadb-objects.cpp
Labels: area/icingadb, core/crash

#8588 Fix null pointer dereferences when deleting objects while scheduling downtimes
  lib/icinga/apiactions.cpp
  lib/icinga/downtime.cpp
  lib/icinga/downtime.hpp
  lib/icinga/externalcommandprocessor.cpp
  lib/icinga/scheduleddowntime.cpp
Labels: area/api, core/crash

#8593 Remove incorrect assertion in ConfigItem::ActivateItems
  lib/config/configitem.cpp
Labels: area/configuration, core/quality

#8605 IcingaDB: wait for queries to be executed in inital sync
  lib/icingadb/icingadb-objects.cpp
  lib/icingadb/redisconnection.cpp
  lib/icingadb/redisconnection.hpp
Labels: area/icingadb, bug

#8604 IcingaDB: start initial dump in callback instead of timer
  lib/icingadb/icingadb-objects.cpp
  lib/icingadb/icingadb.cpp
  lib/icingadb/icingadb.hpp
  lib/icingadb/redisconnection.cpp
  lib/icingadb/redisconnection.hpp
Labels: area/icingadb

#8600 Flapping: Allow to ignore states in flapping detection
  doc/08-advanced-topics.md
  doc/09-object-types.md
  lib/icinga/checkable-check.cpp
  lib/icinga/checkable-flapping.cpp
  lib/icinga/checkable.cpp
  lib/icinga/checkable.hpp
  lib/icinga/checkable.ti
Labels: area/checks, enhancement, ref/NC

#7918 On check_timeout first send SIGTERM
  lib/base/process.cpp
  lib/base/process.hpp
Labels: area/checks, enhancement

#8158 Checkable#ProcessCheckResult(): don't overwrite check source
  lib/icinga/checkable-check.cpp
Labels: area/checks, bug

#8513 FireSuppressedNotifications(const Notification::Ptr&): don't send notifications while suppressed by checkable
  lib/icinga/checkable-notification.cpp
  lib/icinga/checkable.hpp
  lib/notification/notificationcomponent.cpp
Labels: area/notifications, bug

#8602 Delay start of IcingaDB until most config objects are activated
  lib/icingadb/icingadb.ti
Labels: area/icingadb, bug

#8020 check_mysql: don't set -H if -s is given
  itl/command-plugins.conf
Labels: area/itl, bug

#8613 IdoCheckTask: Don't override checkable critical with warn state
  lib/db_ido/idochecktask.cpp
Labels: area/db-ido, area/itl, bug
