Repository Icinga/icinga2, pull requests merged in 2021-05, with the labels that each got.

#8733 Icinga DB runtime updates and state via streams
  lib/icingadb/icingadb-objects.cpp
  lib/icingadb/icingadb-utility.cpp
  lib/icingadb/icingadb.cpp
  lib/icingadb/icingadb.hpp
Labels: area/icingadb

#8767 GitHub actions: don't build on Fedora 32
  .github/workflows/packages.yml
Labels: area/ci

#8763 Icinga DB: Replace global keys spacer '_' with ':' to fit new schema
  lib/icingadb/icingadb-objects.cpp
Labels: area/icingadb, bug

#8764 Icinga DB: Change ID fields to match SQL schema
  lib/icingadb/icingadb-objects.cpp
Labels: area/icingadb

#8677 IDO: Use own transaction for program status and make sure InternalNewTransaction() gets executed
  lib/db_ido/dbconnection.cpp
  lib/db_ido_mysql/idomysqlconnection.cpp
Labels: area/db-ido, bug, core/consider-backporting

#8352 GitHub actions: build also support/*
  .github/workflows/docker.yml
  .github/workflows/packages.yml
Labels: area/ci

#8789 Fix non-unity builds in support/2.11
  lib/base/tlsutility.hpp
Labels: core/build-fix

#8790 GitHub actions: update distros
  .github/workflows/packages.yml
Labels: area/ci

#8802 Fix building with Boost 1.71.
  third-party/cmake/BoostTestTargets.cmake
Labels: area/setup, core/quality

#8793 Support Boost 1.74
  CMakeLists.txt
  lib/base/string.cpp
  lib/base/string.hpp
  lib/base/utility.cpp
  lib/perfdata/elasticsearchwriter.cpp
  lib/perfdata/influxdbwriter.cpp
  lib/remote/configfileshandler.cpp
  lib/remote/httpserverconnection.cpp
  lib/remote/httputility.cpp
  lib/remote/infohandler.cpp
Labels: bug

#8792 Support Boost 1.74
  CMakeLists.txt
  lib/base/string.cpp
  lib/base/string.hpp
  lib/base/utility.cpp
  lib/perfdata/elasticsearchwriter.cpp
  lib/perfdata/influxdbwriter.cpp
  lib/remote/configfileshandler.cpp
  lib/remote/httpserverconnection.cpp
  lib/remote/httputility.cpp
  lib/remote/infohandler.cpp
Labels: bug

#8708 Make sure not to send reminder notification, if problem notification has been suppressed by TimePeriod
  lib/notification/notificationcomponent.cpp
Labels: area/notifications, bug, core/consider-backporting

#8791 GitHub actions: build packages
  .github/workflows/packages.yml
  .travis.yml
Labels: area/ci

#8788 ConfigObjectUtility#CreateObject(): check config objects for duplicates
  lib/remote/configobjectutility.cpp
Labels: core/consider-backporting

#8808 Make sure not to send reminder notification, if problem notification has been suppressed by TimePeriod
  lib/notification/notificationcomponent.cpp
Labels: area/notifications, bug

#8782 Fix crash when notifications are sent while the notification object is deleted (2.12)
  lib/icinga/notification.cpp
Labels: area/distributed, area/notifications, core/crash

#8775 Send problem notifications after downtime end for checkables in child zones (2.12)
  doc/19-technical-concepts.md
  lib/icinga/clusterevents.cpp
Labels: area/distributed, area/notifications, bug, ref/IP, ref/NC

#8784 Fix null pointer dereferences when deleting objects while scheduling downtimes (2.11)
  lib/icinga/apiactions.cpp
  lib/icinga/downtime.cpp
  lib/icinga/downtime.hpp
  lib/icinga/externalcommandprocessor.cpp
  lib/icinga/scheduleddowntime.cpp
Labels: area/api, core/crash

#8780 Fix crash when notifications are sent while the notification object is deleted (2.11)
  lib/icinga/notification.cpp
Labels: area/distributed, area/notifications, core/crash

#8776 Improve handling of exceptions thrown by RunWorker (2.11)
  lib/cli/daemoncommand.cpp
Labels: area/windows, bug

#8772 Send problem notifications after downtime end for checkables in child zones (2.11)
  doc/19-technical-concepts.md
  lib/icinga/clusterevents.cpp
Labels: area/distributed, area/notifications, bug, ref/IP, ref/NC

#8770 Retry file rename operations on Windows for some errors (2.11)
  lib/base/utility.cpp
Labels: area/windows, bug, core/crash

#8810 IDO: Use own transaction for program status and make sure InternalNewTransaction() gets executed
  lib/db_ido/dbconnection.cpp
  lib/db_ido_mysql/idomysqlconnection.cpp
Labels: area/db-ido, bug

#8777 Improve handling of exceptions thrown by RunWorker (2.12)
  lib/cli/daemoncommand.cpp
Labels: area/windows, bug

#8771 Retry file rename operations on Windows for some errors (2.12)
  lib/base/utility.cpp
Labels: area/windows, bug, core/crash

#8809 IDO: Use own transaction for program status and make sure InternalNewTransaction() gets executed
  lib/db_ido/dbconnection.cpp
  lib/db_ido_mysql/idomysqlconnection.cpp
Labels: area/db-ido, bug
