Repository Icinga/icinga2, pull requests merged in 2021-03, with the labels that each got.

#8641 Icinga DB: don't write all types
  lib/icingadb/icingadb-objects.cpp
Labels: area/icingadb, bug

#8649 Icinga DB: HMSET the same fields only once
  lib/icingadb/icingadb-objects.cpp
  lib/icingadb/icingadb.cpp
  lib/icingadb/icingadb.hpp
Labels: area/icingadb, bug

#8620 GitHub actions: build Fedora v33
  .github/workflows/packages.yml
Labels: area/ci

#8621 GitHub actions: build SLES v15.2
  .github/workflows/packages.yml
Labels: area/ci

#8003 check_snmp_int: support -a
  doc/10-icinga-template-library.md
  itl/command-plugins-manubulon.conf
Labels: area/itl, enhancement

#8619 GitHub actions: build openSUSE v15.2
  .github/workflows/packages.yml
Labels: area/ci

#8008 PluginUtility::ParseCheckOutput(): if it doesn't look like perfdata, it's not perfdata
  lib/icinga/pluginutility.cpp
Labels: area/checks

#8650 Icinga DB: re-insert only changed object attributes
  lib/icingadb/icingadb-objects.cpp
  lib/icingadb/icingadb.hpp
Labels: area/icingadb, enhancement

#8676 IcingaDB#UpdateAllConfigObjects(): don't modify map concurrently
  lib/icingadb/icingadb-objects.cpp
Labels: area/icingadb, bug, core/crash

#8681 Send problem notifications after downtime end for checkables in child zones
  doc/19-technical-concepts.md
  lib/icinga/clusterevents.cpp
Labels: area/distributed, area/notifications, bug, core/consider-backporting, ref/IP, ref/NC

#8688 Speed up SHA1 function by removing calls to sprintf
  lib/base/tlsutility.cpp
  test/CMakeLists.txt
  test/base-tlsutility.cpp
Labels: core/quality

#8697 JsonEncode(): serialize integers w/o trailing .0
  lib/base/json.cpp
  test/base-json.cpp
Labels: area/icingadb, bug

#8693 PackObject(): avoid one malloc()
  lib/base/CMakeLists.txt
  lib/base/object-packer.cpp
  lib/base/stringbuilder.cpp
  lib/base/stringbuilder.hpp
Labels: area/icingadb, bug

#8696 RedisConnection::WriteRESP: Use one asio::async_write instead of many
  lib/icingadb/redisconnection.hpp
Labels: area/icingadb, core/quality

#8702 Add missing #include <iostream>
  lib/base/stdiostream.hpp
Labels: core/build-fix

#8691 Retry file rename operations on Windows for some errors
  lib/base/utility.cpp
Labels: area/windows, bug, core/consider-backporting, core/crash

#8698 Icinga DB: cache environment ID instead of recomputing it every time
  lib/icingadb/icingadb-objects.cpp
  lib/icingadb/icingadb.cpp
  lib/icingadb/icingadb.hpp
Labels: area/icingadb

#8547 Fix runtime config updates not working for objects without zone
  lib/remote/apilistener-configsync.cpp
Labels: area/distributed, bug
