Repository Icinga/icinga2, pull requests merged in 2021-12, with the labels that each got.

#9104 GHA: add Raspbian bullseye
  .github/workflows/raspbian.yml
Labels: cla/signed

#9106 Downtime::DowntimesExpireTimerHandler: don't copy vector
  lib/icinga/downtime.cpp
Labels: core/quality, area/runtime, cla/signed

#9111 GHA: Add Ubuntu impish
  .github/workflows/deb.yml
Labels: cla/signed

#8990 Fix scheduling of downtimes for all services on child hosts
  doc/12-icinga2-api.md
  lib/icinga/apiactions.cpp
Labels: bug, ref/IP, area/runtime, consider backporting, cla/signed

#9095 pass nwc_health check SNMPv3 args only if needed
  itl/plugins-contrib.d/network-components.conf
Labels: cla/signed

#8956 Fix IDO MySQL schema version
  lib/db_ido_mysql/2.13.1.sql
  lib/db_ido_mysql/schema/mysql.sql
Labels: bug, area/db-ido, consider backporting, cla/signed

#9122 Set downtime trigger time deterministically
  lib/icinga/checkable-check.cpp
  lib/icinga/checkable-downtime.cpp
  lib/icinga/checkable.hpp
  lib/icinga/downtime.cpp
  lib/icinga/downtime.hpp
Labels: area/distributed, area/icingadb, cla/signed

#9094 Add missing include to fix non-unity builds
  lib/icinga/usergroup.cpp
Labels: core/build-fix, cla/signed
