Repository Icinga/icinga2, pull requests merged in 2021-10, with the labels that each got.

#8514 Replace origin of check_sar-perf.py, since it not not maintained ther…
  doc/05-service-monitoring.md
  doc/10-icinga-template-library.md
Labels: needs feedback, cla/signed

#9000 JournaldLogger - log to systemd journal
  doc/09-object-types.md
  doc/14-features.md
  etc/CMakeLists.txt
  etc/icinga2/features-available/journald.conf
  lib/base/CMakeLists.txt
  lib/base/journaldlogger.cpp
  lib/base/journaldlogger.hpp
  lib/base/journaldlogger.ti
  lib/base/sysloglogger.cpp
  lib/base/sysloglogger.hpp
  tools/syntax/nano/icinga2.nanorc
  tools/syntax/vim/syntax/icinga2.vim
Labels: enhancement, area/log, cla/signed

#9006 Doc: Enhance notification `end` time docs
  doc/03-monitoring-basics.md
  doc/09-object-types.md
Labels: area/documentation, cla/signed

#9001 Icinga DB: Write IDs of notified users into notification history stream
  lib/icingadb/icingadb-objects.cpp
Labels: area/icingadb, cla/signed

#8924 [ITL] Added --datadir, --language and --perflimit for check_postgres
  doc/10-icinga-template-library.md
  itl/plugins-contrib.d/databases.conf
Labels: cla/signed
