Repository Icinga/icinga2, pull requests merged in 2021-04, with the labels that each got.

#8712 Avoid dependency on Visual C++ ATL in tests on Windows
  test/base-utility.cpp
Labels: area/windows, core/build-fix

#8728 GitHub actions: also build on Ubuntu hirsute
  .github/workflows/packages.yml
Labels: area/ci

#8706 Icinga DB: dump the correct icinga:config:endpoint#zone_id
  lib/icingadb/icingadb-objects.cpp
Labels: area/icingadb, bug, needs-feedback

#8729 GitHub actions: also build on Fedora 34
  .github/workflows/packages.yml
Labels: area/ci

#8720 GitHub actions: drop Ubuntu Xenial
  .github/workflows/packages.yml
Labels: area/ci

#8684 IcingaDB: Add dump signals for type dependencies and global keys and change signal pattern
  lib/icingadb/icingadb-objects.cpp
  lib/icingadb/icingadb.hpp
Labels: area/icingadb, enhancement
