Repository Icinga/icinga2, pull requests merged in 2021-08, with the labels that each got.

#8945 GHA: drop EOL Ubuntu groovy
  .github/workflows/deb.yml
Labels: area/ci

#8946 ConfigPackageUtility::ValidatePackageName(): always tolerate already existing packages
  lib/remote/configfileshandler.cpp
  lib/remote/configpackageshandler.cpp
  lib/remote/configpackageutility.cpp
  lib/remote/configpackageutility.hpp
  lib/remote/configstageshandler.cpp
  test/remote-configpackageutility.cpp
Labels: area/api, area/configuration, core/build-fix

#8815 Make base_value/format test easier to understand
  test/base-value.cpp
Labels: area/tests, core/quality

#8954 README.md: remove misleading badge
  README.md
Labels: area/documentation, cla/signed

#8955 IDO PgSQL: always use regular string literals
  lib/db_ido_pgsql/idopgsqlconnection.cpp
Labels: bug, area/db-ido, cla/signed

#8957 ApiListener: Choose bind host default based on OS IPv6 support
  doc/09-object-types.md
  doc/17-language-reference.md
  lib/base/configuration.cpp
Labels: area/distributed, area/api, cla/signed

#8961 ApiListener: Choose bind host default based on OS IPv6 support (2.13)
  doc/09-object-types.md
  doc/17-language-reference.md
  lib/base/configuration.cpp
Labels: area/distributed, area/api, cla/signed

#8958 IDO PgSQL: always use regular string literals (2.13)
  lib/db_ido_pgsql/idopgsqlconnection.cpp
Labels: bug, area/db-ido, cla/signed

#8966 Icinga DB: introduce icinga:history:stream:downtime#scheduled_by
  lib/icingadb/icingadb-objects.cpp
Labels: enhancement, area/icingadb, cla/signed

#8977 Add 2.13.1 changelog and bump ICINGA2_VERSION
  CHANGELOG.md
  ICINGA2_VERSION
Labels: cla/signed
