Repository Icinga/icinga2, pull requests merged in 2022-02, with the labels that each got.

#9201 GHA: drop CentOS 8
  .github/workflows/rpm.yml
Labels: area/ci, consider backporting, cla/signed

#9197 ITL: Add --extra-opts parameter to the mysql and pgsql CheckCommand d…
  doc/10-icinga-template-library.md
  itl/command-plugins.conf
Labels: cla/signed

#9154 Icinga DB: ensure is_reachable and severity don't miss updates
  lib/icinga/checkable-check.cpp
  lib/icingadb/icingadb-objects.cpp
  lib/icingadb/icingadb.hpp
Labels: area/icingadb, cla/signed

#9208 GitHub Actions: pin Windows Server version to 2019
  .github/workflows/windows.yml
Labels: cla/signed

#9217 Update installation instructions for easier navigation on icinga.com
  doc/02-installation.md
  doc/02-installation.md.d/01-Debian.md
  doc/02-installation.md.d/02-Ubuntu.md
  doc/02-installation.md.d/03-Raspbian.md
  doc/02-installation.md.d/04-Fedora.md
  doc/02-installation.md.d/05-CentOS.md
  doc/02-installation.md.d/06-RHEL.md
  doc/02-installation.md.d/07-OpenSUSE.md
  doc/02-installation.md.d/08-SLES.md
  doc/02-installation.md.d/09-Amazon-Linux.md
  doc/02-installation.md.d/10-Windows.md
  doc/03-monitoring-basics.md
  doc/04-configuration.md
  doc/06-distributed-monitoring.md
  doc/07-agent-based-monitoring.md
  doc/14-features.md
  doc/15-troubleshooting.md
  doc/16-upgrading-icinga-2.md
  doc/21-development.md
  doc/images/installation/mariadb-centos7.png
  doc/images/installation/postgr-import-ido.png
Labels: cla/signed

#9213 IcingaDB: Add previous_soft_state to host_state and service_state
  lib/icingadb/icingadb-objects.cpp
Labels: enhancement, area/icingadb, cla/signed

#9221 Prevent deadlock in ProcessCheckResult
  lib/icinga/checkable-check.cpp
Labels: bug, area/checks, ref/IP, consider backporting, cla/signed

#9212 IDO: fix incorrect contacts in notification history with multiple IDO instances on a single node
  lib/db_ido/dbconnection.cpp
  lib/db_ido/dbevents.cpp
  lib/db_ido/dbobject.cpp
  lib/db_ido/dbobject.hpp
Labels: bug, area/db-ido, ref/IP, cla/signed

#9016 Add new check_nrpe parameter -D to disable logging to syslog
  doc/10-icinga-template-library.md
  itl/command-plugins.conf
Labels: cla/signed

#9231 GHA: drop CentOS 8
  .github/workflows/rpm.yml
Labels: area/ci, cla/signed

#9232 GHA: drop CentOS 8
  .github/workflows/rpm.yml
Labels: area/ci, cla/signed

#9233 GitHub Actions: pin Windows Server version to 2019
  .github/workflows/windows.yml
Labels: cla/signed

#9234 GitHub Actions: pin Windows Server version to 2019
  .github/workflows/windows.yml
Labels: cla/signed

#9230 Update installation instructions for easier navigation on icinga.com
  doc/02-installation.md
  doc/02-installation.md.d/01-Debian.md
  doc/02-installation.md.d/02-Ubuntu.md
  doc/02-installation.md.d/03-Raspbian.md
  doc/02-installation.md.d/04-Fedora.md
  doc/02-installation.md.d/05-CentOS.md
  doc/02-installation.md.d/06-RHEL.md
  doc/02-installation.md.d/07-OpenSUSE.md
  doc/02-installation.md.d/08-SLES.md
  doc/02-installation.md.d/09-Amazon-Linux.md
  doc/02-installation.md.d/10-Windows.md
  doc/03-monitoring-basics.md
  doc/04-configuration.md
  doc/06-distributed-monitoring.md
  doc/07-agent-based-monitoring.md
  doc/14-features.md
  doc/15-troubleshooting.md
  doc/16-upgrading-icinga-2.md
  doc/21-development.md
  doc/images/installation/mariadb-centos7.png
  doc/images/installation/postgr-import-ido.png
Labels: blocker, area/documentation, cla/signed

#9252 Icinga DB: don't write state history for ack/downtime/host problem changes
  lib/icingadb/icingadb-objects.cpp
  lib/icingadb/icingadb.hpp
Labels: bug, area/icingadb, cla/signed

#9253 TimePeriod/ScheduledDowntime: improve DST handling
  lib/icinga/legacytimeperiod.cpp
  lib/icinga/legacytimeperiod.hpp
  test/CMakeLists.txt
  test/icinga-legacytimeperiod.cpp
Labels: bug, area/runtime, cla/signed

#9259 Checkable#ExecuteEventHandler(): don't outsource event command run twice
  lib/icinga/checkable-event.cpp
Labels: bug, ref/IP, area/runtime, cla/signed

#9260 Checkable#ExecuteEventHandler(): don't outsource event command run twice
  lib/icinga/checkable-event.cpp
Labels: bug, ref/IP, area/runtime, cla/signed

#9261 Checkable#ExecuteEventHandler(): don't outsource event command run twice
  lib/icinga/checkable-event.cpp
Labels: bug, ref/IP, area/runtime, cla/signed
