Repository Icinga/icinga2, pull requests merged in 2022-11, with the labels that each got.

#9562 Bump Boost v1.79 -> v1.80
  doc/21-development.md
  doc/win-dev.ps1
  tools/win32/configure-dev.ps1
  tools/win32/configure.ps1
Labels: area/windows, cla/signed

#9560 ConfigItem: Fix infinite recursion caused by `ignore_on_error`
  lib/config/configitem.cpp
Labels: bug, area/configuration, cla/signed

#9558 Construct string once, not unnecessarily N times
  lib/icinga/service-apply.cpp
Labels: area/configuration, core/quality, ref/IP, cla/signed

#9559 Lookup apply rules faster by Type*, not String and by map instead of ==/!=
  lib/config/applyrule.cpp
  lib/config/applyrule.hpp
  lib/config/config_parser.yy
  lib/icinga/dependency-apply.cpp
  lib/icinga/notification-apply.cpp
  lib/icinga/scheduleddowntime-apply.cpp
  lib/icinga/service-apply.cpp
Labels: area/configuration, core/quality, ref/IP, cla/signed

#9545 Separately handle apply rules targetting only specific parent objects
  lib/base/string.cpp
  lib/base/string.hpp
  lib/config/CMakeLists.txt
  lib/config/applyrule-targeted.cpp
  lib/config/applyrule.cpp
  lib/config/applyrule.hpp
  lib/config/expression.hpp
  lib/icinga/dependency-apply.cpp
  lib/icinga/dependency.hpp
  lib/icinga/notification-apply.cpp
  lib/icinga/notification.hpp
  lib/icinga/scheduleddowntime-apply.cpp
  lib/icinga/scheduleddowntime.hpp
  lib/icinga/service-apply.cpp
  lib/icinga/service.hpp
Labels: area/configuration, core/quality, ref/IP, cla/signed

#9565 Separately handle apply rules targetting only specific parent objects
  lib/base/string.cpp
  lib/base/string.hpp
  lib/config/CMakeLists.txt
  lib/config/applyrule-targeted.cpp
  lib/config/applyrule.cpp
  lib/config/applyrule.hpp
  lib/config/expression.hpp
  lib/icinga/dependency-apply.cpp
  lib/icinga/dependency.hpp
  lib/icinga/notification-apply.cpp
  lib/icinga/notification.hpp
  lib/icinga/scheduleddowntime-apply.cpp
  lib/icinga/scheduleddowntime.hpp
  lib/icinga/service-apply.cpp
  lib/icinga/service.hpp
Labels: area/configuration, core/quality, cla/signed

#9566 Windows: update bundled OpenSSL to version 1.1.1s
  doc/win-dev.ps1
  tools/win32/configure.ps1
Labels: area/windows, cla/signed

#9567 Windows: update bundled OpenSSL to version 1.1.1s
  doc/win-dev.ps1
  tools/win32/configure.ps1
Labels: area/windows, cla/signed

#9568 Release 2.13.6
  CHANGELOG.md
  ICINGA2_VERSION
Labels: cla/signed

#9570 Recommend to try libjemalloc to speed up reload
  doc/15-troubleshooting.md
Labels: ref/IP, cla/signed

#9572 ApplyRule#GetF*Var(): return by const ref
  lib/config/applyrule.cpp
  lib/config/applyrule.hpp
Labels: cla/signed

#9577 ConfigItem::CommitNewItems(): allow fast search of pending items by type
  lib/base/type.cpp
  lib/base/type.hpp
  lib/config/configitem.cpp
  tools/mkclass/classcompiler.cpp
Labels: cla/signed

#9593 Change apt-get to apt
  doc/02-installation.md
Labels: cla/signed

#9586 icinga2 daemon: write icinga2.debug only if --dump-objects given
  doc/11-cli-commands.md
  doc/15-troubleshooting.md
  lib/cli/daemoncommand.cpp
  lib/cli/daemonutility.cpp
  lib/cli/objectlistcommand.cpp
  lib/config/configcompilercontext.cpp
  lib/config/configcompilercontext.hpp
  lib/config/configitem.cpp
Labels: enhancement, area/configuration, cla/signed

#9508 Fix data race in `ApplyRule` class
  lib/config/applyrule.cpp
  lib/config/applyrule.hpp
Labels: cla/signed

#9557 CONTEXT: lazily evaluate frames to only actually assemble when needed
  lib/base/configobject.cpp
  lib/base/context.cpp
  lib/base/context.hpp
  lib/compat/checkresultreader.cpp
  lib/config/configcompiler.cpp
  lib/db_ido_mysql/idomysqlconnection.cpp
  lib/db_ido_pgsql/idopgsqlconnection.cpp
  lib/icinga/checkable-check.cpp
  lib/icinga/checkable-event.cpp
  lib/icinga/checkable-notification.cpp
  lib/icinga/dependency-apply.cpp
  lib/icinga/hostgroup.cpp
  lib/icinga/macroprocessor.cpp
  lib/icinga/notification-apply.cpp
  lib/icinga/scheduleddowntime-apply.cpp
  lib/icinga/service-apply.cpp
  lib/icinga/servicegroup.cpp
  lib/icinga/usergroup.cpp
  lib/perfdata/elasticsearchwriter.cpp
  lib/perfdata/gelfwriter.cpp
  lib/perfdata/graphitewriter.cpp
  lib/perfdata/influxdbcommonwriter.cpp
  lib/perfdata/opentsdbwriter.cpp
  lib/perfdata/perfdatawriter.cpp
  lib/remote/apilistener-filesync.cpp
  lib/remote/apilistener.cpp
Labels: area/configuration, core/quality, cla/signed

#9591 icinga2 daemon: w/o --dump-objects just check for circular refs
  lib/base/namespace.cpp
  lib/base/namespace.hpp
  lib/base/serializer.cpp
  lib/base/serializer.hpp
  lib/config/configitem.cpp
Labels: enhancement, area/configuration, cla/signed
