Repository Icinga/icinga2, pull requests merged in 2022-06, with the labels that each got.

#9384 IcingaDB: Add `_name` suffix to columns referring to name
  lib/icingadb/icingadb-objects.cpp
Labels: area/icingadb, consider backporting, cla/signed

#9356 Take host state into account when sending suppressed notifications
  lib/icinga/checkable-notification.cpp
Labels: bug, area/notifications, ref/IP, ref/NC, cla/signed

#9360 Windows: update boost to version 1.79.0
  doc/21-development.md
  doc/win-dev.ps1
  tools/win32/configure-dev.ps1
  tools/win32/configure.ps1
Labels: area/windows, cla/signed

#9362 Remove redundant call to Serialize() in ConfigItem::Commit()
  lib/config/configitem.cpp
Labels: area/configuration, core/quality, consider backporting, cla/signed

#9404 Icinga DB: make error message more helpful if API isn't set up
  lib/icingadb/icingadb.cpp
Labels: area/icingadb, consider backporting, cla/signed

#9257 Doc: Enhance Zones in Zones troubleshooting
  doc/15-troubleshooting.md
Labels: bug, area/documentation, good first issue, cla/signed

#9385 Add new option `-a` to the `mem` CheckCommand
  doc/10-icinga-template-library.md
  itl/plugins-contrib.d/operating-system.conf
Labels: cla/signed

#9399 IcingaDB: Add `_name` suffix to columns referring to name
  lib/icingadb/icingadb-objects.cpp
Labels: area/icingadb, cla/signed

#9398 IcingaDB: handle null (Empty) for value/set_if/separator in command arguments
  lib/icingadb/icingadb-objects.cpp
Labels: area/icingadb, cla/signed

#9397 Introduce Command#arguments[].separator
  doc/09-object-types.md
  itl/command-plugins.conf
  lib/icinga/command.ti
  lib/icinga/macroprocessor.cpp
  lib/icinga/macroprocessor.hpp
  lib/icingadb/icingadb-objects.cpp
Labels: enhancement, cla/signed

#9396 Icinga DB: initialize environment ID during config validation
  lib/icingadb/icingadb.cpp
  lib/icingadb/icingadb.hpp
Labels: bug, area/icingadb, cla/signed

#9400 Remove redundant call to Serialize() in ConfigItem::Commit()
  lib/config/configitem.cpp
Labels: area/configuration, core/quality, cla/signed

#9401 Remove redundant call to Serialize() in ConfigItem::Commit()
  lib/config/configitem.cpp
Labels: area/configuration, core/quality, cla/signed

#9395 Replace EventuallyAtomic with AtomicOrLocked which falls back to a mutex
  lib/base/atomic.hpp
  lib/base/configobject.ti
  lib/icinga/host.ti
  lib/icinga/hostgroup.ti
  lib/icinga/service.ti
  lib/icinga/servicegroup.ti
  lib/icinga/timeperiod.ti
  lib/icinga/user.ti
  lib/icinga/usergroup.ti
  tools/mkclass/classcompiler.cpp
Labels: bug, core/crash, ref/IP, cla/signed

#9394 Synchronize all access to auto-generated class members (from .ti files)
  lib/base/atomic.hpp
  lib/base/configobject.ti
  lib/icinga/host.ti
  lib/icinga/hostgroup.ti
  lib/icinga/service.ti
  lib/icinga/servicegroup.ti
  lib/icinga/timeperiod.ti
  lib/icinga/user.ti
  lib/icinga/usergroup.ti
  tools/mkclass/classcompiler.cpp
Labels: bug, enhancement, area/api, core/crash, ref/IP, cla/signed

#9414 Windows: Update openssl to the latest version 1_1_1p
  doc/win-dev.ps1
  tools/win32/configure.ps1
Labels: cla/signed

#9415 Windows: Update openssl to the latest version 1_1_1p
  doc/win-dev.ps1
  tools/win32/configure.ps1
Labels: cla/signed

#9417 Introduce Icinga DB check (like the IDO one)
  doc/10-icinga-template-library.md
  lib/icingadb/CMakeLists.txt
  lib/icingadb/icingadb-itl.conf
  lib/icingadb/icingadb-objects.cpp
  lib/icingadb/icingadb.cpp
  lib/icingadb/icingadb.hpp
  lib/icingadb/icingadb.ti
  lib/icingadb/icingadbchecktask.cpp
  lib/icingadb/icingadbchecktask.hpp
  lib/icingadb/redisconnection.cpp
  lib/icingadb/redisconnection.hpp
Labels: enhancement, area/icingadb, cla/signed

#9418 Icinga DB: make error message more helpful if API isn't set up
  lib/icingadb/icingadb.cpp
Labels: area/icingadb, cla/signed

#9420 Icinga DB: icinga:*:state: rename state to soft_state
  lib/icingadb/icingadb-objects.cpp
Labels: bug, area/icingadb, consider backporting, cla/signed

#9421 Icinga DB: icinga:*:state: rename state to soft_state
  lib/icingadb/icingadb-objects.cpp
Labels: bug, area/icingadb, cla/signed

#9387 Update Icinga DB related docs
  doc/02-installation.md
  doc/09-object-types.md
  doc/13-addons.md
  doc/14-features.md
  doc/images/addons/nano-syntax.png
  doc/images/addons/vim-syntax.png
  doc/images/icingadb/icingadb-architecture.png
  doc/images/icingadb/icingadb-daemon.png
  doc/images/icingadb/icingadb-icinga2.png
  doc/images/icingadb/icingadb-redis.png
Labels: area/documentation, cla/signed

#9423 Update Icinga DB related docs
  doc/02-installation.md
  doc/09-object-types.md
  doc/13-addons.md
  doc/14-features.md
  doc/images/addons/nano-syntax.png
  doc/images/addons/vim-syntax.png
  doc/images/icingadb/icingadb-architecture.png
  doc/images/icingadb/icingadb-daemon.png
  doc/images/icingadb/icingadb-icinga2.png
  doc/images/icingadb/icingadb-redis.png
Labels: area/documentation, cla/signed

#9403 Release 2.12.9
  CHANGELOG.md
  ICINGA2_VERSION
Labels: cla/signed

#9268 Doc: Windows Dev Environment: correct reboot requirement
  doc/21-development.md
Labels: area/documentation, cla/signed
