Repository Icinga/icinga2, pull requests merged in 2022-10, with the labels that each got.

#9513 Icinga DB: on every check result update state only 1x, not 3x in a row
  lib/icingadb/icingadb-objects.cpp
  lib/icingadb/icingadb.hpp
Labels: bug, area/icingadb, ref/IP, consider backporting, cla/signed

#9519 Utility::ValidateUTF8(): move a string instead of copying a vector
  lib/base/utility.cpp
Labels: core/quality, consider backporting, cla/signed

#9512 [ITL] Added some ignore options for check_ssl_cert
  doc/10-icinga-template-library.md
  itl/plugins-contrib.d/web.conf
Labels: cla/signed

#9407 Don't allow to change object navigation fields at runtime
  lib/icinga/comment.ti
  lib/icinga/dependency.ti
  lib/icinga/downtime.ti
  lib/icinga/notification.ti
  lib/icinga/scheduleddowntime.ti
  lib/icinga/service.ti
  lib/remote/zone.ti
Labels: bug, area/api, good first issue, consider backporting, cla/signed

#9518 StartUnixWorker(): watch forked child via waitpid(), not SIGCHLD handler
  lib/cli/daemoncommand.cpp
Labels: bug, cla/signed

#9406 ConfigItem: Fix infinite recursion caused by `ignore_on_error` when …
  lib/config/configitem.cpp
Labels: bug, area/configuration, cla/signed

#9542 Construct string once, not unnecessarily N times
  lib/icinga/service-apply.cpp
Labels: area/configuration, core/quality, ref/IP, cla/signed

#9543 Lookup apply rules faster by Type*, not String and by map instead of ==/!=
  lib/config/applyrule.cpp
  lib/config/applyrule.hpp
  lib/config/config_parser.yy
  lib/icinga/dependency-apply.cpp
  lib/icinga/notification-apply.cpp
  lib/icinga/scheduleddowntime-apply.cpp
  lib/icinga/service-apply.cpp
Labels: area/configuration, core/quality, ref/IP, cla/signed

#9549 Bump Boost v1.79 -> v1.80
  doc/21-development.md
  doc/win-dev.ps1
  tools/win32/configure-dev.ps1
  tools/win32/configure.ps1
Labels: area/windows, consider backporting, cla/signed

#9550 Backport Icinga DB performance improvements
  lib/base/logger.cpp
  lib/base/logger.hpp
  lib/base/logger.ti
  lib/base/utility.cpp
  lib/icingadb/icingadb-objects.cpp
  lib/icingadb/icingadb.hpp
  lib/icingadb/redisconnection.cpp
Labels: bug, area/icingadb, core/quality, ref/IP, cla/signed
