Repository Icinga/icinga2, pull requests merged in 2023-02, with the labels that each got.

#8744 NodeUtility::WriteNodeConfigObjects(): avoid unneccessary Utility::SetFileOwnership()
  lib/cli/nodeutility.cpp
Labels: bug, area/setup, cla/signed

#9620 Document Notification#times being not aware of downtimes
  doc/03-monitoring-basics.md
Labels: area/notifications, ref/IP, cla/signed

#9647 Docs: Windows Dev Environment: TL;DR: disable unity build
  doc/21-development.md
Labels: area/documentation, area/windows, cla/signed

#9648 Fix config sync after freezing namespaces
  icinga-app/icinga.cpp
  lib/base/scriptframe.cpp
  lib/cli/daemonutility.cpp
  lib/remote/apilistener-filesync.cpp
Labels: area/configuration, blocker, area/distributed, cla/signed

#9598 CheckerComponent#CheckThreadProc(): also propagate next check update …
  lib/checker/checkercomponent.cpp
Labels: bug, area/icingadb, cla/signed

#9622 Main process: ignore SIGHUP
  lib/cli/daemoncommand.cpp
Labels: bug, core/crash, cla/signed

#9466 Deduplicate and stabilize fragile filesystem transactions
  lib/base/atomic-file.cpp
  lib/base/atomic-file.hpp
  lib/base/scriptglobal.cpp
  lib/base/utility.cpp
  lib/base/utility.hpp
  lib/cli/apisetuputility.cpp
  lib/cli/nodesetupcommand.cpp
  lib/cli/nodeutility.cpp
  lib/cli/nodewizardcommand.cpp
  lib/compat/statusdatawriter.cpp
  lib/config/configcompilercontext.cpp
  lib/config/configcompilercontext.hpp
  lib/icinga/icingaapplication.cpp
  lib/remote/apilistener.cpp
  lib/remote/jsonrpcconnection-pki.cpp
Labels: cla/signed

#9585 Doc: Troubleshooting: Optimise apply rules and group assign conditions
  doc/15-troubleshooting.md
Labels: enhancement, area/configuration, area/documentation, needs feedback, cla/signed

#9657 Use a shared_mutex for read `Dictionary` operations
  lib/base/dictionary.cpp
  lib/base/dictionary.hpp
Labels: area/configuration, core/quality, cla/signed

#8389 Forbid dependency cycles
  lib/cli/daemonutility.cpp
  lib/icinga/dependency.cpp
  lib/icinga/dependency.hpp
Labels: enhancement, needs feedback, area/runtime, cla/signed

#9658 Dictionary#*(): remove bool overrideFrozen if unused
  lib/base/dictionary.cpp
  lib/base/dictionary.hpp
  lib/base/scriptglobal.cpp
  lib/base/scriptglobal.hpp
Labels: core/quality, cla/signed

#9667 Windows: bump OpenSSL to v1.1.1t
  doc/win-dev.ps1
  tools/win32/configure.ps1
Labels: area/windows, cla/signed

#9653 Setup all signal handlers with SA_RESTART flag
  lib/base/application.cpp
Labels: bug, ref/IP, consider backporting, cla/signed

#9673 Bump Boost to v1.81
  doc/21-development.md
  doc/win-dev.ps1
  tools/win32/configure-dev.ps1
  tools/win32/configure.ps1
Labels: area/windows, cla/signed

#9668 Update GHA
  .github/workflows/deb.yml
  .github/workflows/docker.yml
  .github/workflows/linux.bash
  .github/workflows/linux.yml
  .github/workflows/raspbian.yml
  .github/workflows/rpm.yml
  .github/workflows/windows.yml
  RELEASE.md
Labels: area/ci, cla/signed

#9669 Update GHA
  .github/workflows/deb.yml
  .github/workflows/docker.yml
  .github/workflows/linux.bash
  .github/workflows/linux.yml
  .github/workflows/raspbian.yml
  .github/workflows/rpm.yml
  .github/workflows/windows.yml
  RELEASE.md
Labels: bug, area/documentation, area/ci, cla/signed

#9672 Windows: bump OpenSSL to v1.1.1t
  doc/win-dev.ps1
  tools/win32/configure.ps1
Labels: area/windows, cla/signed

#9679 CheckerComponent#CheckThreadProc(): also propagate next check update …
  lib/checker/checkercomponent.cpp
Labels: bug, area/icingadb, cla/signed

#9677 Docs: Fix instructions for Fedora
  doc/02-installation.md
  doc/02-installation.md.d/04-Fedora.md
Labels: cla/signed

#9681 Deduplicate and stabilize fragile filesystem transactions
  lib/base/atomic-file.cpp
  lib/base/atomic-file.hpp
  lib/base/scriptglobal.cpp
  lib/base/utility.cpp
  lib/base/utility.hpp
  lib/cli/apisetuputility.cpp
  lib/cli/nodesetupcommand.cpp
  lib/cli/nodeutility.cpp
  lib/cli/nodewizardcommand.cpp
  lib/compat/statusdatawriter.cpp
  lib/config/configcompilercontext.cpp
  lib/config/configcompilercontext.hpp
  lib/icinga/icingaapplication.cpp
  lib/remote/apilistener.cpp
  lib/remote/jsonrpcconnection-pki.cpp
Labels: cla/signed

#9671 Backport docs
  RELEASE.md
  doc/01-about.md
  doc/02-installation.md
  doc/02-installation.md.d/04-Fedora.md
  doc/03-monitoring-basics.md
  doc/04-configuration.md
  doc/05-service-monitoring.md
  doc/09-object-types.md
  doc/10-icinga-template-library.md
  doc/12-icinga2-api.md
  doc/15-troubleshooting.md
  doc/17-language-reference.md
  doc/19-technical-concepts.md
  doc/21-development.md
  etc/icinga2/conf.d/hosts.conf
Labels: area/documentation, cla/signed

#9678 Bump Boost to v1.81
  doc/21-development.md
  doc/win-dev.ps1
  lib/base/string.cpp
  lib/base/string.hpp
  lib/remote/httphandler.cpp
  lib/remote/httpserverconnection.cpp
  tools/win32/configure-dev.ps1
  tools/win32/configure.ps1
Labels: area/windows, cla/signed

#9680 Fix compile error on Solaris 11.4
  lib/base/sysloglogger.cpp
Labels: bug, area/setup, cla/signed

#9682 Setup all signal handlers with SA_RESTART flag
  lib/base/application.cpp
Labels: bug, ref/IP, cla/signed

#9696 Update .mailmap
  .mailmap
Labels: cla/signed

#9686 Boost v1.81, OpenSSL v1.1.1t
  doc/21-development.md
  doc/win-dev.ps1
  lib/base/string.cpp
  lib/base/string.hpp
  lib/remote/httphandler.cpp
  lib/remote/httpserverconnection.cpp
  tools/win32/configure-dev.ps1
  tools/win32/configure.ps1
Labels: cla/signed

#9689 Add role icinga2adm_r to SELinux policies
  tools/selinux/icinga2.te
Labels: cla/signed

#9691 Icinga 2.12.10
  CHANGELOG.md
  ICINGA2_VERSION
Labels: cla/signed

#9690 Add role icinga2adm_r to SELinux policies
  tools/selinux/icinga2.te
Labels: cla/signed

#9692 Icinga 2.13.7
  CHANGELOG.md
  ICINGA2_VERSION
Labels: cla/signed

#9664 Add role icinga2adm_r to SELinux policies
  tools/selinux/icinga2.te
Labels: cla/signed

#8302 Macros: support $env.ENV_VAR_NAME$
  doc/03-monitoring-basics.md
  lib/db_ido/idochecktask.cpp
  lib/icinga/CMakeLists.txt
  lib/icinga/apiactions.cpp
  lib/icinga/envresolver.cpp
  lib/icinga/envresolver.hpp
  lib/icinga/macroprocessor.cpp
  lib/icinga/macroprocessor.hpp
  lib/icingadb/icingadbchecktask.cpp
  lib/livestatus/hoststable.cpp
  lib/livestatus/servicestable.cpp
  lib/methods/clusterzonechecktask.cpp
  lib/methods/dummychecktask.cpp
  lib/methods/icingachecktask.cpp
  lib/methods/pluginchecktask.cpp
  lib/methods/plugineventtask.cpp
  lib/methods/pluginnotificationtask.cpp
  lib/methods/sleepchecktask.cpp
  lib/perfdata/graphitewriter.cpp
  lib/perfdata/influxdbcommonwriter.cpp
  lib/perfdata/opentsdbwriter.cpp
  lib/perfdata/perfdatawriter.cpp
Labels: enhancement, area/windows, cla/signed

#9675 Update third-party/nlohmann_json to v3.9.1
  lib/base/json.cpp
  third-party/nlohmann_json/LICENSE
  third-party/nlohmann_json/json.hpp
Labels: cla/signed

#9662 Repair DSL Namespace values being constant broken in #9627
  lib/base/namespace.cpp
  lib/base/scriptframe.cpp
Labels: area/configuration, core/quality, core/build-fix, cla/signed

#9702 CMakeLists.txt: provide sane defaults for which subsystems to build
  CMakeLists.txt
  doc/21-development.md
  tools/win32/configure-dev.ps1
  tools/win32/configure.ps1
Labels: area/windows, core/quality, cla/signed
