Repository Icinga/icinga2, pull requests merged in 2023-03, with the labels that each got.

#9711 Connect(): don't try next DNS record if operation is canceled
  lib/base/tcpsocket.hpp
Labels: bug, area/distributed, ref/IP, ref/NC, consider backporting, cla/signed

#9717 ProcessSpawnImpl(): remove redundant _exit(128);
  lib/base/process.cpp
Labels: core/quality, cla/signed

#9497 Application::Exit(): don't exit(), but _exit(), even in debug build mode
  lib/base/application.cpp
Labels: bug, core/crash, cla/signed

#9738 Document why Timer::TimerThreadProc() can use Timer members during Timer#~Timer() call
  lib/base/timer.cpp
Labels: core/quality, cla/signed

#9740 Freeze globals namespace during config load
  lib/cli/daemonutility.cpp
Labels: area/configuration, core/quality, cla/signed

#9715 Remove StatusDataWriter which has been deprecated for 5 major versions
  doc/09-object-types.md
  doc/14-features.md
  doc/23-migrating-from-icinga-1x.md
  etc/icinga2/features-available/statusdata.conf
  lib/compat/CMakeLists.txt
  lib/compat/statusdatawriter.cpp
  lib/compat/statusdatawriter.hpp
  lib/compat/statusdatawriter.ti
  lib/icinga/compatutility.cpp
  tools/syntax/nano/icinga2.nanorc
Labels: enhancement, area/compat, core/quality, cla/signed

#9485 Require GCC 7+ for C++17
  CMakeLists.txt
  doc/21-development.md
Labels: cla/signed
