Repository Icinga/icinga2, pull requests merged in 2023-07, with the labels that each got.

#9809 Copy and paste global default TLS cipher set from ssl-config.mozilla.org
  doc/09-object-types.md
  lib/base/tlsutility.hpp
Labels: cla/signed

#9815 Don't hang in timed out connection attempt
  lib/base/tcpsocket.hpp
  lib/remote/apilistener.cpp
Labels: bug, area/distributed, ref/IP, ref/NC, cla/signed

#9821 PluginUtility: Fix PerfData parsing for values separated with multiple spaces
  lib/icinga/pluginutility.cpp
  test/CMakeLists.txt
  test/icinga-perfdata.cpp
Labels: bug, area/metrics, cla/signed

#9812 ElasticsearchWriter: switch to v7+ URL schema to support v8
  lib/perfdata/elasticsearchwriter.cpp
Labels: enhancement, area/elastic, ref/NC, cla/signed

#9820 Checkable#ProcessCheckResult(): only clean up ack comments older than check result
  lib/icinga/apiactions.cpp
  lib/icinga/checkable-check.cpp
  lib/icinga/checkable-comment.cpp
  lib/icinga/checkable.hpp
  lib/icinga/externalcommandprocessor.cpp
Labels: ref/IP, ref/NC, cla/signed

#9818 ElasticsearchWriter#Pause(): call Flush() only once
  lib/perfdata/elasticsearchwriter.cpp
Labels: bug, area/elastic, cla/signed

#9062 Built-in check command: ifw-api
  doc/10-icinga-template-library.md
  itl/command-icinga.conf
  lib/methods/CMakeLists.txt
  lib/methods/ifwapichecktask.cpp
  lib/methods/ifwapichecktask.hpp
  lib/methods/methods-itl.conf
  lib/remote/apilistener.cpp
  lib/remote/apilistener.hpp
Labels: enhancement, area/windows, area/checks, cla/signed

#9822 cluster-zone: consider own zone connected if there's only one endpoint
  lib/methods/clusterzonechecktask.cpp
Labels: bug, area/distributed, area/itl, cla/signed

#9743 GHA: Linux: add Fedora 38, Ubuntu 23.04, Debian 12, openSUSE 15.5
  .github/workflows/linux.bash
  .github/workflows/linux.yml
Labels: area/ci, cla/signed

#9814 Icinga DB feature: normalize several Redis data not to crash the Go daemon
  lib/icingadb/icingadb-objects.cpp
Labels: bug, area/icingadb, cla/signed

#9819 Add syslog logging to SELinux during usage of sudo
  tools/selinux/icinga2.te
Labels: cla/signed

#9787 Windows: bump OpenSSL v1.1 (soon EOL) -> v3.0
  CMakeLists.txt
  doc/21-development.md
  doc/win-dev.ps1
  tools/win32/configure.ps1
Labels: area/windows, backported, cla/signed

#9827 Application::m_LastReloadFailed: if double isn't always lock free, use uint32_t
  lib/base/application.hpp
Labels: core/build-fix, cla/signed

#9824 Icinga 2.13.8
  CHANGELOG.md
  ICINGA2_VERSION
Labels: cla/signed

#9760 Icinga 2.14
  CHANGELOG.md
  ICINGA2_VERSION
  doc/16-upgrading-icinga-2.md
Labels: cla/signed

#9746 Adds ProgressPreference SilentlyContinue
  doc/win-dev.ps1
Labels: cla/signed

#9734 Remove unused Stream#Peek()
  lib/base/fifo.cpp
  lib/base/fifo.hpp
  lib/base/stream.cpp
  lib/base/stream.hpp
Labels: core/quality, cla/signed

#9759 ssl_cert allow HTTP request URL setting
  doc/10-icinga-template-library.md
  itl/plugins-contrib.d/web.conf
Labels: cla/signed

#9830 Release issue template: restore non-trivial info from removed RELEASE.md
  .github/ISSUE_TEMPLATE/release.md
Labels: cla/signed

#9828 Replace `RELEASE.md' with issue template
  .github/ISSUE_TEMPLATE/release.md
  RELEASE.md
Labels: cla/signed
