Repository Icinga/icinga2, pull requests merged in 2023-10, with the labels that each got.

#9863 GHA: drop EOL Ubuntu 22.10
  .github/workflows/linux.yml
Labels: area/ci, consider backporting, cla/signed

#9871 GHA: add upcoming (already frozen) Fedora 39
  .github/workflows/linux.yml
Labels: area/ci, cla/signed

#9872 GHA: add upcoming (already frozen) Ubuntu 23.10
  .github/workflows/linux.yml
Labels: area/ci, cla/signed

#9875 Fix downtime host/service name attribute descriptions
  doc/09-object-types.md
Labels: bug, area/documentation, consider backporting, cla/signed

#9878 Fix link text for Downtime* Event Stream Types
  doc/12-icinga2-api.md
Labels: area/documentation, consider backporting, cla/signed

#9882 Remove dead code in GetSignatureAlgorithm()
  lib/base/tlsutility.cpp
Labels: core/quality, cla/signed

#9883 Document host Common Runtime Attribute
  doc/09-object-types.md
Labels: area/documentation, consider backporting, cla/signed
