Repository Icinga/icinga2, pull requests merged in 2023-01, with the labels that each got.

#9624 Make compilable on Boost v1.81
  lib/base/string.cpp
  lib/base/string.hpp
  lib/remote/httphandler.cpp
  lib/remote/httpserverconnection.cpp
Labels: consider backporting, cla/signed

#9594 ConfigObjectUtility::GetObjectConfigPath(): just return paths of existing objects
  lib/remote/apilistener-configsync.cpp
  lib/remote/configobjectutility.cpp
  lib/remote/configobjectutility.hpp
Labels: enhancement, area/configuration, cla/signed

#9610 ITL: mongodb: support --ssl-ca-cert-file
  doc/10-icinga-template-library.md
  itl/plugins-contrib.d/databases.conf
Labels: enhancement, area/itl, ref/NC, cla/signed

#9491 Fix compile error on Solaris 11.4
  lib/base/sysloglogger.cpp
Labels: bug, area/setup, cla/signed

#7921 CLang: compile with -fno-limit-debug-info
  CMakeLists.txt
Labels: core/quality, cla/signed

#9611 ITL: vmware: support --open_vm_tools_ok, --no_vm_tools_ok
  doc/10-icinga-template-library.md
  itl/plugins-contrib.d/vmware.conf
Labels: bug, area/itl, good first issue, cla/signed

#9041 check_icmp: double packet loss thresholds
  doc/10-icinga-template-library.md
  itl/command-plugins.conf
Labels: cla/signed

#8595 cluster-zone: consider own zone connected if there's only one endpoint
  lib/methods/clusterzonechecktask.cpp
Labels: bug, area/distributed, area/itl, cla/signed

#9045 ITL: add check_linux_netdev
  doc/10-icinga-template-library.md
  itl/plugins-contrib.d/network-components.conf
Labels: ref/NC, cla/signed

#9603 Namespace: replace behavior classes with a bool
  lib/base/json-script.cpp
  lib/base/math-script.cpp
  lib/base/namespace.cpp
  lib/base/namespace.hpp
  lib/base/scriptframe.cpp
  lib/config/expression.cpp
  lib/icinga/icingaapplication.cpp
Labels: area/configuration, core/quality, cla/signed

#9633 GitHub Actions: no longer test builds on Fedora 35
  .github/workflows/rpm.yml
Labels: area/ci, cla/signed

#9606 INITIALIZE_ONCE_WITH_PRIORITY: use enum for priority values and use std::function
  lib/base/function.hpp
  lib/base/initialize.cpp
  lib/base/initialize.hpp
  lib/base/loader.cpp
  lib/base/loader.hpp
  lib/base/objecttype.cpp
  lib/base/primitivetype.hpp
  lib/base/scriptframe.cpp
  lib/base/type.cpp
  lib/base/type.hpp
  lib/config/configfragment.hpp
  lib/icinga/icingaapplication.cpp
Labels: core/quality, cla/signed

#9637 GHA: revert back to ubuntu-latest
  .github/workflows/raspbian.yml
Labels: area/ci, cla/signed

#9627 Namespace: use rwlock and disable read locking after freeze
  icinga-app/icinga.cpp
  lib/base/function.hpp
  lib/base/initialize.hpp
  lib/base/json-script.cpp
  lib/base/json.cpp
  lib/base/logger.cpp
  lib/base/math-script.cpp
  lib/base/namespace-script.cpp
  lib/base/namespace.cpp
  lib/base/namespace.hpp
  lib/base/scriptframe.cpp
  lib/base/scriptglobal.cpp
  lib/base/scriptutils.cpp
  lib/base/serializer.cpp
  lib/base/sysloglogger.cpp
  lib/base/type.cpp
  lib/config/expression.cpp
  lib/db_ido/dbquery.cpp
  lib/icinga/checkresult.cpp
  lib/icinga/cib.cpp
  lib/icinga/downtime.cpp
  lib/icinga/icingaapplication.cpp
  lib/icinga/notification.cpp
  lib/icingadb/icingadb-stats.cpp
  lib/remote/variablequeryhandler.cpp
Labels: area/configuration, core/quality, cla/signed

#9635 GHA: drop EOL OSes
  .github/workflows/raspbian.yml
  .github/workflows/rpm.yml
Labels: area/ci, cla/signed

#9636 GHA: let GitHub cancel redundant jobs
  .github/workflows/deb.yml
  .github/workflows/docker.yml
  .github/workflows/raspbian.yml
  .github/workflows/rpm.yml
  .github/workflows/windows.yml
Labels: area/ci, cla/signed

#9424 Run only a single job per workflow at a time
  .github/workflows/deb.yml
  .github/workflows/raspbian.yml
  .github/workflows/rpm.yml
  .github/workflows/windows.yml
Labels: cla/signed

#8005 check_http: support --verify-host
  doc/10-icinga-template-library.md
  itl/command-plugins.conf
Labels: enhancement, area/itl, cla/signed

#9056 check_logfiles: --winwarncrit is a flag, not a param
  itl/plugins-contrib.d/logmanagement.conf
Labels: cla/signed

#7958 /v1/actions/*: return 404 if no objects found
  lib/remote/actionshandler.cpp
Labels: bug, area/api, cla/signed

#7863 Disallow fetching the ticket salt via REST API
  lib/remote/variablequeryhandler.cpp
Labels: cla/signed

#9641 Some trivial code optimisations
  lib/base/loader.cpp
  lib/base/value-operators.cpp
  lib/config/configitem.cpp
  lib/icinga/checkcommand.hpp
  lib/icinga/eventcommand.hpp
  lib/remote/apilistener.cpp
  lib/remote/configobjectutility.cpp
Labels: core/quality, cla/signed

#9599 Influx DB: don't unneccessarily truncate timestamps to whole seconds
  lib/perfdata/influxdbcommonwriter.cpp
Labels: area/influxdb, core/quality, cla/signed

#9608 Move Types namespace into type.cpp and simplify Type::GetByName()
  lib/base/scriptframe.cpp
  lib/base/type.cpp
Labels: area/configuration, core/quality, ref/IP, cla/signed

#8118 Speed up config object lookup
  lib/base/configtype.cpp
  lib/base/configtype.hpp
Labels: core/quality, cla/signed

#9539 Add the Option to disable RetryWrites to CheckCommand of mongodb
  doc/10-icinga-template-library.md
  itl/plugins-contrib.d/databases.conf
Labels: area/itl, cla/signed

#9642 ITL: let check_disk choose sane default units by itself
  doc/10-icinga-template-library.md
  itl/command-plugins.conf
Labels: area/itl, cla/signed

#9640 GHA: build Icinga 2 from source
  .github/workflows/deb.yml
  .github/workflows/linux.bash
  .github/workflows/linux.yml
  .github/workflows/raspbian.yml
  .github/workflows/rpm.yml
Labels: area/ci, cla/signed

#9264 Doc: SUSE: install monitoring-plugins-all
  doc/02-installation.md
Labels: area/documentation, cla/signed
