Repository Icinga/icinga2, pull requests merged in 2023-04, with the labels that each got.

#9714 Remove CheckResultReader which has been deprecated for 5 major versions
  doc/09-object-types.md
  doc/14-features.md
  lib/compat/CMakeLists.txt
  lib/compat/checkresultreader.cpp
  lib/compat/checkresultreader.hpp
  lib/compat/checkresultreader.ti
  lib/icinga/compatutility.cpp
  tools/syntax/nano/icinga2.nanorc
Labels: enhancement, area/compat, core/quality, cla/signed

#9742 etc/icinga2/scripts/mail-*-notification.sh: render Icinga DB Web URLs
  etc/icinga2/scripts/mail-host-notification.sh
  etc/icinga2/scripts/mail-service-notification.sh
Labels: bug, area/notifications, area/icingadb, cla/signed

#8627 Fix update execution message discarded. refs #8616
  lib/icinga/apiactions.cpp
  lib/icinga/clusterevents.cpp
Labels: cla/signed

#9725 ApiListener#NewClientHandlerInternal(): on basic_socket#cancel() (due to timeout) don't ssl::stream#async_shutdown()
  lib/remote/apilistener.cpp
Labels: bug, area/distributed, ref/IP, ref/NC, consider backporting, cla/signed

#9741 Docs: Monitoring Basics: make Event Commands not a subsection of Dependencies
  doc/03-monitoring-basics.md
Labels: bug, area/documentation, cla/signed
