Repository Icinga/icinga2, pull requests merged in 2024-02, with the labels that each got.

#9993 IoEngine: Always log coroutine exception diagnostics
  lib/base/io-engine.hpp
Labels: ref/IP, cla/signed

#9736 Stream#Read(): remove de facto unused param allow_partial
  lib/base/fifo.cpp
  lib/base/fifo.hpp
  lib/base/networkstream.cpp
  lib/base/networkstream.hpp
  lib/base/stdiostream.cpp
  lib/base/stdiostream.hpp
  lib/base/stream.cpp
  lib/base/stream.hpp
  test/base-fifo.cpp
Labels: cla/signed

#9994 Drop redundant `CpuBoundWork` usages in `lib/remote`
  lib/remote/eventshandler.cpp
  lib/remote/httpserverconnection.cpp
  lib/remote/jsonrpcconnection.cpp
Labels: area/distributed, core/quality, consider backporting, cla/signed

#9992 Drop redundant `CpuBoundWork` usage in `JsonRpcConnection::Disconnect()`
  lib/remote/jsonrpcconnection.cpp
Labels: area/distributed, core/quality, ref/IP, consider backporting, cla/signed

#9575 WorkQueue#ParallelFor(): allocate lambda once per thread, not once per item
  lib/base/workqueue.hpp
Labels: core/quality, cla/signed

#8011 Reset all signal handlers of child processes
  lib/base/process.cpp
Labels: area/checks, consider backporting, cla/signed

#9999 ApiListener: Reset `m_LogMessageCount` when rotating
  lib/remote/apilistener.cpp
Labels: bug, area/distributed, ref/IP, consider backporting, cla/signed

#9980 Process `config::update/delete` cluster events gracefully
  lib/remote/apilistener-configsync.cpp
  lib/remote/apilistener.hpp
  lib/remote/configobjectutility.cpp
Labels: bug, area/distributed, ref/IP, ref/NC, area/runtime, consider backporting, cla/signed

#9997 ApiListener#ListenerCoroutineProc(): get remote endpoint ASAP for logging
  lib/remote/apilistener.cpp
Labels: bug, area/distributed, ref/IP, cla/signed

#10009 OpenTsdbWriter#CheckResultHandler(): clarify log messages
  lib/perfdata/opentsdbwriter.cpp
Labels: area/opentsdb, area/log, core/quality, cla/signed
