Repository Icinga/icinga2, pull requests merged in 2024-05, with the labels that each got.

#10049 Downtime::AddDowntime(): NULL-check pointer before deref not to crash
  lib/icinga/apiactions.cpp
  lib/icinga/downtime.cpp
  lib/icinga/downtime.hpp
  lib/icinga/externalcommandprocessor.cpp
  lib/icinga/scheduleddowntime.cpp
Labels: bug, area/api, core/crash, ref/IP, consider backporting, cla/signed

#10050 docs: Drop `last_in_downtime` attrs
  doc/09-object-types.md
Labels: bug, area/documentation, cla/signed

#9941 release.md: Merge docker-icinga2 dependency updates
  .github/ISSUE_TEMPLATE/release.md
Labels: cla/signed

#9960 Document root user usage in installation
  doc/02-installation.md
Labels: enhancement, area/documentation, cla/signed

#10066 Remove unused Checkable#RemoveAllDowntimes()
  lib/icinga/checkable-downtime.cpp
  lib/icinga/checkable.hpp
Labels: core/quality, cla/signed

#9749 ITL: check_disk: ignore more fuse* filesystems
  doc/10-icinga-template-library.md
  itl/command-plugins.conf
Labels: area/itl, cla/signed

#10065 Update `object#config_hash` after all relations queries
  lib/db_ido/dbobject.cpp
  lib/db_ido/hostdbobject.cpp
  lib/db_ido/servicedbobject.cpp
Labels: bug, area/db-ido, ref/IP, cla/signed

#9758 Fix ssl_cert deprecation warnings
  doc/10-icinga-template-library.md
  itl/plugins-contrib.d/web.conf
Labels: area/itl, cla/signed

#9881 check_ssl_cert: integrate new option to set maximum validity
  doc/10-icinga-template-library.md
  itl/plugins-contrib.d/web.conf
Labels: area/itl, cla/signed

#10048 GHA: Docker: don't run on support/* branches
  .github/workflows/docker.yml
Labels: enhancement, area/itl, area/ci, consider backporting, cla/signed

#10062 Don't fail to remove obsolete downtimes
  lib/icinga/apiactions.cpp
  lib/icinga/downtime.cpp
  lib/icinga/downtime.hpp
  lib/icinga/externalcommandprocessor.cpp
  lib/icinga/scheduleddowntime.cpp
Labels: bug, ref/IP, area/runtime, consider backporting, cla/signed
