Repository Icinga/icinga2, pull requests merged in 2024-06, with the labels that each got.

#10056 Update 06-distributed-monitoring.md
  AUTHORS
  doc/06-distributed-monitoring.md
Labels: area/documentation, cla/signed

#10075 Update GitHub actions
  .github/workflows/authors-file.yml
  .github/workflows/docker.yml
  .github/workflows/linux.yml
  CMakeLists.txt
Labels: bug, enhancement, area/itl, area/windows, area/ci, cla/signed

#10079 Bump OpenSSL shipped for Windows to v3.0.14
  doc/win-dev.ps1
  tools/win32/configure.ps1
Labels: area/windows, cla/signed

#10071 Add missing `Object{created,deleted,modified}` docs
  doc/12-icinga2-api.md
Labels: bug, area/documentation, cla/signed

#10084 Bump Windows deps
  doc/21-development.md
  doc/win-dev.ps1
  tools/win32/configure-dev.ps1
  tools/win32/configure.ps1
Labels: area/windows, cla/signed

#10060 IcingaDB#SerializeState(): limit execution_time and latency to 2^32-1
  lib/icingadb/icingadb-objects.cpp
Labels: bug, area/icingadb, ref/IP, cla/signed

#10087 Update GitHub actions
  .github/workflows/authors-file.yml
  .github/workflows/docker.yml
  .github/workflows/linux.yml
  CMakeLists.txt
Labels: bug, enhancement, area/itl, area/windows, area/ci, cla/signed

#10089 Bump Windows deps
  doc/21-development.md
  doc/win-dev.ps1
  tools/win32/configure-dev.ps1
  tools/win32/configure.ps1
Labels: area/windows, cla/signed

#10061 Strip '\r' in notification messages to avoid 'Content-Type: application/octet-stream'
  etc/icinga2/scripts/mail-host-notification.sh
  etc/icinga2/scripts/mail-service-notification.sh
Labels: bug, area/notifications, area/setup, ref/IP
