Repository Icinga/icinga2, pull requests merged in 2024-03, with the labels that each got.

#9967 Fix typo in API Doc example
  AUTHORS
  doc/12-icinga2-api.md
Labels: bug, area/documentation, cla/signed

#10018 Revert "Process `config::update/delete` cluster events gracefully"
  lib/remote/apilistener-configsync.cpp
  lib/remote/apilistener.hpp
  lib/remote/configobjectutility.cpp
Labels: bug, area/distributed, ref/IP, ref/NC, area/runtime, cla/signed

#9953 Fix typo in 12-icinga2-api.md
  AUTHORS
  doc/12-icinga2-api.md
Labels: cla/signed
