Repository Icinga/icinga2, pull requests merged in 2024-08, with the labels that each got.

#10013 Fix broken runtime config sync
  lib/remote/apilistener-configsync.cpp
  lib/remote/configobjectslock.cpp
  lib/remote/configobjectslock.hpp
  lib/remote/configobjectutility.cpp
  lib/remote/createobjecthandler.cpp
  lib/remote/deleteobjecthandler.cpp
  lib/remote/modifyobjecthandler.cpp
Labels: bug, blocker, area/distributed, ref/NC, area/runtime, consider backporting, cla/signed

#10107 Timeperiods: fix off by one when calculating n-th last weekday of the month
  lib/icinga/legacytimeperiod.cpp
  test/CMakeLists.txt
  test/icinga-legacytimeperiod.cpp
Labels: bug, area/runtime, consider backporting, cla/signed

#10015 /v1/debug/malloc_info: call malloc_info(3) if available
  CMakeLists.txt
  config.h.cmake
  doc/12-icinga2-api.md
  lib/remote/CMakeLists.txt
  lib/remote/mallocinfohandler.cpp
  lib/remote/mallocinfohandler.hpp
Labels: enhancement, area/api, cla/signed

#9983 Fix broken `TimePeriod/ScheduledDowntime`s
  lib/icinga/legacytimeperiod.cpp
  lib/icinga/timeperiod.cpp
  test/CMakeLists.txt
  test/icinga-legacytimeperiod.cpp
Labels: bug, area/configuration, ref/IP, area/runtime, consider backporting, cla/signed

#10116 Docs: Add missing angle bracket
  doc/12-icinga2-api.md
Labels: bug, area/documentation, cla/signed

#10115 doc/03-monitoring-basics.md: fix invalid link address
  doc/03-monitoring-basics.md
Labels: bug, area/documentation, consider backporting, cla/signed

#10114 Bump Boost shipped for Windows to v1.86
  doc/win-dev.ps1
  tools/win32/configure-dev.ps1
  tools/win32/configure.ps1
Labels: area/windows, consider backporting, cla/signed

#10118 doc/21-development.md: fix bad link address
  doc/21-development.md
Labels: area/documentation, consider backporting, cla/signed

#10120 doc/02-installation.md: remove outdated info
  doc/02-installation.md
Labels: area/documentation, cla/signed

#10090 Clarify that our Debian installation docs also apply to the Raspberry Pi OS
  .github/workflows/linux.yml
  doc/02-installation.md
  doc/02-installation.md.d/03-Raspberry-Pi-OS.md
  doc/02-installation.md.d/03-Raspbian.md
  doc/13-addons.md
Labels: enhancement, area/documentation, area/setup, consider backporting, cla/signed

#10112 Overhaul Utility::FormatDateTime()
  lib/base/utility.cpp
  lib/base/utility.hpp
  test/CMakeLists.txt
  test/base-utility.cpp
  test/icinga-legacytimeperiod.cpp
Labels: bug, ref/IP, cla/signed

#9975 add multiplier option to check_snmp which is available since monitori…
  doc/10-icinga-template-library.md
  itl/command-plugins.conf
Labels: area/itl, cla/signed

#10111 Unregister invalid config objects properly
  lib/config/configitem.cpp
Labels: bug, area/api, consider backporting, cla/signed

#9974 Fix ITL for http CheckCommand definition
  AUTHORS
  doc/10-icinga-template-library.md
  itl/command-plugins.conf
Labels: area/itl, cla/signed

#10136 .deb: let user install icinga-archive-keyring package
  doc/02-installation.md
Labels: bug, area/documentation, area/setup, consider backporting, cla/signed

#9205 Add check_curl to ITL
  doc/10-icinga-template-library.md
  itl/command-plugins.conf
Labels: area/itl, cla/signed

#10011 Checkable: Don't recalculate `next_check` for remotely generated `cr`
  lib/icinga/checkable-check.cpp
Labels: bug, area/distributed, area/checks, consider backporting, cla/signed
