Repository Icinga/icinga2, pull requests merged in 2024-09, with the labels that each got.

#10108 Update GitHub actions
  .github/workflows/linux.bash
  .github/workflows/linux.yml
  tools/win32/test.ps1
Labels: area/ci, cla/signed

#10109 Update GitHub actions
  .github/workflows/linux.bash
  .github/workflows/linux.yml
  AUTHORS
  tools/win32/test.ps1
Labels: area/ci, cla/signed

#9991 JsonRpcConnection#Send*(): discard messages ASAP once shutting down
  lib/base/defer.hpp
  lib/remote/apilistener.cpp
  lib/remote/jsonrpcconnection.cpp
  lib/remote/jsonrpcconnection.hpp
Labels: bug, area/distributed, ref/IP, cla/signed

#10147 Utility::ReleaseHelper(): remove detection of EOL distros
  lib/base/utility.cpp
Labels: cla/signed

#10035 check_systemd: Fix executable name and include latest arguments
  doc/03-monitoring-basics.md
  doc/05-service-monitoring.md
  doc/10-icinga-template-library.md
  itl/plugins-contrib.d/systemd.conf
Labels: bug, area/documentation, area/itl, good first issue, cla/signed

#10149 tests: Fix test `FormatDateTime` with invalid formats on macOS/*BSD
  test/base-utility.cpp
Labels: area/tests, cla/signed

#10152 Remove trailing whitespaces in the markdown files of the documentation
  doc/01-about.md
  doc/10-icinga-template-library.md
  doc/11-cli-commands.md
  doc/12-icinga2-api.md
  doc/14-features.md
  doc/18-library-reference.md
  doc/19-technical-concepts.md
  doc/22-selinux.md
  doc/23-migrating-from-icinga-1x.md
  doc/24-appendix.md
Labels: area/documentation, cla/signed

#10146 JsonRpcConnection#Send*(): discard messages ASAP once shutting down
  lib/base/defer.hpp
  lib/remote/apilistener.cpp
  lib/remote/jsonrpcconnection.cpp
  lib/remote/jsonrpcconnection.hpp
Labels: bug, area/distributed, ref/IP, cla/signed

#10145 Overhaul Utility::FormatDateTime()
  lib/base/utility.cpp
  lib/base/utility.hpp
  test/CMakeLists.txt
  test/base-utility.cpp
  test/icinga-legacytimeperiod.cpp
Labels: bug, ref/IP, cla/signed

#10156 Linux Dev Environment: fix /usr/local/icinga2/etc ownership
  doc/21-development.md
Labels: bug, area/documentation, cla/signed

#10130 Timeperiods: fix off by one when calculating n-th last weekday of the…
  lib/icinga/legacytimeperiod.cpp
  test/CMakeLists.txt
  test/icinga-legacytimeperiod.cpp
Labels: bug, area/runtime, cla/signed

#10129 /v1/debug/malloc_info: call malloc_info(3) if available
  CMakeLists.txt
  config.h.cmake
  doc/12-icinga2-api.md
  lib/remote/CMakeLists.txt
  lib/remote/mallocinfohandler.cpp
  lib/remote/mallocinfohandler.hpp
Labels: enhancement, area/api, cla/signed

#10132 Strip '\r' in notification messages to avoid 'Content-Type: application/octet-stream'
  etc/icinga2/scripts/mail-host-notification.sh
  etc/icinga2/scripts/mail-service-notification.sh
Labels: bug, area/notifications, area/setup, ref/IP

#10125 Mention plugin exit codes outside [0..3] in the plugin output and warning log
  lib/base/process.hpp
  lib/icinga/checkresult.ti
  lib/methods/pluginchecktask.cpp
Labels: enhancement, area/checks, ref/IP, cla/signed

#10119 Bump Boost shipped for Windows to v1.86
  doc/win-dev.ps1
  tools/win32/configure-dev.ps1
  tools/win32/configure.ps1
Labels: area/windows, cla/signed

#10122 Fix broken `TimePeriod/ScheduledDowntime`s
  lib/icinga/legacytimeperiod.cpp
  lib/icinga/timeperiod.cpp
  test/CMakeLists.txt
  test/icinga-legacytimeperiod.cpp
Labels: bug, area/configuration, ref/IP, area/runtime, cla/signed

#10133 Timeperiods: fix off by one when calculating n-th last weekday of the month
  lib/icinga/legacytimeperiod.cpp
  test/CMakeLists.txt
  test/icinga-legacytimeperiod.cpp
Labels: bug, area/runtime, cla/signed

#10128 Fix broken `TimePeriod/ScheduledDowntime`s
  lib/icinga/legacytimeperiod.cpp
  lib/icinga/timeperiod.cpp
  test/CMakeLists.txt
  test/icinga-legacytimeperiod.cpp
Labels: bug, area/configuration, ref/IP, area/runtime, cla/signed

#10127 Downtime::AddDowntime(): NULL-check pointer before deref not to crash
  lib/icinga/apiactions.cpp
  lib/icinga/downtime.cpp
  lib/icinga/downtime.hpp
  lib/icinga/externalcommandprocessor.cpp
  lib/icinga/scheduleddowntime.cpp
Labels: bug, area/api, core/crash, ref/IP, cla/signed

#10160 IcingaDB: Don't sync partially initialised objects
  lib/icingadb/icingadb-objects.cpp
Labels: bug, area/configuration, area/api, core/crash, ref/IP, area/runtime, cla/signed

#10134 Bump Boost shipped for Windows to v1.86
  doc/win-dev.ps1
  tools/win32/configure-dev.ps1
  tools/win32/configure.ps1
Labels: area/windows, cla/signed

#10162 Unregister invalid config objects properly
  lib/config/configitem.cpp
Labels: bug, area/api, cla/signed

#10163 Checkable: Don't recalculate `next_check` while processing remotely genrated check
  lib/icinga/checkable-check.cpp
Labels: bug, area/distributed, area/checks, cla/signed

#10164 IcingaDB: Don't sync partially initialised objects
  lib/icingadb/icingadb-objects.cpp
Labels: bug, area/configuration, area/api, core/crash, ref/IP, area/runtime, cla/signed

#10155 Type#GetLoadDependencies(): VERIFY() that no nullptr is returned
  tools/mkclass/classcompiler.cpp
Labels: core/quality, cla/signed

#10126 Fix broken runtime config sync
  lib/remote/CMakeLists.txt
  lib/remote/apilistener-configsync.cpp
  lib/remote/configobjectslock.cpp
  lib/remote/configobjectslock.hpp
  lib/remote/configobjectutility.cpp
  lib/remote/createobjecthandler.cpp
  lib/remote/deleteobjecthandler.cpp
  lib/remote/modifyobjecthandler.cpp
Labels: bug, area/configuration, blocker, area/distributed, area/api, area/checks, ref/NC, area/runtime, cla/signed

#10169 Type#GetLoadDependencies(): VERIFY() that only config object types are returned
  tools/mkclass/classcompiler.cpp
Labels: core/quality, cla/signed

#10168 Checkable: Don't recalculate `next_check` while processing remotely genrated check
  lib/icinga/checkable-check.cpp
Labels: bug, area/distributed, area/checks, cla/signed

#10165 Overhaul Utility::FormatDateTime()
  lib/base/utility.cpp
  lib/base/utility.hpp
  test/CMakeLists.txt
  test/base-utility.cpp
  test/icinga-legacytimeperiod.cpp
Labels: bug, ref/IP, cla/signed

#10170 Bump OpenSSL shipped for Windows to v3.0.15
  doc/win-dev.ps1
  tools/win32/configure.ps1
Labels: area/windows, consider backporting, cla/signed

#10173 Bump OpenSSL shipped for Windows to v3.0.15
  doc/win-dev.ps1
  tools/win32/configure.ps1
Labels: area/windows, cla/signed

#10174 Add closing quotationmarks in Validator for influxdb writer config
  AUTHORS
  lib/perfdata/influxdbcommonwriter.cpp
Labels: bug, area/influxdb, cla/signed

#10148 Sort config types by their load dependencies once
  lib/base/initialize.hpp
  lib/base/type.cpp
  lib/base/type.hpp
  lib/config/configitem.cpp
  test/CMakeLists.txt
  test/base-type.cpp
Labels: core/quality, cla/signed

#10140 Don't use thread-local var in coroutine & drop superfluous `CpuBoundWork` usage
  lib/methods/ifwapichecktask.cpp
  lib/remote/httpserverconnection.cpp
Labels: bug, consider backporting, cla/signed
