Repository Icinga/icinga2, pull requests merged in 2025-01, with the labels that each got.

#10277 GHA: Amazon Linux: fix broken link to Boost tarball
  .github/workflows/linux.bash
Labels: bug, area/ci, cla/signed

#10275 GHA: drop EOL SUSE versions
  .github/workflows/linux.yml
  .github/workflows/rpm.yml
Labels: area/ci, consider backporting, cla/signed

#10000 Fix broken downtime comment sync
  lib/base/dependencygraph.cpp
  lib/base/dependencygraph.hpp
  lib/remote/apilistener-configsync.cpp
  lib/remote/apilistener.hpp
Labels: bug, area/distributed, ref/IP, area/runtime, consider backporting, cla/signed

#9861 icinga2: address comment loading where host reference is not found
  AUTHORS
  lib/icinga/comment.cpp
Labels: bug, cla/signed

#10081 Update documentation
  AUTHORS
  doc/01-about.md
  doc/02-installation.md
  doc/02-installation.md.d/03-Raspbian.md
  doc/02-installation.md.d/05-CentOS.md
  doc/03-monitoring-basics.md
  doc/05-service-monitoring.md
  doc/06-distributed-monitoring.md
  doc/09-object-types.md
  doc/10-icinga-template-library.md
  doc/11-cli-commands.md
  doc/12-icinga2-api.md
  doc/13-addons.md
  doc/14-features.md
  doc/15-troubleshooting.md
  doc/17-language-reference.md
  doc/18-library-reference.md
  doc/19-technical-concepts.md
  doc/21-development.md
  doc/22-selinux.md
  doc/23-migrating-from-icinga-1x.md
  doc/24-appendix.md
  lib/icinga/checkable-check.cpp
  tools/selinux/icinga2.te
Labels: bug, enhancement, area/documentation, area/setup, cla/signed

#10261 ITL vmware-esx-soap-host-net{,-nic}: Add missing option "--unplugged_nics_state"
  AUTHORS
  doc/10-icinga-template-library.md
  itl/plugins-contrib.d/vmware.conf
Labels: enhancement, area/itl, cla/signed

#10196 Added the `--dane` option to the command definition ssl_cert
  doc/10-icinga-template-library.md
  itl/plugins-contrib.d/web.conf
Labels: enhancement, area/itl, cla/signed

#10281 GHA: also test SLES, not just openSUSE
  .github/workflows/linux.bash
  .github/workflows/linux.yml
Labels: enhancement, area/ci, consider backporting, cla/signed

#10283 Update ITL for check_ssh
  doc/10-icinga-template-library.md
  itl/command-plugins.conf
Labels: enhancement, area/itl, cla/signed

#10254 Timeout: use less resources, clean them up better and make cancellation deterministic
  lib/base/io-engine.cpp
  lib/base/io-engine.hpp
  lib/base/tlsstream.cpp
  lib/icingadb/redisconnection.cpp
  lib/icingadb/redisconnection.hpp
  lib/methods/ifwapichecktask.cpp
  lib/remote/apilistener.cpp
  test/CMakeLists.txt
  test/base-io-engine.cpp
Labels: core/quality, consider backporting, cla/signed

#10284 21-development.md: fix indentation
  doc/21-development.md
Labels: bug, area/documentation, cla/signed

#10289 Fix and cleanup broken and obsolete links
  doc/02-installation.md
  doc/04-configuration.md
  doc/08-advanced-topics.md
  doc/12-icinga2-api.md
  doc/13-addons.md
  doc/15-troubleshooting.md
  doc/21-development.md
Labels: cla/signed

#10188 IcingaDB Check: Multiple Responsible Instances
  lib/icingadb/icingadbchecktask.cpp
Labels: area/icingadb, ref/IP, cla/signed

#10077 Reject infinite performance data values
  lib/base/perfdatavalue.cpp
  test/icinga-perfdata.cpp
Labels: cla/signed

#10294 Log slow HTTP/RPC processing stats
  lib/remote/httpserverconnection.cpp
  lib/remote/jsonrpcconnection.cpp
  lib/remote/jsonrpcconnection.hpp
Labels: cla/signed

#10295 JsonRpcConnection: don't write new messages on shutdown
  lib/remote/jsonrpcconnection.cpp
Labels: cla/signed

#10296 Address comment loading where host reference is not found gracefully
  AUTHORS
  lib/icinga/comment.cpp
Labels: cla/signed

#10298 IcingaDB: limit several numbers not to crash Go daemon
  lib/icingadb/icingadb-objects.cpp
  lib/icingadb/icingadb-utility.cpp
Labels: cla/signed

#10287 21-development.md: support Windows Server
  doc/21-development.md
Labels: bug, area/documentation, area/windows, cla/signed

#10058 Ido*sqlConnection#FieldToEscapedString(): don't write out of range time
  lib/db_ido_mysql/idomysqlconnection.cpp
  lib/db_ido_pgsql/idopgsqlconnection.cpp
Labels: bug, area/db-ido, ref/IP, cla/signed

#10293 Add a dedicated method for disconnecting TLS connections
  lib/base/io-engine.cpp
  lib/base/io-engine.hpp
  lib/base/tlsstream.cpp
  lib/base/tlsstream.hpp
  lib/icingadb/redisconnection.cpp
  lib/icingadb/redisconnection.hpp
  lib/methods/ifwapichecktask.cpp
  lib/remote/apilistener.cpp
  lib/remote/httpserverconnection.cpp
  lib/remote/jsonrpcconnection.cpp
  test/CMakeLists.txt
  test/base-io-engine.cpp
Labels: cla/signed

#10300 IDO: timestamp out of range errors
  lib/db_ido_mysql/idomysqlconnection.cpp
  lib/db_ido_pgsql/idopgsqlconnection.cpp
Labels: cla/signed

#10291 Update GitHub Actions
  .github/workflows/linux.bash
  .github/workflows/linux.yml
  .github/workflows/rpm.yml
Labels: area/ci, cla/signed

#10279 release.md: don't update doc/21-development.md
  .github/ISSUE_TEMPLATE/release.md
Labels: cla/signed

#9732 Silence compiler warnings in code we don't maintain
  CMakeLists.txt
  icinga-app/CMakeLists.txt
  lib/base/CMakeLists.txt
  lib/db_ido_mysql/CMakeLists.txt
  lib/db_ido_pgsql/CMakeLists.txt
  lib/icingadb/CMakeLists.txt
  lib/mysql_shim/CMakeLists.txt
  lib/pgsql_shim/CMakeLists.txt
  third-party/cmake/BoostTestTargets.cmake
Labels: core/quality, cla/signed

#10137 On Windows, don't create C:\Program Files\Icinga2\var during MSI build
  icinga-app/CMakeLists.txt
  lib/base/CMakeLists.txt
  lib/remote/CMakeLists.txt
Labels: bug, area/windows, consider backporting, cla/signed

#10304 On Windows, don't create C:\Program Files\Icinga2\var during MSI build
  icinga-app/CMakeLists.txt
  lib/base/CMakeLists.txt
  lib/remote/CMakeLists.txt
Labels: bug, area/windows, cla/signed

#10305 On Windows, don't create C:\Program Files\Icinga2\var during MSI build
  icinga-app/CMakeLists.txt
  lib/base/CMakeLists.txt
  lib/remote/CMakeLists.txt
Labels: bug, area/windows, cla/signed

#10314 tools/win32/configure*.ps1: allow custom $CMAKE_ARGS (JSON array)
  tools/win32/configure-dev.ps1
  tools/win32/configure.ps1
Labels: area/windows, cla/signed

#10244 IcingaDB: limit several numbers not to crash Go daemon
  lib/icingadb/icingadb-objects.cpp
  lib/icingadb/icingadb-utility.cpp
Labels: bug, area/icingadb, ref/IP, cla/signed

#10315 tools/win32/configure*.ps1: allow custom $CMAKE_ARGS (JSON array)
  tools/win32/configure-dev.ps1
  tools/win32/configure.ps1
Labels: area/windows, cla/signed

#10313 Icinga 2.14.4
  CHANGELOG.md
  ICINGA2_VERSION
Labels: cla/signed

#8169 GET /v1/objects/*: handle "attrs":[] as expected
  lib/remote/objectqueryhandler.cpp
Labels: bug, area/api, cla/signed

#10322 docs: Document `mail-{host,service}-notification` `-X` option
  doc/03-monitoring-basics.md
Labels: area/documentation, cla/signed

#10318 Include Nagios in the migration docs
  doc/23-migrating-from-icinga-1x.md
Labels: area/documentation, cla/signed

#9943 Disable TLS renegotiation and fix compile error on OpenBSD
  lib/base/tlsutility.cpp
Labels: core/build-fix, cla/signed

#10324 Include Nagios in the migration docs
  doc/23-migrating-from-icinga-1x.md
Labels: cla/signed
