Repository Icinga/icinga2, pull requests merged in 2025-05, with the labels that each got.

#10426 Include "procs-to-show"to ITL check_load command
  doc/10-icinga-template-library.md
  itl/command-plugins.conf
Labels: area/itl, cla/signed

#10384 GHA: AUTHORS: ignore dependabot[bot]
  .github/workflows/authors-file.yml
Labels: good first issue, cla/signed

#10430 GHA: Fix amazonlinux:2023 MariaDB package
  .github/workflows/linux.bash
Labels: area/ci, cla/signed

#10418 Improvements to core dumps section in developer documentation (and some smaller stuff)
  doc/19-technical-concepts.md
  doc/21-development.md
Labels: cla/signed

#10421 doc/08-advanced-topics.md: Reference CheckResult state
  doc/08-advanced-topics.md
Labels: area/documentation, cla/signed

#10323 Update Icinga 2 CLI Commands Documentation
  doc/11-cli-commands.md
Labels: area/documentation, cla/signed

#10432 Fix PerfdataValue Counter Parsing
  lib/base/perfdatavalue.cpp
  test/icinga-perfdata.cpp
Labels: bug, area/checks, cla/signed

#10265 RedisConnection#Connect(): get rid of spin lock
  lib/base/io-engine.cpp
  lib/base/io-engine.hpp
  lib/icingadb/redisconnection.cpp
  lib/icingadb/redisconnection.hpp
  lib/remote/jsonrpcconnection.hpp
Labels: area/icingadb, core/quality, ref/NC, cla/signed

#10429 Fix broken SELinux policy on Fedora `>=41` systems
  tools/selinux/icinga2.fc
Labels: bug, cla/signed

#10361 Notification: Reset internal states on (missed)recovery
  lib/icinga/notification.cpp
Labels: bug, area/notifications, ref/IP, cla/signed

#10433 GitHub Actions: Show log files in Windows jobs
  .github/workflows/windows.yml
Labels: area/ci, cla/signed

#10438 GHA: AUTHORS: use sed(1), not grep(1)
  .github/workflows/authors-file.yml
Labels: area/ci, cla/signed

#10379 IcingaDB: Sync downtime `cancel_time` conditionally
  lib/icingadb/icingadb-objects.cpp
Labels: bug, area/icingadb, cla/signed

#10441 Markdown: indent 2nd-level <ul> with 4 spaces, not 1
  doc/19-technical-concepts.md
Labels: bug, area/documentation, cla/signed

#10070 If skipped due to time period, schedule next check on next transition
  lib/checker/checkercomponent.cpp
Labels: bug, area/checks, cla/signed

#10442 Fix two low-hanging fruit compiler warnings
  lib/icinga/comment.ti
  lib/icinga/dependency.ti
  lib/icinga/downtime.ti
  lib/icinga/notification.cpp
  lib/icinga/notification.ti
  lib/icinga/scheduleddowntime.ti
  lib/icinga/service.ti
  lib/icingadb/icingadb-objects.cpp
Labels: core/quality, cla/signed

#10444 Remove unused ProcessingResult::NoCheckResult
  lib/icinga/apiactions.cpp
  lib/icinga/checkable-check.cpp
  lib/icinga/checkable-script.cpp
  lib/icinga/checkable.hpp
Labels: core/quality, cla/signed

#10446 19-technical-concepts.md: correct cold startup duration
  doc/19-technical-concepts.md
Labels: bug, area/documentation, cla/signed

#10449 GHA: Fix amazonlinux:2023 MariaDB package
  .github/workflows/linux.bash
Labels: area/ci, cla/signed

#10448 GHA: Fix amazonlinux:2023 MariaDB package
  .github/workflows/linux.bash
Labels: area/ci, cla/signed

#10445 Bump Windows OpenSSL version to `3.0.16`
  doc/win-dev.ps1
  tools/win32/configure.ps1
Labels: area/windows, consider backporting, cla/signed, dependencies

#10451 Bump Windows OpenSSL version to `3.0.16`
  doc/win-dev.ps1
  tools/win32/configure.ps1
Labels: area/windows, cla/signed, dependencies

#10447 Bump Windows OpenSSL version to `3.0.16`
  doc/win-dev.ps1
  tools/win32/configure.ps1
Labels: area/windows, cla/signed, dependencies

#10453 GHA: Unbreak Windows Tests
  tools/win32/test.ps1
Labels: cla/signed

#10443 Checkable: Use correct timeout for rescheduling remote checks
  lib/icinga/checkable-check.cpp
Labels: bug, area/distributed, area/checks, cla/signed

#10419 Support Boost `1.88` on Windows
  doc/win-dev.ps1
  lib/base/win32.hpp
  tools/win32/configure-dev.ps1
  tools/win32/configure.ps1
Labels: area/windows, cla/signed

#10397 Checkable#ProcessCheckResult(): discard🗑️ CR or delay its producers shutdown
  lib/base/CMakeLists.txt
  lib/base/wait-group.cpp
  lib/base/wait-group.hpp
  lib/checker/checkercomponent.cpp
  lib/checker/checkercomponent.hpp
  lib/compat/externalcommandlistener.cpp
  lib/compat/externalcommandlistener.hpp
  lib/db_ido/idochecktask.cpp
  lib/db_ido/idochecktask.hpp
  lib/icinga/apiactions.cpp
  lib/icinga/checkable-check.cpp
  lib/icinga/checkable-script.cpp
  lib/icinga/checkable.hpp
  lib/icinga/checkcommand.cpp
  lib/icinga/checkcommand.hpp
  lib/icinga/clusterevents-check.cpp
  lib/icinga/clusterevents.cpp
  lib/icinga/externalcommandprocessor.cpp
  lib/icinga/externalcommandprocessor.hpp
  lib/icingadb/icingadbchecktask.cpp
  lib/icingadb/icingadbchecktask.hpp
  lib/livestatus/livestatuslistener.cpp
  lib/livestatus/livestatuslistener.hpp
  lib/livestatus/livestatusquery.cpp
  lib/livestatus/livestatusquery.hpp
  lib/methods/clusterchecktask.cpp
  lib/methods/clusterchecktask.hpp
  lib/methods/clusterzonechecktask.cpp
  lib/methods/clusterzonechecktask.hpp
  lib/methods/dummychecktask.cpp
  lib/methods/dummychecktask.hpp
  lib/methods/exceptionchecktask.cpp
  lib/methods/exceptionchecktask.hpp
  lib/methods/icingachecktask.cpp
  lib/methods/icingachecktask.hpp
  lib/methods/ifwapichecktask.cpp
  lib/methods/ifwapichecktask.hpp
  lib/methods/nullchecktask.cpp
  lib/methods/nullchecktask.hpp
  lib/methods/pluginchecktask.cpp
  lib/methods/pluginchecktask.hpp
  lib/methods/randomchecktask.cpp
  lib/methods/randomchecktask.hpp
  lib/methods/sleepchecktask.cpp
  lib/methods/sleepchecktask.hpp
  lib/remote/apilistener.cpp
  lib/remote/apilistener.hpp
  test/icinga-checkable-flapping.cpp
  test/icinga-checkresult.cpp
  test/livestatus.cpp
Labels: bug, area/checks, cla/signed
