Repository Icinga/icinga2, pull requests merged in 2025-07, with the labels that each got.

#10493 Mention Elasticsearch prefix for indices and various minor fixes
  AUTHORS
  doc/03-monitoring-basics.md
  doc/05-service-monitoring.md
  doc/06-distributed-monitoring.md
  doc/09-object-types.md
  doc/10-icinga-template-library.md
  doc/12-icinga2-api.md
  doc/14-features.md
  doc/15-troubleshooting.md
  doc/16-upgrading-icinga-2.md
  doc/17-language-reference.md
  doc/22-selinux.md
Labels: area/documentation, cla/signed

#10481 docs: Icinga DB Setup for every Distribution
  doc/02-installation.md
Labels: area/documentation, cla/signed

#10387 Introduce Endpoint#messages_received_per_type
  lib/remote/apifunction.cpp
  lib/remote/apifunction.hpp
  lib/remote/endpoint.cpp
  lib/remote/endpoint.hpp
  lib/remote/endpoint.ti
  lib/remote/jsonrpcconnection.cpp
Labels: enhancement, area/distributed, area/api, cla/signed

#10509 GHA: add Ubuntu 25.04
  .github/workflows/linux.yml
Labels: area/ci, consider backporting, cla/signed

#10476 Handle concurrent config package updates gracefully
  lib/remote/configpackageshandler.cpp
  lib/remote/configpackageutility.cpp
  lib/remote/configstageshandler.cpp
  lib/remote/configstageshandler.hpp
Labels: bug, area/api, ref/IP, consider backporting, cla/signed
