Repository Icinga/icinga2, pull requests merged in 2025-02, with the labels that each got.

#9928 API: also log error behind "No data received on new API connection"
  lib/remote/apilistener.cpp
Labels: area/distributed, area/log, core/quality, cla/signed

#10225 Always compile with -Wsuggest-override not to forget `override`
  CMakeLists.txt
Labels: core/quality, cla/signed

#10332 Don't abruptly close anonymous connections
  lib/remote/jsonrpcconnection-pki.cpp
Labels: bug, area/distributed, consider backporting, cla/signed

#10334 Remove RHEL 7 from installation instructions
  AUTHORS
  doc/02-installation.md
Labels: area/documentation, cla/signed

#10335 Document `mail-{host,service}-notification` `-X` option
  doc/03-monitoring-basics.md
Labels: area/documentation, cla/signed

#10336 Add dev docs on windows server
  doc/21-development.md
Labels: area/documentation, cla/signed

#10337 Don't abruptly close anonymous connections
  lib/remote/jsonrpcconnection-pki.cpp
Labels: cla/signed

#10339 PerfData: Don't discard min/max values even if crit/warn thresholds aren’t given
  AUTHORS
  lib/base/perfdatavalue.cpp
  test/CMakeLists.txt
  test/icinga-perfdata.cpp
Labels: bug, cla/signed

#10341 Release v2.14.5
  CHANGELOG.md
  ICINGA2_VERSION
Labels: cla/signed

#10342 tests: fix FormatDateTime with 32-bit time_t
  test/base-utility.cpp
Labels: area/tests, consider backporting, cla/signed

#10343 tests: fix FormatDateTime with 32-bit time_t
  CHANGELOG.md
  test/base-utility.cpp
Labels: area/tests, cla/signed

#8010 ITL: add --extra-opts to plugins supporting it
  doc/10-icinga-template-library.md
  itl/command-plugins.conf
Labels: area/itl, cla/signed
