Repository Icinga/icinga2, pull requests merged in 2025-04, with the labels that each got.

#10399 `Checkable::GetSeverity()`: consider reachability
  lib/icinga/host.cpp
  lib/icinga/service.cpp
Labels: area/runtime, cla/signed

#9949 GHA: also build on Alpine to test LibreSSL which is used on OpenBSD
  .github/workflows/alpine-bash.Dockerfile
  .github/workflows/linux.bash
  .github/workflows/linux.yml
Labels: area/ci, cla/signed

#10401 GHA: Fix Alpine After CMAKE_OPTS Refactoring
  .github/workflows/linux.bash
Labels: bug, core/build-fix, cla/signed

#10290 Sync dependencies to Redis
  lib/icinga/CMakeLists.txt
  lib/icinga/checkable-check.cpp
  lib/icinga/checkable-dependency.cpp
  lib/icinga/checkable-notification.cpp
  lib/icinga/checkable.cpp
  lib/icinga/checkable.hpp
  lib/icinga/dependency-group.cpp
  lib/icinga/dependency.cpp
  lib/icinga/dependency.hpp
  lib/icinga/dependency.ti
  lib/icingadb/icingadb-objects.cpp
  lib/icingadb/icingadb-utility.cpp
  lib/icingadb/icingadb.hpp
  test/CMakeLists.txt
  test/icinga-dependencies.cpp
Labels: cla/signed

#10402 Raise cmake minimum required version to `3.8...3.17`
  CMakeLists.txt
Labels: bug, core/build-fix, consider backporting, cla/signed

#10395 Update command-plugins.conf to ensure compatibility with nagios-plugins' check_disk
  doc/10-icinga-template-library.md
  itl/command-plugins.conf
Labels: area/itl, cla/signed

#10396 Update web.conf - Include "--ignore-maximum-validity"
  doc/10-icinga-template-library.md
  itl/plugins-contrib.d/web.conf
Labels: cla/signed

#10403 Drop superfluous cmake modules
  third-party/cmake/FindBISON.cmake
  third-party/cmake/FindFLEX.cmake
  third-party/cmake/FindGit.cmake
  third-party/cmake/GNUInstallDirs.cmake
Labels: core/quality, cla/signed

#10074 Feature/tags for elasticsearchwriter
  doc/09-object-types.md
  doc/14-features.md
  lib/perfdata/elasticsearchwriter.cpp
  lib/perfdata/elasticsearchwriter.hpp
  lib/perfdata/elasticsearchwriter.ti
Labels: enhancement, area/elastic, cla/signed

#10352 Fixed double output for timestamps in debug log
  lib/checker/checkercomponent.cpp
  lib/icinga/checkable-check.cpp
Labels: area/log, cla/signed

#10278 Bump Boost shipped for Windows to v1.87
  doc/win-dev.ps1
  lib/base/io-engine.hpp
  lib/base/tcpsocket.hpp
  lib/icingadb/redisconnection.cpp
  lib/icingadb/redisconnection.hpp
  lib/remote/apilistener.cpp
  lib/remote/jsonrpcconnection.cpp
  test/base-io-engine.cpp
  tools/win32/configure-dev.ps1
  tools/win32/configure.ps1
Labels: area/windows, area/ci, cla/signed

#10427 Load Notification objects after User and UserGroup
  lib/icinga/notification.ti
Labels: bug, area/configuration, cla/signed

#10422 Ensure consistent mktime() DST behavior across different implementations
  .github/workflows/linux.bash
  lib/base/datetime.cpp
  lib/base/utility.cpp
  lib/base/utility.hpp
  lib/icinga/legacytimeperiod.cpp
  test/CMakeLists.txt
  test/base-utility.cpp
  test/icinga-legacytimeperiod.cpp
  test/utils.cpp
  test/utils.hpp
Labels: cla/signed
